import { Injectable, inject } from '@angular/core';
import { sha256 } from 'ethers';

import { ChiaWasmService } from '../chia-wasm.service';
import { bytesToHex, hexToBytes } from '../../utils/chia-hash';
import {
  BuildPgtLockArgs,
  LineageProofShape,
  PgtVoteSpendBuilderService,
  UnsignedCoinSpendHex,
} from '../pgt-driver/pgt-vote-spend-builder.service';
import { PROPERTY_REGISTRY_INNER_PUZZLE_HEX } from './property-registry-inner.puzzle-hex';

/**
 * TS port of the three Phase 4 publish-bundle spend builders in
 * ``populis_protocol/populis_puzzles/mint_publish_driver.py``:
 *
 *   * {@link buildProposalEveLaunchSpend}    ↔ ``build_proposal_eve_launch_spend``
 *   * {@link buildTrackerProposeCoinSpend}   ↔ ``build_tracker_propose_coin_spend``
 *   * {@link buildPgtFirstVoteCoinSpend}     ↔ ``build_pgt_first_vote_coin_spend``
 *   * {@link buildPropertyRegistryRegistrationCoinSpend}
 *       ↔ ``property_registry_driver.build_registration_coin_spend``
 *
 * **Sub-brick 4d.2** of the Mint V2 Publish admin desk brick.  This service
 * supplies the *unsigned* CoinSpends the upcoming
 * ``MintProposalV2PublishRunnerService`` (4d.3) bundles with the wallet's
 * XCH parent spend + the proposer's signed PGT inner solution before
 * posting to ``/admin/committee/propose``.
 *
 * **Cross-repo binding.**  Every output is asserted byte-for-byte equal
 * to the Python builder via the three new sections of
 * ``mint-publish.fixtures.json`` (generated by
 * ``populis_protocol/scripts/dump_mint_publish_fixtures.py``).  If you
 * change either side, regenerate the fixture and run both Karma + pytest.
 *
 * **What this service does NOT do:**
 *
 *   * Sign anything.  All inner-solution signing is the wallet's job; the
 *     spends produced here are unsigned.
 *   * Pick the XCH parent / tracker / PGT coins.  The runner (4d.3) and
 *     the wallet handle coin selection.
 *   * Validate authority / quorum / bill semantics.  Those are protocol
 *     concerns enforced on-chain.
 */
@Injectable({ providedIn: 'root' })
export class MintPublishSpendBuilderService {
  private readonly wasm = inject(ChiaWasmService);
  private readonly pgtVoteBuilder = inject(PgtVoteSpendBuilderService);

  // ── Spend-case constants (mirror governance_singleton_inner.clsp) ──
  /** ``proposal_tracker.clsp`` ``TRK_PROPOSE`` defconstant. */
  static readonly TRK_PROPOSE = 1;

  /** Standard chia singleton top-layer constants (pinned for currency). */
  static readonly SINGLETON_MOD_HASH =
    '0x7faa3253bfddd1e0decb0906b2dc6247bbc4cf608f58345d173adb63e8b47c9f';
  static readonly SINGLETON_LAUNCHER_HASH =
    '0xeff07522495060c066f66f32acc2a77e3a3e737aca8baea4d1a64ea4cdc13da9';

  /** Singleton coin amount (mojos).  All Populis singletons are odd-amount. */
  static readonly SINGLETON_AMOUNT = 1n;

  /** Condition opcodes used by the publish-bundle parent conditions. */
  private static readonly CREATE_COIN = 51n;
  private static readonly ASSERT_COIN_ANNOUNCEMENT = 61n;
  private static readonly ASSERT_PUZZLE_ANNOUNCEMENT = 63n;

  /**
   * Compute the property-registry registration announcement id a mint
   * publish spend must assert.
   *
   * Mirrors
   * ``property_registry_driver.registration_announcement_id``:
   *
   *   ``sha256(property_registry_full_puzzle_hash || 0x50 || property_id_canon)``
   */
  propertyRegistryAnnouncementId(args: PropertyRegistryAnnouncementArgs): string {
    const registryPuzzleHash = hexToBytes(
      this.normalizeHex(args.propertyRegistryPuzzleHash),
    );
    const propertyIdCanon = hexToBytes(this.normalizeHex(args.propertyIdCanon));
    if (registryPuzzleHash.length !== 32) {
      throw new Error(
        'mint-publish-spend: propertyRegistryPuzzleHash must be 32 bytes',
      );
    }
    if (propertyIdCanon.length !== 32) {
      throw new Error(
        'mint-publish-spend: propertyIdCanon must be 32 bytes',
      );
    }
    const input = new Uint8Array(65);
    input.set(registryPuzzleHash, 0);
    input[32] = 0x50;
    input.set(propertyIdCanon, 33);
    return sha256(input);
  }

  /**
   * Serialized CLVM condition:
   * ``(ASSERT_PUZZLE_ANNOUNCEMENT propertyRegistryAnnouncementId(...))``.
   */
  buildPropertyRegistryAssertConditionHex(
    args: PropertyRegistryAnnouncementArgs,
  ): string {
    const clvm = this.clvm();
    const announcementId = hexToBytes(
      this.propertyRegistryAnnouncementId(args),
    );
    const condition = clvm.list([
      clvm.int(MintPublishSpendBuilderService.ASSERT_PUZZLE_ANNOUNCEMENT),
      clvm.atom(announcementId),
    ]);
    return bytesToHex(condition.serialize());
  }

  /**
   * Build the A4 property-registry singleton registration CoinSpend.
   *
   * Mirrors ``property_registry_driver.build_registration_coin_spend``:
   *
   *   * Validates that ``registeredIds`` hashes to the current inner puzzle's
   *     curried ``REGISTERED_IDS_ROOT`` and has ``REGISTRY_VERSION`` entries.
   *   * Rejects duplicate ``propertyIdCanon`` values before building a spend.
   *   * Re-curries the registry inner puzzle to
   *     ``[propertyIdCanon, ...registeredIds]`` and ``version + 1``.
   *   * Wraps the inner solution in chia's singleton top layer solution.
   */
  buildPropertyRegistryRegistrationCoinSpend(
    args: BuildPropertyRegistryRegistrationArgs,
  ): PropertyRegistryRegistrationSpend {
    const clvm = this.clvm();
    const sdk = this.sdk();
    const Coin = sdk.Coin;
    const propertyIdCanon = hexToBytes(this.normalizeHex(args.propertyIdCanon));
    if (propertyIdCanon.length !== 32) {
      throw new Error('mint-publish-spend: propertyIdCanon must be 32 bytes');
    }
    const launcherId = hexToBytes(this.normalizeHex(args.registryLauncherId));
    if (launcherId.length !== 32) {
      throw new Error('mint-publish-spend: registryLauncherId must be 32 bytes');
    }
    const amount = BigInt(args.registryCoin.amount);
    if (amount % 2n === 0n) {
      throw new Error('mint-publish-spend: registry singleton amount must be odd');
    }

    const registeredIdBytes = args.registeredIds.map((id, i) => {
      const bytes = hexToBytes(this.normalizeHex(id));
      if (bytes.length !== 32) {
        throw new Error(`mint-publish-spend: registeredIds[${i}] must be 32 bytes`);
      }
      return bytes;
    });
    if (registeredIdBytes.some((id) => this.bytesEqual(id, propertyIdCanon))) {
      throw new Error('mint-publish-spend: propertyIdCanon is already registered');
    }

    const registryInner = clvm.deserialize(
      hexToBytes(this.normalizeHex(args.registryInnerPuzzleHex)),
    );
    const current = this.parsePropertyRegistryInner(registryInner);
    const currentVersion = current.registryVersion;
    if (currentVersion !== BigInt(registeredIdBytes.length)) {
      throw new Error(
        `mint-publish-spend: registeredIds witness count ${registeredIdBytes.length} ` +
          `does not match registry version ${currentVersion}`,
      );
    }
    const witnessRoot = this.registeredIdsRoot(clvm, registeredIdBytes);
    if (!this.bytesEqual(witnessRoot, current.registeredIdsRoot)) {
      throw new Error(
        `mint-publish-spend: registeredIds witness root ${bytesToHex(witnessRoot)} ` +
          `does not match current registry root ${bytesToHex(current.registeredIdsRoot)}`,
      );
    }

    const newRegisteredIds = [propertyIdCanon, ...registeredIdBytes];
    const newRegisteredIdsRoot = this.registeredIdsRoot(clvm, newRegisteredIds);
    const newVersion = currentVersion + 1n;
    const newInner = current.mod.curry([
      current.selfModHash,
      current.govPubkey,
      clvm.atom(newRegisteredIdsRoot),
      clvm.int(newVersion),
    ]);
    const newInnerPuzzleHash = newInner.treeHash();

    const registryStruct = this.singletonStruct(clvm, launcherId);
    const registryFullPuzzle = this.singletonTopLayer(clvm).curry([
      registryStruct,
      registryInner,
    ]);
    const registryFullPuzzleHash = registryFullPuzzle.treeHash();
    const claimedPuzzleHash = hexToBytes(
      this.normalizeHex(args.registryCoin.puzzleHash),
    );
    if (!this.bytesEqual(registryFullPuzzleHash, claimedPuzzleHash)) {
      throw new Error(
        `mint-publish-spend: built registry full puzzle hash ` +
          `${bytesToHex(registryFullPuzzleHash)} does not match coin's ` +
          `claimed puzzle hash ${bytesToHex(claimedPuzzleHash)}.`,
      );
    }

    const registryCoin = new Coin(
      hexToBytes(this.normalizeHex(args.registryCoin.parentCoinInfo)),
      claimedPuzzleHash,
      amount,
    );
    const innerSolution = clvm.list([
      clvm.int(amount),
      clvm.atom(propertyIdCanon),
      clvm.list(registeredIdBytes.map((id) => clvm.atom(id))),
      clvm.int(newVersion),
    ]);
    const outerSolution = clvm.list([
      this.encodeSingletonLineageProof(clvm, args.lineageProof),
      clvm.int(amount),
      innerSolution,
    ]);
    const aggSigMeMessage = clvm.list([
      clvm.atom(propertyIdCanon),
      clvm.atom(current.registeredIdsRoot),
      clvm.atom(newRegisteredIdsRoot),
      clvm.int(newVersion),
    ]).treeHash();

    return {
      coin: {
        parentCoinInfo: bytesToHex(registryCoin.parentCoinInfo),
        puzzleHash: bytesToHex(registryCoin.puzzleHash),
        amount,
      },
      puzzleReveal: bytesToHex(registryFullPuzzle.serialize()),
      solution: bytesToHex(outerSolution.serialize()),
      announcementId: this.propertyRegistryAnnouncementId({
        propertyRegistryPuzzleHash: bytesToHex(claimedPuzzleHash),
        propertyIdCanon: bytesToHex(propertyIdCanon),
      }),
      newInnerPuzzleHash: bytesToHex(newInnerPuzzleHash),
      newRegisteredIdsRoot: bytesToHex(newRegisteredIdsRoot),
      aggSigMeMessage: bytesToHex(aggSigMeMessage),
    };
  }

  /**
   * Curry ``property_registry_inner.clsp`` for a known registry state.
   *
   * This is used for fresh/eve registry state where no prior registry
   * singleton spend exists to reveal the current curried inner puzzle.
   */
  makePropertyRegistryInnerPuzzleHex(args: MakePropertyRegistryInnerPuzzleArgs): string {
    const clvm = this.clvm();
    const govPubkey = hexToBytes(this.normalizeHex(args.govPubkey));
    if (govPubkey.length !== 48) {
      throw new Error('mint-publish-spend: registry GOV_PUBKEY must be 48 bytes');
    }
    const registeredIds = args.registeredIds.map((id, i) => {
      const bytes = hexToBytes(this.normalizeHex(id));
      if (bytes.length !== 32) {
        throw new Error(`mint-publish-spend: registeredIds[${i}] must be 32 bytes`);
      }
      return bytes;
    });
    const registryVersion = BigInt(args.registryVersion ?? registeredIds.length);
    if (registryVersion !== BigInt(registeredIds.length)) {
      throw new Error(
        `mint-publish-spend: registryVersion ${registryVersion} does not ` +
          `match registeredIds count ${registeredIds.length}`,
      );
    }
    const mod = clvm.deserialize(hexToBytes(PROPERTY_REGISTRY_INNER_PUZZLE_HEX));
    const inner = mod.curry([
      clvm.atom(mod.treeHash()),
      clvm.atom(govPubkey),
      clvm.atom(this.registeredIdsRoot(clvm, registeredIds)),
      clvm.int(registryVersion),
    ]);
    return bytesToHex(inner.serialize());
  }

  // ────────────────────────────────────────────────────────────────────
  //  1. Artifact A launcher → eve hop
  // ────────────────────────────────────────────────────────────────────

  /**
   * Build the launcher → eve singleton launch hop for Artifact A (the V2
   * mint-proposal singleton).
   *
   * Mirrors
   * ``populis_puzzles.mint_publish_driver.build_proposal_eve_launch_spend``
   * which itself wraps chia's ``launch_conditions_and_coinsol``.  The wire
   * conventions emitted here are the standard ``singleton_launcher.clsp``
   * ones:
   *
   *   1. ``parent_conditions`` (length 2):
   *      - ``(CREATE_COIN SINGLETON_LAUNCHER_HASH amount)``
   *      - ``(ASSERT_COIN_ANNOUNCEMENT sha256(launcher_coin_id ||
   *         sha256tree(launcher_solution)))``
   *   2. ``launcher_coin_spend``:
   *      - puzzle reveal: the standard chia ``singleton_launcher.clsp``
   *        bytecode (from ``sdk.Constants.singletonLauncher()``)
   *      - solution: ``(eve_full_puzzle_hash, amount, comment_list=[])``
   *
   * @param args.xchParentCoin     The wallet's XCH coin spent in the same
   *   bundle.  Its coin id becomes the launcher coin's
   *   ``parent_coin_info``.
   * @param args.eveInnerPuzzleHex Serialized V2 mint-proposal inner puzzle
   *   curried for the DRAFT eve state (0x-hex).  Must equal the puzzle
   *   whose tree-hash is the ``eveInnerPuzhash`` the artifact builder
   *   pins.
   * @param args.amount            Singleton coin amount (mojos).  Defaults
   *   to {@link SINGLETON_AMOUNT}.  Must be odd.
   *
   * @returns Typed {@link ProposalEveLaunchSpend} the runner threads into
   *   the publish bundle.
   *
   * @throws if ``amount`` is even (matches Python's ``ValueError``).
   */
  buildProposalEveLaunchSpend(args: BuildProposalEveLaunchArgs): ProposalEveLaunchSpend {
    const amount = BigInt(
      args.amount ?? MintPublishSpendBuilderService.SINGLETON_AMOUNT,
    );
    if (amount % 2n === 0n) {
      throw new Error(
        'mint-publish-spend: amount must be odd (singleton convention)',
      );
    }
    const sdk = this.sdk();
    const clvm = this.clvm();
    const Coin = sdk.Coin;

    // ── 1. Compute the parent coin's coin id (== launcher_coin.parent) ──
    const parent = args.xchParentCoin;
    const parentCoin = new Coin(
      hexToBytes(this.normalizeHex(parent.parentCoinInfo)),
      hexToBytes(this.normalizeHex(parent.puzzleHash)),
      BigInt(parent.amount),
    );
    const parentCoinId = parentCoin.coinId();

    // ── 2. Build the launcher coin ──
    const launcherPuzzleHash = hexToBytes(
      MintPublishSpendBuilderService.SINGLETON_LAUNCHER_HASH,
    );
    const launcherCoin = new Coin(parentCoinId, launcherPuzzleHash, amount);
    const launcherCoinId = launcherCoin.coinId();

    // ── 3. Build the singleton-wrapped eve full puzzle ──
    const eveInnerPuzzle = clvm.deserialize(
      hexToBytes(this.normalizeHex(args.eveInnerPuzzleHex)),
    );
    const singletonStruct = clvm.pair(
      clvm.atom(hexToBytes(MintPublishSpendBuilderService.SINGLETON_MOD_HASH)),
      clvm.pair(
        clvm.atom(launcherCoinId),
        clvm.atom(launcherPuzzleHash),
      ),
    );
    const eveFullPuzzle = this.singletonTopLayer(clvm).curry([
      singletonStruct,
      eveInnerPuzzle,
    ]);
    const eveFullPuzzleHash = eveFullPuzzle.treeHash();

    // ── 4. Build launcher solution: (eve_full_ph, amount, comment_list) ──
    // chia's launch_conditions_and_coinsol passes ``comment`` as a Python
    // list[tuple[str, str]] which Program.to() encodes as a CLVM list of
    // (key . value) pairs.  Our builder mirrors the Python default
    // (empty list) so we pass clvm.nil().
    const launcherSolution = clvm.list([
      clvm.atom(eveFullPuzzleHash),
      clvm.int(amount),
      clvm.nil(),
    ]);
    const launcherSolutionHash = launcherSolution.treeHash();

    // ── 5. Compute the parent's required conditions ──
    // (CREATE_COIN SINGLETON_LAUNCHER_HASH amount)
    const createLauncher = clvm.list([
      clvm.int(MintPublishSpendBuilderService.CREATE_COIN),
      clvm.atom(launcherPuzzleHash),
      clvm.int(amount),
    ]);
    // (ASSERT_COIN_ANNOUNCEMENT sha256(launcher_coin_id || announcement_msg))
    const announceInput = new Uint8Array(
      launcherCoinId.length + launcherSolutionHash.length,
    );
    announceInput.set(launcherCoinId, 0);
    announceInput.set(launcherSolutionHash, launcherCoinId.length);
    const announcementId = hexToBytes(sha256(announceInput));
    const assertAnnouncement = clvm.list([
      clvm.int(MintPublishSpendBuilderService.ASSERT_COIN_ANNOUNCEMENT),
      clvm.atom(announcementId),
    ]);

    // ── 6. Build the launcher coin spend ──
    const launcherPuzzleBytes = this.singletonLauncherBytes(sdk);

    const launcherCoinSpend: UnsignedCoinSpendHex = {
      coin: {
        parentCoinInfo: bytesToHex(launcherCoin.parentCoinInfo),
        puzzleHash: bytesToHex(launcherCoin.puzzleHash),
        amount,
      },
      puzzleReveal: bytesToHex(launcherPuzzleBytes),
      solution: bytesToHex(launcherSolution.serialize()),
    };

    // ── 7. Compute the eve coin ──
    const eveCoin: CoinHexShape = {
      parentCoinInfo: bytesToHex(launcherCoinId),
      puzzleHash: bytesToHex(eveFullPuzzleHash),
      amount,
    };

    return {
      parentConditionsHex: [
        bytesToHex(createLauncher.serialize()),
        bytesToHex(assertAnnouncement.serialize()),
      ],
      launcherCoinSpend,
      eveCoin,
      eveFullPuzzleHash: bytesToHex(eveFullPuzzleHash),
    };
  }

  // ────────────────────────────────────────────────────────────────────
  //  2. Artifact B tracker.PROPOSE CoinSpend
  // ────────────────────────────────────────────────────────────────────

  /**
   * Build the unsigned singleton-wrapped ``TRK_PROPOSE`` CoinSpend.
   *
   * Mirrors
   * ``populis_puzzles.mint_publish_driver.build_tracker_propose_coin_spend``
   * exactly.  The inner solution layout matches the
   * ``governance_singleton_inner.clsp`` dispatcher:
   *
   *   ``(my_id, my_inner_puzzlehash, my_amount, TRK_PROPOSE,
   *      (proposal_hash, bill_op, voter_inner_puzhash, first_vote, deadline))``
   *
   * The PROPOSE handler asserts the PGT lock announcement for
   * ``(voter_inner_puzhash, proposal_hash, first_vote, deadline)``, so the
   * bundled PGT lock spend MUST emit that exact announcement
   * (see {@link buildPgtFirstVoteCoinSpend}).
   *
   * @param args.trackerCoin            Current tracker singleton coin in
   *   IDLE state.  Its puzzle hash MUST equal the singleton-wrapped
   *   ``trackerInnerPuzzleHex`` tree-hash for ``trackerLauncherId``.
   * @param args.trackerInnerPuzzleHex  Serialized IDLE-state curried
   *   tracker inner puzzle (0x-hex).
   * @param args.trackerLauncherId      Tracker singleton launcher id (0x-hex).
   * @param args.lineageProof           Tracker coin's parent lineage proof.
   * @param args.proposalHash           32-byte ``sha256tree(bill_op)`` of
   *   the proposal being opened (0x-hex).
   * @param args.billOperationHex       Serialized bill_op Program (0x-hex).
   *   For a MINT proposal this is ``(BILL_MINT_TAG, deed_full_puzhash,
   *   property_id_canon, property_registry_puzzle_hash)`` — i.e. the
   *   ``billOpProgramHex`` field
   *   {@link MintPublishService.buildMintPublishArtifacts} returns.
   * @param args.voterInnerPuzzleHash   Proposer's PGT free coin inner
   *   puzzle hash (0x-hex).  MUST match the bundled PGT lock spend's
   *   curry.
   * @param args.firstVoteAmount        PGT mojos locked by the bundled
   *   PGT lock spend.  Must be > 0 and equal the PGT coin's amount.
   * @param args.votingDeadline         Absolute uint64 seconds.
   */
  buildTrackerProposeCoinSpend(
    args: BuildTrackerProposeArgs,
  ): UnsignedCoinSpendHex {
    const sdk = this.sdk();
    const clvm = this.clvm();
    const Coin = sdk.Coin;

    // ── Validation (mirrors the Python builder's preconditions) ──
    const proposalHashBytes = hexToBytes(this.normalizeHex(args.proposalHash));
    if (proposalHashBytes.length !== 32) {
      throw new Error('mint-publish-spend: proposalHash must be 32 bytes');
    }
    const voterInnerPh = hexToBytes(
      this.normalizeHex(args.voterInnerPuzzleHash),
    );
    if (voterInnerPh.length !== 32) {
      throw new Error(
        'mint-publish-spend: voterInnerPuzzleHash must be 32 bytes',
      );
    }
    const firstVote = BigInt(args.firstVoteAmount);
    if (firstVote <= 0n) {
      throw new Error('mint-publish-spend: firstVoteAmount must be > 0');
    }
    const deadline = BigInt(args.votingDeadline);
    if (deadline < 0n || deadline > 0xFFFFFFFFFFFFFFFFn) {
      throw new Error('mint-publish-spend: votingDeadline must be a uint64');
    }

    // ── 1. Re-derive the singleton-wrapped tracker puzzle ──
    const trackerInner = clvm.deserialize(
      hexToBytes(this.normalizeHex(args.trackerInnerPuzzleHex)),
    );
    const trackerInnerHash = trackerInner.treeHash();
    const launcherIdBytes = hexToBytes(
      this.normalizeHex(args.trackerLauncherId),
    );
    const trackerStruct = clvm.pair(
      clvm.atom(hexToBytes(MintPublishSpendBuilderService.SINGLETON_MOD_HASH)),
      clvm.pair(
        clvm.atom(launcherIdBytes),
        clvm.atom(hexToBytes(MintPublishSpendBuilderService.SINGLETON_LAUNCHER_HASH)),
      ),
    );
    const trackerFullPuzzle = this.singletonTopLayer(clvm).curry([
      trackerStruct,
      trackerInner,
    ]);
    const expectedFullPh = trackerFullPuzzle.treeHash();
    const claimedPh = hexToBytes(
      this.normalizeHex(args.trackerCoin.puzzleHash),
    );
    if (!this.bytesEqual(expectedFullPh, claimedPh)) {
      throw new Error(
        `mint-publish-spend: built tracker full puzzle hash ${bytesToHex(expectedFullPh)} ` +
          `does not match coin's claimed puzzle hash ${bytesToHex(claimedPh)}.`,
      );
    }

    // ── 2. Build the inner solution ──
    const trackerCoin = new Coin(
      hexToBytes(this.normalizeHex(args.trackerCoin.parentCoinInfo)),
      claimedPh,
      BigInt(args.trackerCoin.amount),
    );
    const myId = trackerCoin.coinId();
    const billOpProgram = clvm.deserialize(
      hexToBytes(this.normalizeHex(args.billOperationHex)),
    );
    const innerSolution = clvm.list([
      clvm.atom(myId),
      clvm.atom(trackerInnerHash),
      clvm.int(BigInt(args.trackerCoin.amount)),
      clvm.int(BigInt(MintPublishSpendBuilderService.TRK_PROPOSE)),
      clvm.list([
        clvm.atom(proposalHashBytes),
        billOpProgram,
        clvm.atom(voterInnerPh),
        clvm.int(firstVote),
        clvm.int(deadline),
      ]),
    ]);

    // ── 3. Build the singleton outer solution ──
    //   (lineage_proof, my_amount, inner_solution)
    const lineageProofProgram = this.encodeLineageProof(
      clvm,
      args.lineageProof,
    );
    const outerSolution = clvm.list([
      lineageProofProgram,
      clvm.int(BigInt(args.trackerCoin.amount)),
      innerSolution,
    ]);

    return {
      coin: {
        parentCoinInfo: bytesToHex(trackerCoin.parentCoinInfo),
        puzzleHash: bytesToHex(claimedPh),
        amount: args.trackerCoin.amount,
      },
      puzzleReveal: bytesToHex(trackerFullPuzzle.serialize()),
      solution: bytesToHex(outerSolution.serialize()),
    };
  }

  // ────────────────────────────────────────────────────────────────────
  //  3. Proposer's PGT first-vote lock CoinSpend (delegated)
  // ────────────────────────────────────────────────────────────────────

  /**
   * Build the proposer's PGT first-vote LOCK CoinSpend.
   *
   * Thin wrapper around
   * {@link PgtVoteSpendBuilderService.buildPgtLockCoinSpend} (Phase 3) —
   * the LOCK spend is already proven byte-equal to the Python builder via
   * the Phase 3 fixture, and the publish flow's only addition is the
   * publish-flow-named entry point that delegates without changing
   * semantics.
   *
   * Per Phase 3's LOCK semantics, the locked amount equals
   * ``pgtCoin.amount`` (LOCK is full-coin; ``extra_delta = 0``).  The
   * wallet MUST have already split the proposer's PGT bag into a coin of
   * exactly ``firstVoteAmount = pgtCoin.amount`` — the tracker's
   * ``firstVoteAmount`` argument MUST equal this same value, or the
   * on-chain LOCK announcement id won't match.
   *
   * @param args ``PgtFirstVoteArgs`` — the same shape as Phase 3's
   *   ``BuildPgtLockArgs`` except ``deadlineSeconds`` is renamed
   *   ``votingDeadline`` for cross-service clarity.
   */
  buildPgtFirstVoteCoinSpend(args: PgtFirstVoteArgs): UnsignedCoinSpendHex {
    const pgtArgs: BuildPgtLockArgs = {
      pgtCoin: args.pgtCoin,
      voterInnerPuzzleHex: args.voterInnerPuzzleHex,
      voterInnerSolutionHex: args.voterInnerSolutionHex,
      trackerLauncherId: args.trackerLauncherId,
      pgtTailHash: args.pgtTailHash,
      lineageProof: args.lineageProof,
      proposalHash: args.proposalHash,
      deadlineSeconds: args.votingDeadline,
    };
    return this.pgtVoteBuilder.buildPgtLockCoinSpend(pgtArgs);
  }

  // ────────────────────────────────────────────────────────────────────
  //  Internals
  // ────────────────────────────────────────────────────────────────────

  private singletonTopLayer(clvm: ClvmShape): ProgramShape {
    const sdk = this.sdk();
    const bytes =
      sdk.Constants?.singletonTopLayerV11?.() ??
      sdk.Constants?.singletonTopLayer?.();
    if (!bytes) {
      throw new Error(
        'mint-publish-spend: chia-wallet-sdk-wasm Constants.singletonTopLayerV11 unavailable',
      );
    }
    return clvm.deserialize(bytes);
  }

  private singletonLauncherBytes(sdk: PublishSdkShape): Uint8Array {
    if (!sdk.Constants?.singletonLauncher) {
      throw new Error(
        'mint-publish-spend: chia-wallet-sdk-wasm Constants.singletonLauncher unavailable',
      );
    }
    return sdk.Constants.singletonLauncher();
  }

  private encodeLineageProof(
    clvm: ClvmShape,
    proof: LineageProofShape | undefined,
  ): ProgramShape {
    // chia's LineageProof.to_program() emits:
    //   - empty proof              →  nil
    //   - eve-only (parent_name)   →  (parent)
    //   - full proof               →  (parent, inner_hash, amount)
    if (
      !proof ||
      (!proof.parentName && !proof.innerPuzzleHash && proof.amount === undefined)
    ) {
      return clvm.nil();
    }
    if (proof.parentName && !proof.innerPuzzleHash && proof.amount === undefined) {
      return clvm.list([
        clvm.atom(hexToBytes(this.normalizeHex(proof.parentName))),
      ]);
    }
    if (
      !proof.parentName ||
      !proof.innerPuzzleHash ||
      proof.amount === undefined
    ) {
      throw new Error(
        'mint-publish-spend: lineage proof must be empty, eve-only ' +
          '(parentName only), or fully populated (all 3 fields).',
      );
    }
    return clvm.list([
      clvm.atom(hexToBytes(this.normalizeHex(proof.parentName))),
      clvm.atom(hexToBytes(this.normalizeHex(proof.innerPuzzleHash))),
      clvm.int(BigInt(proof.amount)),
    ]);
  }

  private encodeSingletonLineageProof(
    clvm: ClvmShape,
    proof: LineageProofShape,
  ): ProgramShape {
    if (!proof?.parentName || proof.amount === undefined) {
      throw new Error(
        'mint-publish-spend: singleton lineage proof requires parentName and amount',
      );
    }
    const parentName = clvm.atom(hexToBytes(this.normalizeHex(proof.parentName)));
    const amount = clvm.int(BigInt(proof.amount));
    if (!proof.innerPuzzleHash) {
      return clvm.list([parentName, amount]);
    }
    return clvm.list([
      parentName,
      clvm.atom(hexToBytes(this.normalizeHex(proof.innerPuzzleHash))),
      amount,
    ]);
  }

  private parsePropertyRegistryInner(inner: ProgramShape): ParsedPropertyRegistryInner {
    const uncurried = inner.uncurry?.();
    const args = uncurried ? this.curriedArgs(uncurried, 'property registry inner') : null;
    if (!uncurried || !args || args.length !== 4) {
      throw new Error(
        `mint-publish-spend: property registry inner expects 4 curried args, ` +
          `got ${args?.length ?? 0}`,
      );
    }
    const govPubkey = args[1].toAtom?.();
    if (!govPubkey || govPubkey.length !== 48) {
      throw new Error('mint-publish-spend: registry GOV_PUBKEY must be 48 bytes');
    }
    const registeredIdsRoot = args[2].toAtom?.();
    if (!registeredIdsRoot || registeredIdsRoot.length !== 32) {
      throw new Error(
        'mint-publish-spend: registry REGISTERED_IDS_ROOT must be 32 bytes',
      );
    }
    const registryVersion = args[3].toInt?.();
    if (registryVersion === undefined || registryVersion < 0n) {
      throw new Error('mint-publish-spend: registry version must be non-negative');
    }
    return {
      mod: uncurried.program,
      selfModHash: args[0],
      govPubkey: args[1],
      registeredIdsRoot,
      registryVersion,
    };
  }

  private curriedArgs(
    uncurried: UncurriedProgramShape,
    label: string,
  ): ProgramShape[] {
    if (Array.isArray(uncurried.args)) {
      return uncurried.args;
    }
    const args = uncurried.args.toList?.();
    if (!args) {
      throw new Error(`mint-publish-spend: ${label} curried args must be a list`);
    }
    return args;
  }

  private registeredIdsRoot(
    clvm: ClvmShape,
    ids: Uint8Array[],
  ): Uint8Array {
    return clvm.list(ids.map((id) => clvm.atom(id))).treeHash();
  }

  private singletonStruct(clvm: ClvmShape, launcherId: Uint8Array): ProgramShape {
    return clvm.pair(
      clvm.atom(hexToBytes(MintPublishSpendBuilderService.SINGLETON_MOD_HASH)),
      clvm.pair(
        clvm.atom(launcherId),
        clvm.atom(hexToBytes(MintPublishSpendBuilderService.SINGLETON_LAUNCHER_HASH)),
      ),
    );
  }

  private normalizeHex(value: string): string {
    return value.startsWith('0x') || value.startsWith('0X') ? value : '0x' + value;
  }

  private bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
    return true;
  }

  private sdk(): PublishSdkShape {
    const sdk = this.wasm.sdk() as PublishSdkShape | undefined;
    if (!sdk?.Clvm || !sdk?.Coin) {
      throw new Error(
        'mint-publish-spend: chia-wallet-sdk-wasm Clvm/Coin exports unavailable',
      );
    }
    return sdk;
  }

  private clvm(): ClvmShape {
    return new (this.sdk().Clvm)();
  }
}

// ──────────────────────────────────────────────────────────────────────
//  Public input/output shapes
// ──────────────────────────────────────────────────────────────────────

export interface CoinHexShape {
  parentCoinInfo: string;
  puzzleHash: string;
  amount: number | bigint;
}

/**
 * Result of {@link MintPublishSpendBuilderService.buildProposalEveLaunchSpend}.
 *
 * Mirrors the Python ``ProposalEveLaunchSpend`` dataclass.  The fixture's
 * ``proposal_eve_launch.expected`` block pins these fields byte-for-byte.
 */
export interface ProposalEveLaunchSpend {
  /**
   * Serialized CLVM ``Program`` conditions the parent XCH coin's spend
   * must emit so that the launcher coin is created at the canonical
   * Artifact A launcher puzzle hash with the canonical eve puzzle
   * pre-announced.  Always length 2: ``[CREATE_COIN, ASSERT_COIN_ANNOUNCEMENT]``.
   */
  parentConditionsHex: string[];
  /** Launcher coin's CoinSpend (puzzle reveal = standard singleton_launcher). */
  launcherCoinSpend: UnsignedCoinSpendHex;
  /** Computed eve singleton coin (parent=launcher_id, ph=eve_full_ph). */
  eveCoin: CoinHexShape;
  /** Singleton-wrapped eve full puzzle hash, 0x-hex. */
  eveFullPuzzleHash: string;
}

export interface BuildProposalEveLaunchArgs {
  /** Wallet's XCH coin spent in the same bundle. */
  xchParentCoin: CoinHexShape;
  /** V2 mint-proposal inner puzzle curried for DRAFT eve state (0x-hex). */
  eveInnerPuzzleHex: string;
  /** Singleton coin amount (mojos).  Default 1. */
  amount?: number | bigint;
}

export interface BuildTrackerProposeArgs {
  trackerCoin: CoinHexShape;
  trackerInnerPuzzleHex: string;
  trackerLauncherId: string;
  lineageProof: LineageProofShape;
  proposalHash: string;
  /** Serialized bill_op Program (0x-hex). */
  billOperationHex: string;
  voterInnerPuzzleHash: string;
  firstVoteAmount: number | bigint;
  votingDeadline: number | bigint;
}

export interface PropertyRegistryAnnouncementArgs {
  propertyRegistryPuzzleHash: string;
  propertyIdCanon: string;
}

export interface BuildPropertyRegistryRegistrationArgs {
  registryCoin: CoinHexShape;
  registryInnerPuzzleHex: string;
  registryLauncherId: string;
  lineageProof: LineageProofShape;
  propertyIdCanon: string;
  registeredIds: string[];
}

export interface PropertyRegistryRegistrationSpend extends UnsignedCoinSpendHex {
  announcementId: string;
  newInnerPuzzleHash: string;
  newRegisteredIdsRoot: string;
  aggSigMeMessage: string;
}

export interface MakePropertyRegistryInnerPuzzleArgs {
  govPubkey: string;
  registeredIds: string[];
  registryVersion?: number | bigint;
}

/**
 * Args for {@link MintPublishSpendBuilderService.buildPgtFirstVoteCoinSpend}.
 *
 * Same shape as Phase 3's ``BuildPgtLockArgs`` except ``deadlineSeconds``
 * is renamed ``votingDeadline`` to match the publish flow naming.
 */
export interface PgtFirstVoteArgs {
  pgtCoin: CoinHexShape;
  voterInnerPuzzleHex: string;
  voterInnerSolutionHex: string;
  trackerLauncherId: string;
  pgtTailHash: string;
  lineageProof: LineageProofShape;
  proposalHash: string;
  votingDeadline: number | bigint;
}

// ── WASM SDK typing (narrowed) ────────────────────────────────────────
interface ProgramShape {
  treeHash(): Uint8Array;
  serialize(): Uint8Array;
  curry(args: ProgramShape[]): ProgramShape;
  uncurry?(): UncurriedProgramShape | null;
  toList?(): ProgramShape[] | null;
  toAtom?(): Uint8Array | null;
  toInt?(): bigint;
}
interface UncurriedProgramShape {
  program: ProgramShape;
  args: ProgramShape[] | ProgramShape;
}
interface ClvmShape {
  deserialize(bytes: Uint8Array): ProgramShape;
  atom(value: Uint8Array): ProgramShape;
  int(value: bigint): ProgramShape;
  list(value: ProgramShape[]): ProgramShape;
  pair(first: ProgramShape, rest: ProgramShape): ProgramShape;
  nil(): ProgramShape;
}
interface CoinClass {
  new (
    parentCoinInfo: Uint8Array,
    puzzleHash: Uint8Array,
    amount: bigint,
  ): {
    parentCoinInfo: Uint8Array;
    puzzleHash: Uint8Array;
    amount: bigint;
    coinId(): Uint8Array;
  };
}
interface PublishSdkShape {
  Clvm: new () => ClvmShape;
  Coin: CoinClass;
  Constants?: {
    singletonTopLayerV11?: () => Uint8Array;
    singletonTopLayer?: () => Uint8Array;
    singletonLauncher?: () => Uint8Array;
  };
}

interface ParsedPropertyRegistryInner {
  mod: ProgramShape;
  selfModHash: ProgramShape;
  govPubkey: ProgramShape;
  registeredIdsRoot: Uint8Array;
  registryVersion: bigint;
}
