import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting } from '@angular/common/http/testing';

import { ChiaWasmService } from '../chia-wasm.service';
import {
  BuildPropertyRegistryRegistrationArgs,
  BuildProposalEveLaunchArgs,
  BuildTrackerProposeArgs,
  MintPublishSpendBuilderService,
  SgtFirstVoteArgs,
} from './mint-publish-spend-builder.service';
import fixture from './mint-publish.fixtures.json';

/**
 * Cross-repo binding spec for {@link MintPublishSpendBuilderService}.
 *
 * Reads the three spend sections of ``mint-publish.fixtures.json``
 * (generated by ``solslot_protocol/scripts/dump_mint_publish_fixtures.py``)
 * and asserts byte-for-byte equality against the TS builders.  If either
 * side drifts, this spec fails along with the Python fixture currency
 * guard.
 */
describe('MintPublishSpendBuilderService', () => {
  let service: MintPublishSpendBuilderService;

  beforeAll(async () => {
    if ((window as unknown as { ChiaSDK?: unknown }).ChiaSDK) {
      return;
    }
    // @ts-ignore — deep-import; types come from chia_wallet_sdk_wasm.d.ts.
    const wasmExports = await import('chia-wallet-sdk-wasm/chia_wallet_sdk_wasm_bg.js');
    const response = await fetch('/assets/chia_wasm/chia_wallet_sdk_wasm_bg.wasm');
    if (!response.ok) {
      throw new Error(
        `WASM asset fetch failed: ${response.status} ${response.statusText}.`,
      );
    }
    const bytes = await response.arrayBuffer();
    const result = await WebAssembly.instantiate(bytes, {
      './chia_wallet_sdk_wasm_bg.js': wasmExports as unknown as WebAssembly.ModuleImports,
    });
    const setWasm = (wasmExports as unknown as { __wbg_set_wasm?: (w: WebAssembly.Exports) => void }).__wbg_set_wasm;
    if (typeof setWasm !== 'function') {
      throw new Error('chia_wallet_sdk_wasm_bg.js missing __wbg_set_wasm');
    }
    setWasm(result.instance.exports);
    (window as unknown as { ChiaSDK: unknown }).ChiaSDK = wasmExports;
  });

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [provideHttpClient(), provideHttpClientTesting()],
    });
    TestBed.inject(ChiaWasmService).probeReady();
    service = TestBed.inject(MintPublishSpendBuilderService);
  });

  // ────────────────────────────────────────────────────────────────────
  //  0. Property-registry announcement assertion
  // ────────────────────────────────────────────────────────────────────
  describe('property registry announcement assertion', () => {
    const args = {
      propertyRegistryPuzzleHash:
        '0x8989898989898989898989898989898989898989898989898989898989898989',
      propertyIdCanon:
        '0x2121212121212121212121212121212121212121212121212121212121212121',
    };

    it('announcement id matches the Python registry driver formula', () => {
      expect(service.propertyRegistryAnnouncementId(args)).toBe(
        '0xe29f5542a4117bbdd441f7af4db65f24618bbb6e55c26539c288bf3bfb5416ae',
      );
    });

    it('ASSERT_PUZZLE_ANNOUNCEMENT condition hex matches Python Program.to', () => {
      expect(service.buildPropertyRegistryAssertConditionHex(args)).toBe(
        '0xff3fffa0e29f5542a4117bbdd441f7af4db65f24618bbb6e55c26539c288bf3bfb5416ae80',
      );
    });

    it('rejects non-32-byte registry puzzle hashes', () => {
      expect(() =>
        service.propertyRegistryAnnouncementId({
          ...args,
          propertyRegistryPuzzleHash: '0x1234',
        }),
      ).toThrowError(/propertyRegistryPuzzleHash must be 32 bytes/);
    });

    it('rejects non-32-byte property ids', () => {
      expect(() =>
        service.propertyRegistryAnnouncementId({
          ...args,
          propertyIdCanon: '0x1234',
        }),
      ).toThrowError(/propertyIdCanon must be 32 bytes/);
    });
  });

  // ────────────────────────────────────────────────────────────────────
  //  1. Artifact A launcher → eve hop
  // ────────────────────────────────────────────────────────────────────
  describe('buildProposalEveLaunchSpend', () => {
    function eveArgs(): BuildProposalEveLaunchArgs {
      const inp = fixture.proposal_eve_launch.inputs;
      return {
        xchParentCoin: {
          parentCoinInfo: inp.xch_parent_coin.parentCoinInfo,
          puzzleHash: inp.xch_parent_coin.puzzleHash,
          amount: inp.xch_parent_coin.amount,
        },
        eveInnerPuzzleHex: inp.eve_inner_puzzle_hex,
        amount: inp.amount,
      };
    }

    it('parent_conditions match the Python fixture hex list byte-for-byte', () => {
      const result = service.buildProposalEveLaunchSpend(eveArgs());
      const expected = fixture.proposal_eve_launch.expected;
      expect(result.parentConditionsHex.length).toBe(
        expected.parent_conditions_hex.length,
      );
      for (let i = 0; i < expected.parent_conditions_hex.length; i++) {
        expect(result.parentConditionsHex[i]).toBe(
          expected.parent_conditions_hex[i],
        );
      }
    });

    it('launcher coin matches the Python fixture byte-for-byte', () => {
      const result = service.buildProposalEveLaunchSpend(eveArgs());
      const expected = fixture.proposal_eve_launch.expected;
      expect(result.launcherCoinSpend.coin.parentCoinInfo).toBe(
        expected.launcher_coin.parentCoinInfo,
      );
      expect(result.launcherCoinSpend.coin.puzzleHash).toBe(
        expected.launcher_coin.puzzleHash,
      );
      expect(Number(result.launcherCoinSpend.coin.amount)).toBe(
        expected.launcher_coin.amount,
      );
    });

    it('launcher puzzle reveal hex matches the Python fixture', () => {
      const result = service.buildProposalEveLaunchSpend(eveArgs());
      expect(result.launcherCoinSpend.puzzleReveal).toBe(
        fixture.proposal_eve_launch.expected.launcher_puzzle_reveal_hex,
      );
    });

    it('launcher solution hex matches the Python fixture', () => {
      const result = service.buildProposalEveLaunchSpend(eveArgs());
      expect(result.launcherCoinSpend.solution).toBe(
        fixture.proposal_eve_launch.expected.launcher_solution_hex,
      );
    });

    it('eve coin matches the Python fixture byte-for-byte', () => {
      const result = service.buildProposalEveLaunchSpend(eveArgs());
      const expected = fixture.proposal_eve_launch.expected;
      expect(result.eveCoin.parentCoinInfo).toBe(expected.eve_coin.parentCoinInfo);
      expect(result.eveCoin.puzzleHash).toBe(expected.eve_coin.puzzleHash);
      expect(Number(result.eveCoin.amount)).toBe(expected.eve_coin.amount);
    });

    it('eveFullPuzzleHash matches the Python fixture', () => {
      const result = service.buildProposalEveLaunchSpend(eveArgs());
      expect(result.eveFullPuzzleHash).toBe(
        fixture.proposal_eve_launch.expected.eve_full_puzzle_hash,
      );
    });

    it('rejects an even amount', () => {
      const args = eveArgs();
      args.amount = 2;
      expect(() => service.buildProposalEveLaunchSpend(args)).toThrowError(
        /odd/,
      );
    });
  });

  // ────────────────────────────────────────────────────────────────────
  //  2. Artifact B tracker.PROPOSE CoinSpend
  // ────────────────────────────────────────────────────────────────────
  describe('buildTrackerProposeCoinSpend', () => {
    function proposeArgs(): BuildTrackerProposeArgs {
      const inp = fixture.tracker_propose.inputs;
      return {
        trackerCoin: {
          parentCoinInfo: inp.tracker_coin.parentCoinInfo,
          puzzleHash: inp.tracker_coin.puzzleHash,
          amount: inp.tracker_coin.amount,
        },
        trackerInnerPuzzleHex: inp.tracker_inner_puzzle_hex,
        trackerLauncherId: inp.tracker_launcher_id,
        lineageProof: {
          parentName: inp.lineage_proof.parent_name ?? undefined,
          innerPuzzleHash:
            inp.lineage_proof.inner_puzzle_hash ?? undefined,
          amount:
            inp.lineage_proof.amount !== null
              ? inp.lineage_proof.amount
              : undefined,
        },
        proposalHash: inp.proposal_hash,
        billOperationHex: inp.bill_operation_hex,
        voterInnerPuzzleHash: inp.voter_inner_puzzle_hash,
        firstVoteAmount: inp.first_vote_amount,
        votingDeadline: inp.voting_deadline,
      };
    }

    it('coin matches the Python fixture byte-for-byte', () => {
      const result = service.buildTrackerProposeCoinSpend(proposeArgs());
      const expected = fixture.tracker_propose.expected;
      expect(result.coin.parentCoinInfo).toBe(expected.coin.parentCoinInfo);
      expect(result.coin.puzzleHash).toBe(expected.coin.puzzleHash);
      expect(Number(result.coin.amount)).toBe(expected.coin.amount);
    });

    it('puzzle reveal hex matches the Python fixture', () => {
      const result = service.buildTrackerProposeCoinSpend(proposeArgs());
      expect(result.puzzleReveal).toBe(
        fixture.tracker_propose.expected.puzzle_reveal_hex,
      );
    });

    it('solution hex matches the Python fixture', () => {
      const result = service.buildTrackerProposeCoinSpend(proposeArgs());
      expect(result.solution).toBe(
        fixture.tracker_propose.expected.solution_hex,
      );
    });

    it('rejects non-32-byte proposalHash', () => {
      const args = proposeArgs();
      args.proposalHash = '0x1234';
      expect(() => service.buildTrackerProposeCoinSpend(args)).toThrowError(
        /proposalHash must be 32 bytes/,
      );
    });

    it('rejects non-positive firstVoteAmount', () => {
      const args = proposeArgs();
      args.firstVoteAmount = 0;
      expect(() => service.buildTrackerProposeCoinSpend(args)).toThrowError(
        /firstVoteAmount must be > 0/,
      );
    });

    it('rejects mismatched coin puzzle hash', () => {
      const args = proposeArgs();
      args.trackerCoin.puzzleHash =
        '0x0000000000000000000000000000000000000000000000000000000000000000';
      expect(() => service.buildTrackerProposeCoinSpend(args)).toThrowError(
        /does not match coin's claimed puzzle hash/,
      );
    });
  });

  // ────────────────────────────────────────────────────────────────────
  //  3. Proposer's SGT first-vote lock CoinSpend
  // ────────────────────────────────────────────────────────────────────
  describe('buildSgtFirstVoteCoinSpend', () => {
    function firstVoteArgs(): SgtFirstVoteArgs {
      const inp = fixture.sgt_first_vote.inputs;
      const trackerLauncherId =
        fixture.tracker_propose.inputs.tracker_launcher_id;
      return {
        sgtCoin: {
          parentCoinInfo: inp.sgt_coin.parentCoinInfo,
          puzzleHash: inp.sgt_coin.puzzleHash,
          amount: inp.sgt_coin.amount,
        },
        voterInnerPuzzleHex: inp.voter_inner_puzzle_hex,
        voterInnerSolutionHex: inp.voter_inner_solution_hex,
        trackerLauncherId,
        sgtTailHash: inp.sgt_tail_hash,
        lineageProof: {
          parentName: inp.lineage_proof.parent_name ?? undefined,
          innerPuzzleHash:
            inp.lineage_proof.inner_puzzle_hash ?? undefined,
          amount:
            inp.lineage_proof.amount !== null
              ? inp.lineage_proof.amount
              : undefined,
        },
        proposalHash: inp.proposal_hash,
        votingDeadline: inp.voting_deadline,
      };
    }

    it('coin matches the Python fixture byte-for-byte', () => {
      const result = service.buildSgtFirstVoteCoinSpend(firstVoteArgs());
      const expected = fixture.sgt_first_vote.expected;
      expect(result.coin.parentCoinInfo).toBe(expected.coin.parentCoinInfo);
      expect(result.coin.puzzleHash).toBe(expected.coin.puzzleHash);
      expect(Number(result.coin.amount)).toBe(expected.coin.amount);
    });

    it('puzzle reveal hex matches the Python fixture', () => {
      const result = service.buildSgtFirstVoteCoinSpend(firstVoteArgs());
      expect(result.puzzleReveal).toBe(
        fixture.sgt_first_vote.expected.puzzle_reveal_hex,
      );
    });

    it('solution hex matches the Python fixture', () => {
      const result = service.buildSgtFirstVoteCoinSpend(firstVoteArgs());
      expect(result.solution).toBe(
        fixture.sgt_first_vote.expected.solution_hex,
      );
    });
  });

  // ────────────────────────────────────────────────────────────────────
  //  4. Property-registry registration co-spend
  // ────────────────────────────────────────────────────────────────────
  describe('buildPropertyRegistryRegistrationCoinSpend', () => {
    function registrationArgs(): BuildPropertyRegistryRegistrationArgs {
      const inp = fixture.property_registry_registration.inputs;
      return {
        registryCoin: {
          parentCoinInfo: inp.registry_coin.parentCoinInfo,
          puzzleHash: inp.registry_coin.puzzleHash,
          amount: inp.registry_coin.amount,
        },
        registryInnerPuzzleHex: inp.registry_inner_puzzle_hex,
        registryLauncherId: inp.registry_launcher_id,
        lineageProof: {
          parentName: inp.lineage_proof.parent_name ?? undefined,
          innerPuzzleHash:
            inp.lineage_proof.inner_puzzle_hash ?? undefined,
          amount:
            inp.lineage_proof.amount !== null
              ? inp.lineage_proof.amount
              : undefined,
        },
        propertyIdCanon: inp.property_id_canon,
        registeredIds: inp.registered_ids,
      };
    }

    it('coin matches the Python fixture byte-for-byte', () => {
      const result = service.buildPropertyRegistryRegistrationCoinSpend(
        registrationArgs(),
      );
      const expected = fixture.property_registry_registration.expected;
      expect(result.coin.parentCoinInfo).toBe(expected.coin.parentCoinInfo);
      expect(result.coin.puzzleHash).toBe(expected.coin.puzzleHash);
      expect(Number(result.coin.amount)).toBe(expected.coin.amount);
    });

    it('puzzle reveal hex matches the Python fixture', () => {
      const result = service.buildPropertyRegistryRegistrationCoinSpend(
        registrationArgs(),
      );
      expect(result.puzzleReveal).toBe(
        fixture.property_registry_registration.expected.puzzle_reveal_hex,
      );
    });

    it('solution hex matches the Python fixture', () => {
      const result = service.buildPropertyRegistryRegistrationCoinSpend(
        registrationArgs(),
      );
      expect(result.solution).toBe(
        fixture.property_registry_registration.expected.solution_hex,
      );
    });

    it('derived metadata matches the Python fixture', () => {
      const result = service.buildPropertyRegistryRegistrationCoinSpend(
        registrationArgs(),
      );
      const expected = fixture.property_registry_registration.expected;
      expect(result.announcementId).toBe(expected.announcement_id);
      expect(result.newInnerPuzzleHash).toBe(expected.new_inner_puzzle_hash);
      expect(result.newRegisteredIdsRoot).toBe(expected.new_registered_ids_root);
      expect(result.aggSigMeMessage).toBe(expected.agg_sig_me_message);
    });

    it('curries the registry inner puzzle hex from gov pubkey + registered ids', () => {
      const inp = fixture.property_registry_registration.inputs;
      expect(
        service.makePropertyRegistryInnerPuzzleHex({
          govPubkey: inp.gov_pubkey,
          registeredIds: inp.registered_ids,
        }),
      ).toBe(inp.registry_inner_puzzle_hex);
    });

    it('rejects duplicate property ids', () => {
      const args = registrationArgs();
      args.propertyIdCanon = args.registeredIds[0];
      expect(() =>
        service.buildPropertyRegistryRegistrationCoinSpend(args),
      ).toThrowError(/already registered/);
    });

    it('rejects mismatched registry coin puzzle hash', () => {
      const args = registrationArgs();
      args.registryCoin.puzzleHash = '0x' + '00'.repeat(32);
      expect(() =>
        service.buildPropertyRegistryRegistrationCoinSpend(args),
      ).toThrowError(/does not match coin's claimed puzzle hash/);
    });
  });
});
