import { Injectable, inject } from '@angular/core';

import { ChiaWasmService } from '../chia-wasm.service';
import { bytesToHex, coinId, hexToBytes } from '../../utils/chia-hash';

import { MintProposalV2Service } from './mint-proposal-v2.service';
import { MINT_OFFER_DELEGATE_PUZZLE_HEX } from './mint-offer-delegate.puzzle-hex';
import { MINT_OFFER_DELEGATE_V2_PUZZLE_HEX } from './mint-offer-delegate-v2.puzzle-hex';
import { PURCHASE_PAYMENT_PUZZLE_HEX } from './purchase-payment.puzzle-hex';
import { SINGLETON_LAUNCHER_WITH_DID_PUZZLE_HEX } from './singleton-launcher-with-did.puzzle-hex';
import { SMART_DEED_INNER_PUZZLE_HEX } from './smart-deed-inner.puzzle-hex';

/**
 * TS port of ``solslot_puzzles.mint_publish_driver.build_mint_publish_artifacts``.
 *
 * **Why this exists.**  The Phase 4 admin desk "Publish" action atomically
 * lands two on-chain singletons: a V2 mint-proposal singleton (Artifact A)
 * and a governance tracker PROPOSE spend (Artifact B), and pre-spawns the
 * DID-gated deed launcher coin so the deed's full puzzle hash is deterministic
 * at publish time.  This service mirrors the Python driver byte-for-byte so
 * the portal can pin all four ``computed.*_puzhash`` row values client-side
 * *before* the publish bundle is signed.  The values surface in the admin
 * desk UI as a pre-flight integrity check.
 *
 * **Cross-repo binding.**  ``mint_publish_driver.py`` is the source of truth.
 * The canonical fixture
 * ``mint-publish.fixtures.json``
 * is generated by
 * ``solslot_protocol/scripts/dump_mint_publish_fixtures.py`` and read by
 * this service's Karma spec to assert hex-byte equivalence on every value.
 * Drift surfaces as a Karma failure here OR as a fixture-currency failure
 * in ``solslot_protocol/tests/test_mint_publish_fixtures.py``.
 *
 * **What this service exposes:**
 *   * {@link buildMintPublishArtifacts} — top-level pure computation.
 *     Returns all four computed.*_puzhash values, both launcher coin ids,
 *     ``proposal_data_hash``, and the three auxiliary CLVM programs (as
 *     hex) downstream spend builders curry into solutions.
 *   * {@link deedLauncherPuzzleHash} — DID-curried launcher hash; the
 *     pre-spawn coin's puzzle hash.  Exposed standalone because the
 *     wallet-side coin-picker needs it before the publish bundle is
 *     assembled.
 *
 * **What's NOT here (deferred to a follow-up):**
 *   * The actual ``CoinSpend`` bundle assembly (parent → launcher → eve
 *     for Artifact A, tracker.PROPOSE for Artifact B, SGT lock for the
 *     proposer).  This service only pins the hashes; the spend builder
 *     (``MintPublishSpendBuilderService``) lands separately and threads
 *     these values into wallet-signable spends.
 */
@Injectable({ providedIn: 'root' })
export class MintPublishService {
  private readonly wasm = inject(ChiaWasmService);
  private readonly v2 = inject(MintProposalV2Service);

  /**
   * Bill operation tag for a MINT proposal on the governance tracker.
   * Matches ``governance_singleton_inner.clsp``'s ``BILL_MINT``
   * defconstant (``'M' = 0x4d``).  Curried into the tracker.PROPOSE
   * bill_op tuple.
   */
  static readonly BILL_MINT_TAG = 0x4d;

  /**
   * Singleton coin amount (mojos).  All Solslot singletons are
   * odd-amount singletons per chia singleton_top_layer_v1_1.
   */
  static readonly SINGLETON_AMOUNT = 1;

  /**
   * Tree hash of the uncurried ``singleton_top_layer_v1_1.clsp``.
   * Used as the first element of every singleton struct.  Pinned to
   * the chia bundled value so a TS port that swaps singleton sources
   * fails the currency guard.
   */
  static readonly SINGLETON_MOD_HASH =
    '0x7faa3253bfddd1e0decb0906b2dc6247bbc4cf608f58345d173adb63e8b47c9f';

  /**
   * Tree hash of ``singleton_launcher.clsp`` (the standard chia
   * launcher).  Used as the second element of Artifact A's singleton
   * struct (no DID gating needed — Artifact A's launch is atomic
   * within the publish bundle so there is no idle-launcher griefing
   * surface).
   */
  static readonly SINGLETON_LAUNCHER_HASH =
    '0xeff07522495060c066f66f32acc2a77e3a3e737aca8baea4d1a64ea4cdc13da9';

  static readonly CAT_MOD_HASH =
    '0x37bef360ee858133b69d595a906dc45d01af50379dad515eb9518abb7c1d2a7a';
  static readonly OFFER_MOD_HASH =
    '0xcfbfdeed5c4ca2de3d0bf520b9cb4bb7743a359bd2e6a188d19ce7dffc21d3e7';
  static readonly PRIMARY_PURCHASE_PROVIDER_ID =
    '0x15807082c20217563e0ae963a629d073d512e19d56a935b129df947525278963';

  /**
   * Compute the DID-curried deed-launcher puzzle hash.
   *
   * The deed launcher uses ``singleton_launcher_with_did.clsp``
   * **curried with** the protocol DID singleton struct.  This binds
   * the launcher's authorising-announcement check to the protocol
   * DID singleton lineage at puzzle-hash time, which is what makes
   * pre-spawning the deed launcher coin griefing-safe (an attacker
   * who creates an unauthorised coin at this puzzle hash still
   * cannot launch the deed because the curried struct constrains the
   * authorising puzzle).
   *
   * @param protocolDidSingletonStructHex 0x-hex serialization of
   *   the protocol DID singleton struct Program (already wrapped as
   *   ``(SINGLETON_MOD_HASH, (DID_LAUNCHER_ID, SINGLETON_LAUNCHER_HASH))``).
   */
  deedLauncherPuzzleHash(protocolDidSingletonStructHex: string): Uint8Array {
    const clvm = this.clvm();
    const launcherMod = clvm.deserialize(hexToBytes(SINGLETON_LAUNCHER_WITH_DID_PUZZLE_HEX));
    const didStruct = clvm.deserialize(hexToBytes(protocolDidSingletonStructHex));
    return launcherMod.curry([didStruct]).treeHash();
  }

  /** Build the governance MINT bill, including optional metadata commitments. */
  buildMintBillCommitment(args: {
    deedFullPuzhash: string;
    propertyIdCanon: string;
    propertyRegistryPuzzleHash: string;
    metadataRoot?: string;
    metadataAnchorId?: string;
  }): { programHex: string; programHash: string } {
    const program = this.buildMintBillProgram(args);
    return {
      programHex: bytesToHex(program.serialize()),
      programHash: bytesToHex(program.treeHash()),
    };
  }

  /**
   * Top-level builder: pin every artifact the publish bundle binds to.
   *
   * Pure function: same inputs always produce the same outputs.  The
   * portal calls this client-side before submitting the publish
   * bundle; the API re-runs the Python equivalent server-side and
   * rejects bundles whose hash claims drift.
   *
   * Argument shapes mirror the Python ``build_mint_publish_artifacts``
   * keyword-only signature; see the Python docstring for full
   * semantics.  All ``*Hex`` fields are 0x-prefixed; 32-byte fields
   * MUST be exactly 32 bytes after hex-decoding (validated by the
   * underlying ``hexToBytes`` helper + chia-hash bounds checks).
   */
  buildMintPublishArtifacts(args: {
    // Operator metadata.
    propertyIdCanon: string;
    collectionIdCanon: string;
    sharePpm: number | bigint;
    parValueMojos: number | bigint;
    assetClass: number | bigint;
    /** Variable-length raw bytes (e.g. country/region code).  0x-hex. */
    jurisdictionHex: string;
    royaltyPuzhash: string;
    royaltyBps: number | bigint;
    quorumThreshold: number | bigint;
    // Member auth (Eip712Member of admin EVM addr / env gov member).
    ownerMemberHash: string;
    govMemberHash: string;
    // Parent coin ids the wallet picked for the two launcher spends.
    deedLauncherParentCoinName: string;
    proposalLauncherParentCoinName: string;
    // Protocol deployment-derived context.
    /** Serialized Program: ``(SINGLETON_MOD_HASH, (DID_LAUNCHER_ID, SINGLETON_LAUNCHER_HASH))``. */
    protocolDidSingletonStructHex: string;
    protocolDidPuzhash: string;
    protocolDidInnerPuzhash: string;
    governanceSingletonStructHex: string;
    poolSingletonLauncherId: string;
    poolSingletonLauncherPuzzleHash: string;
    p2PoolModHash: string;
    p2VaultModHash: string;
    propertyRegistryPuzzleHash: string;
    /** SHA-256 of canonical PropertyDossierV1. Enables the extended MINT bill. */
    metadataRoot?: string;
    /** First deed launcher id. Omit on the first proposal to bind to this launcher. */
    metadataAnchorId?: string;
    /** Enables the H-system-priced, vault-bound primary purchase path. */
    primaryPurchaseUsdAmountMinor?: number | bigint;
    primaryPurchaseValidatorPubkeys?: string[];
    primaryPurchaseNetwork?: string;
    primaryPurchaseProtocolTreasuryPuzhash?: string;
  }): MintPublishArtifacts {
    const clvm = this.clvm();

    // ── Step 1: Pre-spawned launcher coins → ids ──
    const deedLauncherPuzhash = this.deedLauncherPuzzleHash(args.protocolDidSingletonStructHex);
    const deedLauncherId = coinId(
      args.deedLauncherParentCoinName,
      deedLauncherPuzhash,
      MintPublishService.SINGLETON_AMOUNT,
    );
    const proposalSingletonLauncherId = coinId(
      args.proposalLauncherParentCoinName,
      MintPublishService.SINGLETON_LAUNCHER_HASH,
      MintPublishService.SINGLETON_AMOUNT,
    );

    // ── Step 2: deed singleton struct + smart_deed_inner ──
    // Struct = (SINGLETON_MOD_HASH, (deedLauncherId, deedLauncherPuzhash))
    const deedStructProgram = clvm.pair(
      clvm.atom(hexToBytes(MintPublishService.SINGLETON_MOD_HASH)),
      clvm.pair(clvm.atom(hexToBytes(deedLauncherId)), clvm.atom(deedLauncherPuzhash)),
    );

    const smartDeedMod = clvm.deserialize(hexToBytes(SMART_DEED_INNER_PUZZLE_HEX));
    // Currying order MUST match smart_deed_inner.clsp + Python driver.
    const smartDeedInner = smartDeedMod.curry([
      deedStructProgram,
      clvm.atom(hexToBytes(args.protocolDidPuzhash)),
      clvm.int(BigInt(args.parValueMojos)),
      clvm.int(BigInt(args.assetClass)),
      clvm.atom(hexToBytes(args.propertyIdCanon)),
      clvm.atom(hexToBytes(args.collectionIdCanon)),
      clvm.int(BigInt(args.sharePpm)),
      clvm.atom(hexToBytes(args.jurisdictionHex)),
      clvm.atom(hexToBytes(args.royaltyPuzhash)),
      clvm.int(BigInt(args.royaltyBps)),
      clvm.atom(hexToBytes(MintPublishService.SINGLETON_MOD_HASH)),
      clvm.atom(hexToBytes(args.poolSingletonLauncherId)),
      clvm.atom(hexToBytes(args.poolSingletonLauncherPuzzleHash)),
      clvm.atom(hexToBytes(args.p2PoolModHash)),
      clvm.atom(hexToBytes(args.p2VaultModHash)),
    ]);
    const smartDeedInnerPuzhash = smartDeedInner.treeHash();

    if (!args.metadataRoot && args.metadataAnchorId) {
      throw new Error('metadataAnchorId cannot be supplied without metadataRoot');
    }
    const resolvedMetadataAnchorId = args.metadataRoot
      ? args.metadataAnchorId ?? deedLauncherId
      : undefined;

    // ── Step 3: mint-offer eve inner + deed_full_puzhash ──
    const purchasePaymentMod = clvm.deserialize(hexToBytes(PURCHASE_PAYMENT_PUZZLE_HEX));
    const purchasePaymentModHash = purchasePaymentMod.treeHash();
    let eveMintOfferInner: ClvmProgramShape;
    if (args.primaryPurchaseUsdAmountMinor === undefined) {
      const mintOfferMod = clvm.deserialize(hexToBytes(MINT_OFFER_DELEGATE_PUZZLE_HEX));
      eveMintOfferInner = mintOfferMod.curry([
        clvm.atom(smartDeedInnerPuzhash),
        clvm.atom(purchasePaymentModHash),
        clvm.int(BigInt(args.parValueMojos)),
        clvm.atom(hexToBytes(args.protocolDidPuzhash)),
      ]);
    } else {
      if (!args.metadataRoot || !resolvedMetadataAnchorId) {
        throw new Error('Primary purchase mints require metadataRoot and metadataAnchorId');
      }
      const usdAmountMinor = BigInt(args.primaryPurchaseUsdAmountMinor);
      if (usdAmountMinor <= 0n || usdAmountMinor > 0xffff_ffff_ffff_ffffn) {
        throw new Error('primaryPurchaseUsdAmountMinor must be a positive uint64');
      }
      const networkBytes = new TextEncoder().encode(args.primaryPurchaseNetwork ?? '');
      if (networkBytes.length === 0 || networkBytes.length > 32) {
        throw new Error('primaryPurchaseNetwork must be 1-32 UTF-8 bytes');
      }
      const validatorPubkeys = args.primaryPurchaseValidatorPubkeys ?? [];
      if (
        validatorPubkeys.length !== 3 ||
        new Set(validatorPubkeys.map((value) => value.toLowerCase())).size !== 3
      ) {
        throw new Error('Primary purchase mints require three unique validator public keys');
      }
      const validatorAtoms = validatorPubkeys.map((value) => {
        const pubkey = hexToBytes(value);
        if (pubkey.length !== 48) {
          throw new Error('Each primary purchase validator public key must be 48 bytes');
        }
        return clvm.atom(pubkey);
      });
      const mintOfferV2Mod = clvm.deserialize(hexToBytes(MINT_OFFER_DELEGATE_V2_PUZZLE_HEX));
      const treasuryPuzhash = hexToBytes(args.primaryPurchaseProtocolTreasuryPuzhash ?? '');
      if (treasuryPuzhash.length !== 32) {
        throw new Error('Primary purchase mints require the signed protocol treasury puzzle hash');
      }
      eveMintOfferInner = mintOfferV2Mod.curry([
        clvm.atom(smartDeedInnerPuzhash),
        clvm.atom(hexToBytes(args.p2VaultModHash)),
        clvm.atom(hexToBytes(MintPublishService.SINGLETON_MOD_HASH)),
        clvm.atom(hexToBytes(MintPublishService.SINGLETON_LAUNCHER_HASH)),
        clvm.atom(hexToBytes(MintPublishService.CAT_MOD_HASH)),
        clvm.atom(hexToBytes(MintPublishService.OFFER_MOD_HASH)),
        clvm.atom(networkBytes),
        clvm.atom(hexToBytes(deedLauncherId)),
        clvm.atom(hexToBytes(args.collectionIdCanon)),
        clvm.atom(hexToBytes(args.metadataRoot)),
        clvm.atom(hexToBytes(resolvedMetadataAnchorId)),
        clvm.int(BigInt(args.sharePpm)),
        clvm.int(usdAmountMinor),
        clvm.atom(treasuryPuzhash),
        clvm.list(validatorAtoms),
        clvm.atom(hexToBytes(MintPublishService.PRIMARY_PURCHASE_PROVIDER_ID)),
      ]);
    }

    // Deed full puzzle hash = singleton_top_layer.curry(struct, eve_inner).treeHash()
    const topLayerBytes = this.singletonTopLayerBytes();
    const deedFullPuzzle = clvm
      .deserialize(topLayerBytes)
      .curry([deedStructProgram, eveMintOfferInner]);
    const deedFullPuzhash = deedFullPuzzle.treeHash();

    // ── Step 4: governance tracker proposal_hash + bill_op program ──
    // Extended bill appends metadata commitments. RC16 dispatch reads only
    // the unchanged leading fields while sha256tree commits to the full list.
    const billOpProgram = this.buildMintBillProgram({
      deedFullPuzhash: bytesToHex(deedFullPuzhash),
      propertyIdCanon: args.propertyIdCanon,
      propertyRegistryPuzzleHash: args.propertyRegistryPuzzleHash,
      metadataRoot: args.metadataRoot,
      metadataAnchorId: resolvedMetadataAnchorId,
    });
    const proposalHash = billOpProgram.treeHash();

    // ── Step 5: Artifact A DRAFT eve inner + proposal_data_hash ──
    const proposalDataHash = this.v2.computeProposalDataHash({
      propertyIdCanon: args.propertyIdCanon,
      collectionIdCanon: args.collectionIdCanon,
      sharePpm: args.sharePpm,
      parValueMojos: args.parValueMojos,
      royaltyBps: args.royaltyBps,
      quorumThreshold: args.quorumThreshold,
      metadataRoot: args.metadataRoot,
      metadataAnchorId: resolvedMetadataAnchorId,
    });
    const eveInnerPuzhash = this.v2.makeInnerPuzzleHash({
      ownerMemberHash: args.ownerMemberHash,
      govMemberHash: args.govMemberHash,
      proposalDataHash: bytesToHex(proposalDataHash),
      governanceSingletonStructHex: args.governanceSingletonStructHex,
      governanceProposalHash: bytesToHex(proposalHash),
      deedLauncherId,
      didInnerPuzzleHash: args.protocolDidInnerPuzhash,
      deedFullPuzzleHash: bytesToHex(deedFullPuzhash),
      proposalState: MintProposalV2Service.STATE_DRAFT,
      stateVersion: 0,
    });

    // ── Step 6: Artifact A standard singleton struct (for downstream eve wrap) ──
    const proposalStructProgram = clvm.pair(
      clvm.atom(hexToBytes(MintPublishService.SINGLETON_MOD_HASH)),
      clvm.pair(
        clvm.atom(hexToBytes(proposalSingletonLauncherId)),
        clvm.atom(hexToBytes(MintPublishService.SINGLETON_LAUNCHER_HASH)),
      ),
    );

    return {
      // computed.*_puzhash row
      smartDeedInnerPuzhash: bytesToHex(smartDeedInnerPuzhash),
      eveInnerPuzhash: bytesToHex(eveInnerPuzhash),
      deedFullPuzhash: bytesToHex(deedFullPuzhash),
      proposalHash: bytesToHex(proposalHash),
      // Launcher coin identities
      deedLauncherId,
      proposalSingletonLauncherId,
      // Artifact A binding hash (audit log)
      proposalDataHash: bytesToHex(proposalDataHash),
      metadataRoot: args.metadataRoot,
      metadataAnchorId: resolvedMetadataAnchorId,
      // Auxiliary programs (hex + tree hash)
      billOpProgramHex: bytesToHex(billOpProgram.serialize()),
      billOpProgramHash: bytesToHex(billOpProgram.treeHash()),
      deedSingletonStructProgramHex: bytesToHex(deedStructProgram.serialize()),
      deedSingletonStructProgramHash: bytesToHex(deedStructProgram.treeHash()),
      proposalSingletonStructProgramHex: bytesToHex(proposalStructProgram.serialize()),
      proposalSingletonStructProgramHash: bytesToHex(proposalStructProgram.treeHash()),
    };
  }

  // ── Internals ────────────────────────────────────────────────────────────

  /**
   * Resolve the singleton top-layer v1.1 bytecode from the WASM SDK.
   * Mirrors the resolution order in {@link VaultLaunchSpendService} so
   * upgrades to the SDK that rename the constant accessor surface here
   * once and not in every consumer.
   */
  private singletonTopLayerBytes(): Uint8Array {
    const constants = this.sdk().Constants;
    const bytes = constants?.singletonTopLayerV11?.() ?? constants?.singletonTopLayer?.();
    if (!bytes) {
      throw new Error('MintPublishService: singleton top-layer bytecode unavailable in WASM SDK');
    }
    return bytes;
  }

  private buildMintBillProgram(args: {
    deedFullPuzhash: string;
    propertyIdCanon: string;
    propertyRegistryPuzzleHash: string;
    metadataRoot?: string;
    metadataAnchorId?: string;
  }): ClvmProgramShape {
    if (!!args.metadataRoot !== !!args.metadataAnchorId) {
      throw new Error('metadataRoot and metadataAnchorId must be supplied together');
    }
    const clvm = this.clvm();
    const billFields = [
      clvm.int(BigInt(MintPublishService.BILL_MINT_TAG)),
      clvm.atom(hexToBytes(args.deedFullPuzhash)),
      clvm.atom(hexToBytes(args.propertyIdCanon)),
      clvm.atom(hexToBytes(args.propertyRegistryPuzzleHash)),
    ];
    if (args.metadataRoot && args.metadataAnchorId) {
      const metadataRoot = hexToBytes(args.metadataRoot);
      const metadataAnchorId = hexToBytes(args.metadataAnchorId);
      if (metadataRoot.length !== 32 || metadataAnchorId.length !== 32) {
        throw new Error('metadataRoot and metadataAnchorId must each be 32 bytes');
      }
      billFields.push(clvm.atom(metadataRoot), clvm.atom(metadataAnchorId));
    }
    return clvm.list(billFields);
  }

  private clvm(): ClvmShape {
    return new (this.sdk().Clvm)();
  }

  private sdk(): SdkShape {
    const sdk = this.wasm.sdk() as SdkShape | undefined;
    if (!sdk || !sdk.Clvm) {
      throw new Error(
        'MintPublishService: chia-wallet-sdk-wasm not loaded yet. ' +
          'Await ChiaWasmService.ready() before calling hash helpers.',
      );
    }
    return sdk;
  }
}

// ── Return type ────────────────────────────────────────────────────────────

/**
 * Result of {@link MintPublishService.buildMintPublishArtifacts}.
 *
 * Field grouping mirrors the Python ``MintPublishArtifacts`` dataclass:
 *
 *   1. ``computed.*_puzhash`` row that the admin desk surfaces.
 *   2. Launcher-coin identities the downstream spend builder needs to
 *      reference the just-spawned launchers.
 *   3. ``proposalDataHash`` — Artifact A's audit-log binding.
 *   4. Auxiliary CLVM programs (serialized hex + tree hash) curried
 *      into solutions by the spend builder.
 *
 * All hex values are 0x-prefixed.  32-byte hash fields are exactly
 * 64 hex chars; program-serialization fields are variable-length.
 */
export interface MintPublishArtifacts {
  // computed.*_puzhash row
  smartDeedInnerPuzhash: string;
  eveInnerPuzhash: string;
  deedFullPuzhash: string;
  proposalHash: string;
  // Launcher coin identities
  deedLauncherId: string;
  proposalSingletonLauncherId: string;
  // Artifact A binding hash (audit log)
  proposalDataHash: string;
  metadataRoot?: string;
  metadataAnchorId?: string;
  // Auxiliary CLVM programs
  billOpProgramHex: string;
  billOpProgramHash: string;
  deedSingletonStructProgramHex: string;
  deedSingletonStructProgramHash: string;
  proposalSingletonStructProgramHex: string;
  proposalSingletonStructProgramHash: string;
}

// ── WASM SDK shape (narrowed) ─────────────────────────────────────────────

interface ClvmShape {
  atom(bytes: Uint8Array): ClvmProgramShape;
  int(value: bigint): ClvmProgramShape;
  list(items: ReadonlyArray<ClvmProgramShape>): ClvmProgramShape;
  pair(first: ClvmProgramShape, rest: ClvmProgramShape): ClvmProgramShape;
  deserialize(bytes: Uint8Array): ClvmProgramShape;
}

interface ClvmProgramShape {
  treeHash(): Uint8Array;
  curry(args: ReadonlyArray<ClvmProgramShape>): ClvmProgramShape;
  serialize(): Uint8Array;
}

interface SdkShape {
  Clvm: new () => ClvmShape;
  Constants?: {
    singletonTopLayer?: () => Uint8Array;
    singletonTopLayerV11?: () => Uint8Array;
  };
}
