import { Injectable, inject } from '@angular/core';

import { ChiaWasmService } from '../chia-wasm.service';
import { bytesToHex, coinId, hexToBytes } from '../../utils/chia-hash';

import { MintProposalV2Service } from './mint-proposal-v2.service';
import { MINT_OFFER_DELEGATE_PUZZLE_HEX } from './mint-offer-delegate.puzzle-hex';
import { PURCHASE_PAYMENT_PUZZLE_HEX } from './purchase-payment.puzzle-hex';
import { SINGLETON_LAUNCHER_WITH_DID_PUZZLE_HEX } from './singleton-launcher-with-did.puzzle-hex';
import { SMART_DEED_INNER_PUZZLE_HEX } from './smart-deed-inner.puzzle-hex';

/**
 * TS port of ``solslot_puzzles.mint_publish_driver.build_mint_publish_artifacts``.
 *
 * **Why this exists.**  The Phase 4 admin desk "Publish" action atomically
 * lands two on-chain singletons: a V2 mint-proposal singleton (Artifact A)
 * and a governance tracker PROPOSE spend (Artifact B), and pre-spawns the
 * DID-gated deed launcher coin so the deed's full puzzle hash is deterministic
 * at publish time.  This service mirrors the Python driver byte-for-byte so
 * the portal can pin all four ``computed.*_puzhash`` row values client-side
 * *before* the publish bundle is signed.  The values surface in the admin
 * desk UI as a pre-flight integrity check.
 *
 * **Cross-repo binding.**  ``mint_publish_driver.py`` is the source of truth.
 * The canonical fixture
 * ``mint-publish.fixtures.json``
 * is generated by
 * ``solslot_protocol/scripts/dump_mint_publish_fixtures.py`` and read by
 * this service's Karma spec to assert hex-byte equivalence on every value.
 * Drift surfaces as a Karma failure here OR as a fixture-currency failure
 * in ``solslot_protocol/tests/test_mint_publish_fixtures.py``.
 *
 * **What this service exposes:**
 *   * {@link buildMintPublishArtifacts} — top-level pure computation.
 *     Returns all four computed.*_puzhash values, both launcher coin ids,
 *     ``proposal_data_hash``, and the three auxiliary CLVM programs (as
 *     hex) downstream spend builders curry into solutions.
 *   * {@link deedLauncherPuzzleHash} — DID-curried launcher hash; the
 *     pre-spawn coin's puzzle hash.  Exposed standalone because the
 *     wallet-side coin-picker needs it before the publish bundle is
 *     assembled.
 *
 * **What's NOT here (deferred to a follow-up):**
 *   * The actual ``CoinSpend`` bundle assembly (parent → launcher → eve
 *     for Artifact A, tracker.PROPOSE for Artifact B, SGT lock for the
 *     proposer).  This service only pins the hashes; the spend builder
 *     (``MintPublishSpendBuilderService``) lands separately and threads
 *     these values into wallet-signable spends.
 */
@Injectable({ providedIn: 'root' })
export class MintPublishService {
  private readonly wasm = inject(ChiaWasmService);
  private readonly v2 = inject(MintProposalV2Service);

  /**
   * Bill operation tag for a MINT proposal on the governance tracker.
   * Matches ``governance_singleton_inner.clsp``'s ``BILL_MINT``
   * defconstant (``'M' = 0x4d``).  Curried into the tracker.PROPOSE
   * bill_op tuple.
   */
  static readonly BILL_MINT_TAG = 0x4d;

  /**
   * Singleton coin amount (mojos).  All Solslot singletons are
   * odd-amount singletons per chia singleton_top_layer_v1_1.
   */
  static readonly SINGLETON_AMOUNT = 1;

  /**
   * Tree hash of the uncurried ``singleton_top_layer_v1_1.clsp``.
   * Used as the first element of every singleton struct.  Pinned to
   * the chia bundled value so a TS port that swaps singleton sources
   * fails the currency guard.
   */
  static readonly SINGLETON_MOD_HASH =
    '0x7faa3253bfddd1e0decb0906b2dc6247bbc4cf608f58345d173adb63e8b47c9f';

  /**
   * Tree hash of ``singleton_launcher.clsp`` (the standard chia
   * launcher).  Used as the second element of Artifact A's singleton
   * struct (no DID gating needed — Artifact A's launch is atomic
   * within the publish bundle so there is no idle-launcher griefing
   * surface).
   */
  static readonly SINGLETON_LAUNCHER_HASH =
    '0xeff07522495060c066f66f32acc2a77e3a3e737aca8baea4d1a64ea4cdc13da9';

  /**
   * Compute the DID-curried deed-launcher puzzle hash.
   *
   * The deed launcher uses ``singleton_launcher_with_did.clsp``
   * **curried with** the protocol DID singleton struct.  This binds
   * the launcher's authorising-announcement check to the protocol
   * DID singleton lineage at puzzle-hash time, which is what makes
   * pre-spawning the deed launcher coin griefing-safe (an attacker
   * who creates an unauthorised coin at this puzzle hash still
   * cannot launch the deed because the curried struct constrains the
   * authorising puzzle).
   *
   * @param protocolDidSingletonStructHex 0x-hex serialization of
   *   the protocol DID singleton struct Program (already wrapped as
   *   ``(SINGLETON_MOD_HASH, (DID_LAUNCHER_ID, SINGLETON_LAUNCHER_HASH))``).
   */
  deedLauncherPuzzleHash(protocolDidSingletonStructHex: string): Uint8Array {
    const clvm = this.clvm();
    const launcherMod = clvm.deserialize(
      hexToBytes(SINGLETON_LAUNCHER_WITH_DID_PUZZLE_HEX),
    );
    const didStruct = clvm.deserialize(
      hexToBytes(protocolDidSingletonStructHex),
    );
    return launcherMod.curry([didStruct]).treeHash();
  }

  /**
   * Top-level builder: pin every artifact the publish bundle binds to.
   *
   * Pure function: same inputs always produce the same outputs.  The
   * portal calls this client-side before submitting the publish
   * bundle; the API re-runs the Python equivalent server-side and
   * rejects bundles whose hash claims drift.
   *
   * Argument shapes mirror the Python ``build_mint_publish_artifacts``
   * keyword-only signature; see the Python docstring for full
   * semantics.  All ``*Hex`` fields are 0x-prefixed; 32-byte fields
   * MUST be exactly 32 bytes after hex-decoding (validated by the
   * underlying ``hexToBytes`` helper + chia-hash bounds checks).
   */
  buildMintPublishArtifacts(args: {
    // Operator metadata.
    propertyIdCanon: string;
    collectionIdCanon: string;
    sharePpm: number | bigint;
    parValueMojos: number | bigint;
    assetClass: number | bigint;
    /** Variable-length raw bytes (e.g. country/region code).  0x-hex. */
    jurisdictionHex: string;
    royaltyPuzhash: string;
    royaltyBps: number | bigint;
    quorumThreshold: number | bigint;
    // Member auth (Eip712Member of admin EVM addr / env gov member).
    ownerMemberHash: string;
    govMemberHash: string;
    // Parent coin ids the wallet picked for the two launcher spends.
    deedLauncherParentCoinName: string;
    proposalLauncherParentCoinName: string;
    // Protocol deployment-derived context.
    /** Serialized Program: ``(SINGLETON_MOD_HASH, (DID_LAUNCHER_ID, SINGLETON_LAUNCHER_HASH))``. */
    protocolDidSingletonStructHex: string;
    protocolDidPuzhash: string;
    p2PoolModHash: string;
    p2VaultModHash: string;
    propertyRegistryPuzzleHash: string;
  }): MintPublishArtifacts {
    const clvm = this.clvm();

    // ── Step 1: Pre-spawned launcher coins → ids ──
    const deedLauncherPuzhash = this.deedLauncherPuzzleHash(
      args.protocolDidSingletonStructHex,
    );
    const deedLauncherId = coinId(
      args.deedLauncherParentCoinName,
      deedLauncherPuzhash,
      MintPublishService.SINGLETON_AMOUNT,
    );
    const proposalSingletonLauncherId = coinId(
      args.proposalLauncherParentCoinName,
      MintPublishService.SINGLETON_LAUNCHER_HASH,
      MintPublishService.SINGLETON_AMOUNT,
    );

    // ── Step 2: deed singleton struct + smart_deed_inner ──
    // Struct = (SINGLETON_MOD_HASH, (deedLauncherId, deedLauncherPuzhash))
    const deedStructProgram = clvm.pair(
      clvm.atom(hexToBytes(MintPublishService.SINGLETON_MOD_HASH)),
      clvm.pair(
        clvm.atom(hexToBytes(deedLauncherId)),
        clvm.atom(deedLauncherPuzhash),
      ),
    );

    const smartDeedMod = clvm.deserialize(hexToBytes(SMART_DEED_INNER_PUZZLE_HEX));
    // Currying order MUST match smart_deed_inner.clsp + Python driver.
    const smartDeedInner = smartDeedMod.curry([
      deedStructProgram,
      clvm.atom(hexToBytes(args.protocolDidPuzhash)),
      clvm.int(BigInt(args.parValueMojos)),
      clvm.int(BigInt(args.assetClass)),
      clvm.atom(hexToBytes(args.propertyIdCanon)),
      clvm.atom(hexToBytes(args.collectionIdCanon)),
      clvm.int(BigInt(args.sharePpm)),
      clvm.atom(hexToBytes(args.jurisdictionHex)),
      clvm.atom(hexToBytes(args.royaltyPuzhash)),
      clvm.int(BigInt(args.royaltyBps)),
      clvm.atom(hexToBytes(MintPublishService.SINGLETON_MOD_HASH)),
      clvm.atom(hexToBytes(args.p2PoolModHash)),
      clvm.atom(hexToBytes(args.p2VaultModHash)),
    ]);
    const smartDeedInnerPuzhash = smartDeedInner.treeHash();

    // ── Step 3: mint-offer eve inner + deed_full_puzhash ──
    const purchasePaymentMod = clvm.deserialize(
      hexToBytes(PURCHASE_PAYMENT_PUZZLE_HEX),
    );
    const purchasePaymentModHash = purchasePaymentMod.treeHash();

    const mintOfferMod = clvm.deserialize(
      hexToBytes(MINT_OFFER_DELEGATE_PUZZLE_HEX),
    );
    const eveMintOfferInner = mintOfferMod.curry([
      clvm.atom(smartDeedInnerPuzhash),
      clvm.atom(purchasePaymentModHash),
      clvm.int(BigInt(args.parValueMojos)),
      clvm.atom(hexToBytes(args.protocolDidPuzhash)),
    ]);

    // Deed full puzzle hash = singleton_top_layer.curry(struct, eve_inner).treeHash()
    const topLayerBytes = this.singletonTopLayerBytes();
    const deedFullPuzzle = clvm
      .deserialize(topLayerBytes)
      .curry([deedStructProgram, eveMintOfferInner]);
    const deedFullPuzhash = deedFullPuzzle.treeHash();

    // ── Step 4: governance tracker proposal_hash + bill_op program ──
    // bill_op = (BILL_MINT, deed_full_puzhash, property_id_canon, property_registry_puzzle_hash)
    const billOpProgram = clvm.list([
      clvm.int(BigInt(MintPublishService.BILL_MINT_TAG)),
      clvm.atom(deedFullPuzhash),
      clvm.atom(hexToBytes(args.propertyIdCanon)),
      clvm.atom(hexToBytes(args.propertyRegistryPuzzleHash)),
    ]);
    const proposalHash = billOpProgram.treeHash();

    // ── Step 5: Artifact A DRAFT eve inner + proposal_data_hash ──
    const proposalDataHash = this.v2.computeProposalDataHash({
      propertyIdCanon: args.propertyIdCanon,
      collectionIdCanon: args.collectionIdCanon,
      sharePpm: args.sharePpm,
      parValueMojos: args.parValueMojos,
      royaltyBps: args.royaltyBps,
      quorumThreshold: args.quorumThreshold,
    });
    const eveInnerPuzhash = this.v2.makeInnerPuzzleHash({
      ownerMemberHash: args.ownerMemberHash,
      govMemberHash: args.govMemberHash,
      proposalDataHash: bytesToHex(proposalDataHash),
      proposalState: MintProposalV2Service.STATE_DRAFT,
      stateVersion: 0,
    });

    // ── Step 6: Artifact A standard singleton struct (for downstream eve wrap) ──
    const proposalStructProgram = clvm.pair(
      clvm.atom(hexToBytes(MintPublishService.SINGLETON_MOD_HASH)),
      clvm.pair(
        clvm.atom(hexToBytes(proposalSingletonLauncherId)),
        clvm.atom(hexToBytes(MintPublishService.SINGLETON_LAUNCHER_HASH)),
      ),
    );

    return {
      // computed.*_puzhash row
      smartDeedInnerPuzhash: bytesToHex(smartDeedInnerPuzhash),
      eveInnerPuzhash: bytesToHex(eveInnerPuzhash),
      deedFullPuzhash: bytesToHex(deedFullPuzhash),
      proposalHash: bytesToHex(proposalHash),
      // Launcher coin identities
      deedLauncherId,
      proposalSingletonLauncherId,
      // Artifact A binding hash (audit log)
      proposalDataHash: bytesToHex(proposalDataHash),
      // Auxiliary programs (hex + tree hash)
      billOpProgramHex: bytesToHex(billOpProgram.serialize()),
      billOpProgramHash: bytesToHex(billOpProgram.treeHash()),
      deedSingletonStructProgramHex: bytesToHex(deedStructProgram.serialize()),
      deedSingletonStructProgramHash: bytesToHex(
        deedStructProgram.treeHash(),
      ),
      proposalSingletonStructProgramHex: bytesToHex(
        proposalStructProgram.serialize(),
      ),
      proposalSingletonStructProgramHash: bytesToHex(
        proposalStructProgram.treeHash(),
      ),
    };
  }

  // ── Internals ────────────────────────────────────────────────────────────

  /**
   * Resolve the singleton top-layer v1.1 bytecode from the WASM SDK.
   * Mirrors the resolution order in {@link VaultLaunchSpendService} so
   * upgrades to the SDK that rename the constant accessor surface here
   * once and not in every consumer.
   */
  private singletonTopLayerBytes(): Uint8Array {
    const constants = this.sdk().Constants;
    const bytes =
      constants?.singletonTopLayerV11?.() ?? constants?.singletonTopLayer?.();
    if (!bytes) {
      throw new Error(
        'MintPublishService: singleton top-layer bytecode unavailable in WASM SDK',
      );
    }
    return bytes;
  }

  private clvm(): ClvmShape {
    return new (this.sdk().Clvm)();
  }

  private sdk(): SdkShape {
    const sdk = this.wasm.sdk() as SdkShape | undefined;
    if (!sdk || !sdk.Clvm) {
      throw new Error(
        'MintPublishService: chia-wallet-sdk-wasm not loaded yet. ' +
          'Await ChiaWasmService.ready() before calling hash helpers.',
      );
    }
    return sdk;
  }
}

// ── Return type ────────────────────────────────────────────────────────────

/**
 * Result of {@link MintPublishService.buildMintPublishArtifacts}.
 *
 * Field grouping mirrors the Python ``MintPublishArtifacts`` dataclass:
 *
 *   1. ``computed.*_puzhash`` row that the admin desk surfaces.
 *   2. Launcher-coin identities the downstream spend builder needs to
 *      reference the just-spawned launchers.
 *   3. ``proposalDataHash`` — Artifact A's audit-log binding.
 *   4. Auxiliary CLVM programs (serialized hex + tree hash) curried
 *      into solutions by the spend builder.
 *
 * All hex values are 0x-prefixed.  32-byte hash fields are exactly
 * 64 hex chars; program-serialization fields are variable-length.
 */
export interface MintPublishArtifacts {
  // computed.*_puzhash row
  smartDeedInnerPuzhash: string;
  eveInnerPuzhash: string;
  deedFullPuzhash: string;
  proposalHash: string;
  // Launcher coin identities
  deedLauncherId: string;
  proposalSingletonLauncherId: string;
  // Artifact A binding hash (audit log)
  proposalDataHash: string;
  // Auxiliary CLVM programs
  billOpProgramHex: string;
  billOpProgramHash: string;
  deedSingletonStructProgramHex: string;
  deedSingletonStructProgramHash: string;
  proposalSingletonStructProgramHex: string;
  proposalSingletonStructProgramHash: string;
}

// ── WASM SDK shape (narrowed) ─────────────────────────────────────────────

interface ClvmShape {
  atom(bytes: Uint8Array): ClvmProgramShape;
  int(value: bigint): ClvmProgramShape;
  list(items: ReadonlyArray<ClvmProgramShape>): ClvmProgramShape;
  pair(first: ClvmProgramShape, rest: ClvmProgramShape): ClvmProgramShape;
  deserialize(bytes: Uint8Array): ClvmProgramShape;
}

interface ClvmProgramShape {
  treeHash(): Uint8Array;
  curry(args: ReadonlyArray<ClvmProgramShape>): ClvmProgramShape;
  serialize(): Uint8Array;
}

interface SdkShape {
  Clvm: new () => ClvmShape;
  Constants?: {
    singletonTopLayer?: () => Uint8Array;
    singletonTopLayerV11?: () => Uint8Array;
  };
}
