/**
 * Cross-repo binding test for the TS port of mint_publish_driver.
 *
 * The fixture file (``mint-publish.fixtures.json``) is generated by
 * ``solslot_protocol/scripts/dump_mint_publish_fixtures.py`` and pinned
 * cross-repo by ``solslot_protocol/tests/test_mint_publish_fixtures.py``.
 * Each ``expected.*`` value is asserted byte-for-byte against this
 * service's reproduction of ``build_mint_publish_artifacts``.
 *
 * **If a test here fails:**
 *   1. The TS implementation in ``mint-publish.service.ts`` drifted
 *      from the Python source of truth.  Compare the failing field
 *      against the equivalent step in ``mint_publish_driver.py``.
 *   2. OR the Python source / a curried puzzle .clsp changed and one
 *      of the .puzzle-hex.ts files wasn't regenerated.  Re-run:
 *
 *          cd solslot_protocol
 *          bash scripts/dump_mint_publish_puzzle_hex.sh
 *          .venv/bin/python scripts/dump_mint_publish_fixtures.py
 *
 *      then re-test.
 *
 * WASM bootstrap mirrors ``mint-proposal-v2.service.spec.ts``.
 */
import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting } from '@angular/common/http/testing';

import { ChiaWasmService } from '../chia-wasm.service';
import { bytesToHex } from '../../utils/chia-hash';

import { MintPublishService, type MintPublishArtifacts } from './mint-publish.service';
import { MintProposalV2Service } from './mint-proposal-v2.service';
import fixturesJson from './mint-publish.fixtures.json';
import metadataFixture from '../property-metadata/property-metadata-v1.fixture.json';

// ── Fixture shape ──────────────────────────────────────────────────────────
interface Constants {
  bill_mint_tag: number;
  singleton_amount: number;
  singleton_mod_hash: string;
  singleton_launcher_hash: string;
  protocol_did_singleton_struct_hex: string;
  protocol_did_singleton_struct_hash: string;
  protocol_did_launcher_id: string;
}

interface Inputs {
  property_id_canon: string;
  collection_id_canon: string;
  share_ppm: number;
  par_value_mojos: number;
  asset_class: number;
  jurisdiction_hex: string;
  royalty_puzhash: string;
  royalty_bps: number;
  quorum_threshold: number;
  owner_member_hash: string;
  gov_member_hash: string;
  deed_launcher_parent_coin_name: string;
  proposal_launcher_parent_coin_name: string;
  protocol_did_puzhash: string;
  protocol_did_inner_puzhash: string;
  governance_singleton_struct_hex: string;
  pool_singleton_launcher_id: string;
  pool_singleton_launcher_puzzle_hash: string;
  p2_pool_mod_hash: string;
  p2_vault_mod_hash: string;
  property_registry_puzzle_hash: string;
}

interface Expected {
  smart_deed_inner_puzhash: string;
  eve_inner_puzhash: string;
  deed_full_puzhash: string;
  proposal_hash: string;
  deed_launcher_id: string;
  proposal_singleton_launcher_id: string;
  proposal_data_hash: string;
  bill_op_program_hex: string;
  bill_op_program_hash: string;
  deed_singleton_struct_program_hex: string;
  deed_singleton_struct_program_hash: string;
  proposal_singleton_struct_program_hex: string;
  proposal_singleton_struct_program_hash: string;
}

interface FixtureFile {
  constants: Constants;
  inputs: Inputs;
  expected: Expected;
}

const fixture = fixturesJson as FixtureFile;

// ── Test suite ────────────────────────────────────────────────────────────
describe('MintPublishService', () => {
  let service: MintPublishService;

  beforeAll(async () => {
    // WASM bootstrap mirroring mint-proposal-v2.service.spec.ts.
    if ((window as unknown as { ChiaSDK?: unknown }).ChiaSDK) {
      return;
    }
    // @ts-ignore — deep-import path; types come from chia_wallet_sdk_wasm.d.ts.
    const wasmExports = await import('chia-wallet-sdk-wasm/chia_wallet_sdk_wasm_bg.js');
    const response = await fetch('/assets/chia_wasm/chia_wallet_sdk_wasm_bg.wasm');
    if (!response.ok) {
      throw new Error(`WASM asset fetch failed: ${response.status} ${response.statusText}`);
    }
    const bytes = await response.arrayBuffer();
    const result = await WebAssembly.instantiate(bytes, {
      './chia_wallet_sdk_wasm_bg.js': wasmExports as unknown as WebAssembly.ModuleImports,
    });
    const setWasm = (
      wasmExports as unknown as {
        __wbg_set_wasm?: (w: WebAssembly.Exports) => void;
      }
    ).__wbg_set_wasm;
    if (typeof setWasm !== 'function') {
      throw new Error('chia_wallet_sdk_wasm_bg.js missing __wbg_set_wasm');
    }
    setWasm(result.instance.exports);
    (window as unknown as { ChiaSDK: unknown }).ChiaSDK = wasmExports;
  });

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [provideHttpClient(), provideHttpClientTesting()],
    });
    const wasmService = TestBed.inject(ChiaWasmService);
    wasmService.probeReady();
    service = TestBed.inject(MintPublishService);
  });

  // ── Constants ──
  describe('constants', () => {
    it('BILL_MINT_TAG matches the fixture (0x4d = "M")', () => {
      expect(MintPublishService.BILL_MINT_TAG).toBe(fixture.constants.bill_mint_tag);
      expect(MintPublishService.BILL_MINT_TAG).toBe(0x4d);
    });

    it('SINGLETON_AMOUNT matches the fixture (odd-amount singleton convention)', () => {
      expect(MintPublishService.SINGLETON_AMOUNT).toBe(fixture.constants.singleton_amount);
      expect(MintPublishService.SINGLETON_AMOUNT).toBe(1);
    });

    it('SINGLETON_MOD_HASH matches the fixture (chia bundled value)', () => {
      expect(MintPublishService.SINGLETON_MOD_HASH).toBe(fixture.constants.singleton_mod_hash);
    });

    it('SINGLETON_LAUNCHER_HASH matches the fixture (chia bundled value)', () => {
      expect(MintPublishService.SINGLETON_LAUNCHER_HASH).toBe(
        fixture.constants.singleton_launcher_hash,
      );
    });
  });

  // ── deedLauncherPuzzleHash (standalone) ──
  describe('deedLauncherPuzzleHash', () => {
    it('matches the wallet-side puzzle hash the deed launcher coin uses', () => {
      const got = service.deedLauncherPuzzleHash(
        fixture.constants.protocol_did_singleton_struct_hex,
      );
      // The fixture pins deed_launcher_id = sha256(parent || did_curried_ph || amount).
      // Reverse-derive the puzzle hash by re-running coinId with the SAME
      // amount + parent and comparing — easier to just compute the
      // singleton_launcher_with_did.curry(struct).treeHash() match here.
      // We do that by checking the puzzle hash flows correctly into the
      // top-level builder (covered below); here we just sanity-check the
      // standalone helper produces the SAME hash that build_mint_publish_artifacts
      // uses internally.
      const fromBuilder = service.buildMintPublishArtifacts(builderArgsFromFixture(fixture));
      // deed_launcher_id = coinId(parent, deed_launcher_puzhash, 1).
      // If deedLauncherPuzzleHash returns the same bytes, the resulting
      // coin id matches the fixture.
      expect(fromBuilder.deedLauncherId).toBe(fixture.expected.deed_launcher_id);
      // Direct format sanity: 32 bytes.
      expect(got.length).toBe(32);
      // It is NOT the standard launcher hash (griefing-safety property).
      expect(bytesToHex(got)).not.toBe(MintPublishService.SINGLETON_LAUNCHER_HASH);
    });
  });

  // ── buildMintPublishArtifacts (cross-repo binding) ──
  describe('buildMintPublishArtifacts', () => {
    let result: MintPublishArtifacts;

    beforeEach(() => {
      result = service.buildMintPublishArtifacts(builderArgsFromFixture(fixture));
    });

    it('smartDeedInnerPuzhash matches Python', () => {
      expect(result.smartDeedInnerPuzhash).toBe(fixture.expected.smart_deed_inner_puzhash);
    });

    it('eveInnerPuzhash matches Python (Artifact A DRAFT eve)', () => {
      expect(result.eveInnerPuzhash).toBe(fixture.expected.eve_inner_puzhash);
    });

    it('deedFullPuzhash matches Python (singleton-wrapped mint-offer eve)', () => {
      expect(result.deedFullPuzhash).toBe(fixture.expected.deed_full_puzhash);
    });

    it('proposalHash matches Python (sha256tree of the expanded MINT bill)', () => {
      expect(result.proposalHash).toBe(fixture.expected.proposal_hash);
    });

    it('deedLauncherId matches Python (DID-gated launcher coin name)', () => {
      expect(result.deedLauncherId).toBe(fixture.expected.deed_launcher_id);
    });

    it('proposalSingletonLauncherId matches Python (standard launcher coin name)', () => {
      expect(result.proposalSingletonLauncherId).toBe(
        fixture.expected.proposal_singleton_launcher_id,
      );
    });

    it('proposalDataHash matches Python (Artifact A audit-log binding)', () => {
      expect(result.proposalDataHash).toBe(fixture.expected.proposal_data_hash);
    });

    it('billOpProgram hex + tree hash match Python', () => {
      expect(result.billOpProgramHex).toBe(fixture.expected.bill_op_program_hex);
      expect(result.billOpProgramHash).toBe(fixture.expected.bill_op_program_hash);
    });

    it('deedSingletonStructProgram hex + tree hash match Python', () => {
      expect(result.deedSingletonStructProgramHex).toBe(
        fixture.expected.deed_singleton_struct_program_hex,
      );
      expect(result.deedSingletonStructProgramHash).toBe(
        fixture.expected.deed_singleton_struct_program_hash,
      );
    });

    it('proposalSingletonStructProgram hex + tree hash match Python', () => {
      expect(result.proposalSingletonStructProgramHex).toBe(
        fixture.expected.proposal_singleton_struct_program_hex,
      );
      expect(result.proposalSingletonStructProgramHash).toBe(
        fixture.expected.proposal_singleton_struct_program_hash,
      );
    });

    it('is deterministic (same inputs → same outputs)', () => {
      // Defence-in-depth: confirm re-running with the SAME inputs
      // produces byte-equal outputs.  Catches stateful-clvm bugs
      // where the WASM Clvm leaks state across calls.
      const a = service.buildMintPublishArtifacts(builderArgsFromFixture(fixture));
      const b = service.buildMintPublishArtifacts(builderArgsFromFixture(fixture));
      expect(a).toEqual(b);
    });

    it('binds primary-purchase proceeds to the signed treasury puzzle hash', () => {
      const base = {
        ...builderArgsFromFixture(fixture),
        metadataRoot: metadataFixture.metadataRoot,
        primaryPurchaseUsdAmountMinor: 125_000,
        primaryPurchaseValidatorPubkeys: ['11', '22', '33'].map(
          (byte) => `0x${byte.repeat(48)}`,
        ),
        primaryPurchaseNetwork: 'testnet11',
      };
      const treasuryA = service.buildMintPublishArtifacts({
        ...base,
        primaryPurchaseProtocolTreasuryPuzhash: `0x${'d4'.repeat(32)}`,
      });
      const treasuryB = service.buildMintPublishArtifacts({
        ...base,
        primaryPurchaseProtocolTreasuryPuzhash: `0x${'d5'.repeat(32)}`,
      });

      expect(treasuryA.deedFullPuzhash).not.toBe(treasuryB.deedFullPuzhash);
      expect(() => service.buildMintPublishArtifacts(base)).toThrowError(
        /protocol treasury puzzle hash/,
      );
    });

    it('cross-binding: proposalHash = sha256tree(expanded MINT bill)', () => {
      // Reproduce the proposal hash computation outside the service via
      // the V2 service's CLVM accessor, as a sanity-cross-check that
      // the bill_op tuple shape we curry matches what the governance
      // tracker expects.  This catches an entire class of "we computed
      // the right tuple but with the wrong tag" bugs.
      const v2 = TestBed.inject(MintProposalV2Service);
      // computeTransitionMessage repurposes the same sha256tree of a
      // 3-tuple [int, int, int] — we need a bill tuple with atoms, so we
      // can't reuse it directly.  Instead, we re-verify by checking that
      // the fixture's bill_op_program_hash matches proposalHash, which
      // is the on-wire identity:
      expect(result.proposalHash).toBe(result.billOpProgramHash);
      // And the fixture's pinned bill_op tag matches the constant:
      expect(MintPublishService.BILL_MINT_TAG).toBe(fixture.constants.bill_mint_tag);
      // Avoid unused-var lint:
      expect(v2).toBeTruthy();
    });
  });

  it('matches the Python metadata-extended MINT bill fixture', () => {
    const vector = metadataFixture.mintVector;
    const result = service.buildMintBillCommitment({
      deedFullPuzhash: vector.inputs.deedFullPuzhash,
      propertyIdCanon: vector.inputs.propertyIdCanon,
      propertyRegistryPuzzleHash: vector.inputs.propertyRegistryPuzhash,
      metadataRoot: metadataFixture.metadataRoot,
      metadataAnchorId: vector.inputs.metadataAnchorId,
    });
    expect(result.programHex).toBe(vector.expected.billProgramHex);
    expect(result.programHash).toBe(vector.expected.billProgramHash);
  });
});

// ── Helpers ────────────────────────────────────────────────────────────────

/**
 * Map fixture's snake_case input fields to the TS service's camelCase
 * keyword args.  Centralised so each test reads the same input shape
 * without re-typing 14 fields.
 */
function builderArgsFromFixture(f: FixtureFile) {
  return {
    propertyIdCanon: f.inputs.property_id_canon,
    collectionIdCanon: f.inputs.collection_id_canon,
    sharePpm: f.inputs.share_ppm,
    parValueMojos: f.inputs.par_value_mojos,
    assetClass: f.inputs.asset_class,
    jurisdictionHex: f.inputs.jurisdiction_hex,
    royaltyPuzhash: f.inputs.royalty_puzhash,
    royaltyBps: f.inputs.royalty_bps,
    quorumThreshold: f.inputs.quorum_threshold,
    ownerMemberHash: f.inputs.owner_member_hash,
    govMemberHash: f.inputs.gov_member_hash,
    deedLauncherParentCoinName: f.inputs.deed_launcher_parent_coin_name,
    proposalLauncherParentCoinName: f.inputs.proposal_launcher_parent_coin_name,
    protocolDidSingletonStructHex: f.constants.protocol_did_singleton_struct_hex,
    protocolDidPuzhash: f.inputs.protocol_did_puzhash,
    protocolDidInnerPuzhash: f.inputs.protocol_did_inner_puzhash,
    governanceSingletonStructHex: f.inputs.governance_singleton_struct_hex,
    poolSingletonLauncherId: f.inputs.pool_singleton_launcher_id,
    poolSingletonLauncherPuzzleHash: f.inputs.pool_singleton_launcher_puzzle_hash,
    p2PoolModHash: f.inputs.p2_pool_mod_hash,
    p2VaultModHash: f.inputs.p2_vault_mod_hash,
    propertyRegistryPuzzleHash: f.inputs.property_registry_puzzle_hash,
  };
}
