import { Injectable, inject } from '@angular/core';

import { ChiaWasmService } from '../chia-wasm.service';
import { hexToBytes, bytesToHex } from '../../utils/chia-hash';
import { MINT_PROPOSAL_INNER_V2_PUZZLE_HEX } from './mint-proposal-v2.puzzle-hex';

/**
 * TS port of selected helpers from
 * ``solslot_protocol/solslot_puzzles/mint_proposal_v2_driver.py``.
 *
 * **Why this exists.**  Phase 9-Hermes-D moves mint-proposal launch +
 * lifecycle off the API and onto the WASM-first path.  This service
 * is the canonical client-side implementation of the off-chain
 * helpers that the V2 mint-proposal puzzle's curry / signing
 * machinery mirrors.
 *
 * **Cross-repo binding.**  The Python helpers in
 * ``mint_proposal_v2_driver.py`` are the source of truth; this TS
 * port is validated against the JSON fixture
 * ``mint-proposal-v2.fixtures.json`` (regenerated by
 * ``solslot_protocol/scripts/dump_mint_proposal_v2_fixtures.py``).
 * Drift between Python and TS surfaces as a Karma test failure.
 *
 * **What this service exposes (compute path):**
 *   * {@link modHash} \u2014 tree hash of the uncurried V2 inner puzzle.
 *   * {@link computeProposalDataHash} \u2014 sha256tree of the
 *     immutable proposal fields (property_id, collection_id, share_ppm,
 *     par, royalty, quorum).
 *   * {@link computeBindingHash} \u2014 the 32-byte value the
 *     curve-specific member's signature commits to.  Locks the sig
 *     to (transition_case, new_state_version, proposal_data_hash);
 *     replay across cases / versions / proposals is blocked.
 *   * {@link computeTransitionMessage} \u2014 the announcement payload
 *     body (sans PROTOCOL_PREFIX) the puzzle emits via
 *     CREATE_PUZZLE_ANNOUNCEMENT.
 *   * {@link makeInnerPuzzleHash} \u2014 tree hash of the V2 inner curried
 *     with its 11 args.  Used for the eve coin's puzzle hash and for
 *     post-transition recurry checks.
 *
 * **What's NOT here yet (deferred):**
 *   * Full launch orchestration (wallet.transfer + buildLauncherCoinSpend
 *     + push_tx).  Lands in a follow-up that wires this service into
 *     the mint-detail UI's "Submit on chain" button.
 *   * Spend-bundle assembly for APPROVE/CANCEL transitions.  Same
 *     follow-up; depends on the EVM/BLS member solution shapes the
 *     wallet returns.
 */
@Injectable({ providedIn: 'root' })
export class MintProposalV2Service {
  private readonly wasm = inject(ChiaWasmService);

  /**
   * Pinned tree hash of the uncurried V2 mint-proposal puzzle.
   * Cross-checked against the .clsp source by the Python regression
   * test ``test_mint_proposal_v2.py::TestModHash::test_mod_hash_pinned``
   * and by this service's own Karma spec.  Drift here means the
   * .puzzle-hex.ts file is out of sync with .clsp.hex.
   */
  static readonly MOD_HASH = '0xbb1379bc24f0a02ca27de58e2200ae4cd1fc1e58d53a49d1119600108741d37e';

  /** State machine constants (mirror the .clsp). */
  static readonly STATE_DRAFT = 1;
  static readonly STATE_APPROVED = 2;
  static readonly STATE_CANCELLED = 3;
  static readonly STATE_EXECUTED = 4;

  /** Transition case opcodes (mirror the .clsp). */
  static readonly TRANSITION_APPROVE = 0x61; // 'a'
  static readonly TRANSITION_CANCEL = 0x63; // 'c'
  static readonly TRANSITION_EXECUTE = 0x78; // 'x'

  /**
   * Tree hash of the uncurried V2 inner puzzle.  Derived from the
   * bundled puzzle hex via ``Clvm.deserialize().treeHash()`` so the
   * exact algorithm matches the on-chain puzzle and Python helpers.
   *
   * Returned as ``Uint8Array`` (32 bytes) for compatibility with
   * downstream callers; use {@link bytesToHex} for the 0x-prefixed
   * string form expected by spec assertions and fixture comparisons.
   */
  modHash(): Uint8Array {
    const clvm = this.clvm();
    const puzzleBytes = hexToBytes(MINT_PROPOSAL_INNER_V2_PUZZLE_HEX);
    return clvm.deserialize(puzzleBytes).treeHash();
  }

  /**
   * sha256tree of ``(property_id_canon, collection_id_canon, share_ppm,
   * par_value_mojos, royalty_bps, quorum_threshold)``.
   *
   * @param args.propertyIdCanon 0x-prefixed 32-byte hex from the
   *   property registry's canonicaliser.
   * @param args.collectionIdCanon 0x-prefixed 32-byte hex identifying the
   *   deed's Pool Economic V2 collection.
   * @param args.sharePpm Deed share in parts-per-million; 1_000_000 is 100%.
   * @param args.parValueMojos uint64 par value in mojos.
   * @param args.royaltyBps 0\u201310000 inclusive (range guarded off-chain).
   * @param args.quorumThreshold SGT vote threshold for execution.
   */
  computeProposalDataHash(args: {
    propertyIdCanon: string;
    collectionIdCanon: string;
    sharePpm: number | bigint;
    parValueMojos: number | bigint;
    royaltyBps: number | bigint;
    quorumThreshold: number | bigint;
  }): Uint8Array {
    const clvm = this.clvm();
    const list = clvm.list([
      clvm.atom(hexToBytes(args.propertyIdCanon)),
      clvm.atom(hexToBytes(args.collectionIdCanon)),
      clvm.int(BigInt(args.sharePpm)),
      clvm.int(BigInt(args.parValueMojos)),
      clvm.int(BigInt(args.royaltyBps)),
      clvm.int(BigInt(args.quorumThreshold)),
    ]);
    return list.treeHash();
  }

  /**
   * sha256tree of ``(transition_case, new_state_version,
   * proposal_data_hash)``.  This is the 32-byte value the curve-
   * specific member's signature commits to:
   *
   *   * For Eip712Member, it's the ``Delegated_Puzzle_Hash`` slot
   *     of the EIP-712 envelope (``ChiaCoinSpend(bytes32 coin_id,
   *     bytes32 delegated_puzzle_hash)``).
   *   * For BlsMember (or any AGG_SIG_ME-emitting member), it's the
   *     message bytes the signature targets.
   *
   * Mirrors ``mint_proposal_v2_driver.compute_binding_hash``.  Replay
   * protection: a sig collected for one
   * ``(case, version, proposal)`` triple cannot authorise any other.
   */
  computeBindingHash(args: {
    transitionCase: number;
    newStateVersion: number | bigint;
    proposalDataHash: string;
  }): Uint8Array {
    const clvm = this.clvm();
    const list = clvm.list([
      clvm.int(BigInt(args.transitionCase)),
      clvm.int(BigInt(args.newStateVersion)),
      clvm.atom(hexToBytes(args.proposalDataHash)),
    ]);
    return list.treeHash();
  }

  /**
   * sha256tree of ``(transition_case, new_state, new_state_version)``.
   * Off-chain consumers (the legacy API indexer and any future on-
   * chain monitor) consume the puzzle's announcement as
   * ``PROTOCOL_PREFIX (0x53) || compute_transition_message(...)``;
   * this helper produces the message body without the prefix so the
   * caller can prepend it themselves (mirrors the v1 + v2 puzzle's
   * ``transition-message`` defun).
   */
  computeTransitionMessage(args: {
    transitionCase: number;
    newState: number;
    newStateVersion: number | bigint;
  }): Uint8Array {
    const clvm = this.clvm();
    const list = clvm.list([
      clvm.int(BigInt(args.transitionCase)),
      clvm.int(BigInt(args.newState)),
      clvm.int(BigInt(args.newStateVersion)),
    ]);
    return list.treeHash();
  }

  /**
   * Tree hash of the V2 inner puzzle curried with its immutable execution
   * context and state slots.
   * Currying order MUST match ``mint_proposal_inner_v2.clsp`` and
   * ``mint_proposal_v2_driver.make_inner_puzzle``:
   *
   *   1. ``SELF_MOD_HASH``  \u2014 produced by {@link modHash}
   *   2. ``OWNER_MEMBER_HASH``
   *   3. ``GOV_MEMBER_HASH``
   *   4. ``PROPOSAL_DATA_HASH``
   *   5. ``GOVERNANCE_SINGLETON_STRUCT``
   *   6. ``GOVERNANCE_PROPOSAL_HASH``
   *   7. ``DEED_LAUNCHER_ID``
   *   8. ``DID_INNER_PUZZLE_HASH``
   *   9. ``DEED_FULL_PUZZLE_HASH``
   *   10. ``PROPOSAL_STATE``
   *   11. ``STATE_VERSION``
   *
   * Used as the eve coin's inner puzzle hash at launch and as the
   * post-transition hash for CREATE_COIN's recurry check.  Drift
   * here would mean every spend computes a different inner hash than
   * the chain expects, bricking the proposal lineage.
   */
  makeInnerPuzzleHash(args: {
    ownerMemberHash: string;
    govMemberHash: string;
    proposalDataHash: string;
    governanceSingletonStructHex: string;
    governanceProposalHash: string;
    deedLauncherId: string;
    didInnerPuzzleHash: string;
    deedFullPuzzleHash: string;
    proposalState: number;
    stateVersion: number | bigint;
  }): Uint8Array {
    return this.makeInnerPuzzle(args).treeHash();
  }

  /**
   * Build the curried V2 inner puzzle and return its **serialized**
   * CLVM bytecode as 0x-hex.
   *
   * Same curry as {@link makeInnerPuzzleHash} (the hash variant just
   * tree-hashes this program); exposed so spend builders that wrap the
   * inner puzzle in a singleton (e.g. the Artifact A launcher → eve
   * hop in
   * {@link MintPublishSpendBuilderService.buildProposalEveLaunchSpend})
   * have the actual puzzle reveal, not only its hash.
   */
  makeInnerPuzzleHex(args: {
    ownerMemberHash: string;
    govMemberHash: string;
    proposalDataHash: string;
    governanceSingletonStructHex: string;
    governanceProposalHash: string;
    deedLauncherId: string;
    didInnerPuzzleHash: string;
    deedFullPuzzleHash: string;
    proposalState: number;
    stateVersion: number | bigint;
  }): string {
    return bytesToHex(this.makeInnerPuzzle(args).serialize());
  }

  private makeInnerPuzzle(args: {
    ownerMemberHash: string;
    govMemberHash: string;
    proposalDataHash: string;
    governanceSingletonStructHex: string;
    governanceProposalHash: string;
    deedLauncherId: string;
    didInnerPuzzleHash: string;
    deedFullPuzzleHash: string;
    proposalState: number;
    stateVersion: number | bigint;
  }): ClvmProgramShape {
    const clvm = this.clvm();
    const puzzle = clvm.deserialize(hexToBytes(MINT_PROPOSAL_INNER_V2_PUZZLE_HEX));
    return puzzle.curry([
      clvm.atom(this.modHash()),
      clvm.atom(hexToBytes(args.ownerMemberHash)),
      clvm.atom(hexToBytes(args.govMemberHash)),
      clvm.atom(hexToBytes(args.proposalDataHash)),
      clvm.deserialize(hexToBytes(args.governanceSingletonStructHex)),
      clvm.atom(hexToBytes(args.governanceProposalHash)),
      clvm.atom(hexToBytes(args.deedLauncherId)),
      clvm.atom(hexToBytes(args.didInnerPuzzleHash)),
      clvm.atom(hexToBytes(args.deedFullPuzzleHash)),
      clvm.int(BigInt(args.proposalState)),
      clvm.int(BigInt(args.stateVersion)),
    ]);
  }

  // \u2500\u2500 Internals \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500
  /**
   * Lazy WASM Clvm accessor.  Throws a clear error if the SDK isn't
   * loaded yet \u2014 callers should wait for ``ChiaWasmService.ready()``
   * before invoking the hash helpers.  Mirrors the pattern in
   * {@link AdminAuthorityV2Service.clvm}.
   */
  private clvm(): ClvmShape {
    const sdk = this.wasm.sdk() as { Clvm?: new () => ClvmShape };
    if (!sdk.Clvm) {
      throw new Error(
        'MintProposalV2Service: chia-wallet-sdk-wasm not loaded yet. ' +
          'Await ChiaWasmService.ready() before calling hash helpers.',
      );
    }
    return new sdk.Clvm();
  }
}

// Re-export for convenience so callers don't need a separate import to
// turn the Uint8Array helpers into 0x-hex strings for fixture comparison.
export { bytesToHex };

// \u2500\u2500\u2500 WASM SDK shape (narrowed) \u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500\u2500

/**
 * Narrowed view of the chia-wallet-sdk-wasm ``Clvm`` class surface
 * we actually use.  Avoids depending on the sprawling SDK type
 * signature; mirrors the equivalent shape used by
 * {@link AdminAuthorityV2Service}.
 */
interface ClvmShape {
  atom(bytes: Uint8Array): ClvmProgramShape;
  int(value: bigint): ClvmProgramShape;
  list(items: ReadonlyArray<ClvmProgramShape>): ClvmProgramShape;
  deserialize(bytes: Uint8Array): ClvmProgramShape;
}

interface ClvmProgramShape {
  treeHash(): Uint8Array;
  curry(args: ReadonlyArray<ClvmProgramShape>): ClvmProgramShape;
  serialize(): Uint8Array;
}
