/** Solslot V2 development defaults. Ceremony coordinates are intentionally empty. */
export const environment = {
  production: false,
  schemaVersion: 2 as const,
  protocolVersion: 'solslot-v2' as const,
  experienceMode: 'testnet-alpha' as const,
  protocolWritesEnabled: true,
  strictProtocolCoordinatePins: true,
  bootstrapTag: 'SOLSLOT_BOOTSTRAP_V2' as const,

  faucetApi: 'http://127.0.0.1:8787',
  legacyRecallApi: 'http://127.0.0.1:5000',
  coinsetRpc: 'https://testnet11.api.coinset.org',
  chiaNetwork: 'testnet11' as 'testnet11' | 'mainnet',
  walletConnectProjectId: '3145bc617be2b491a8e6033b3b0fcf43',
  eip712Name: 'Solslot Protocol' as const,
  eip712Version: '2' as const,
  eip712ChainId: 11155111,

  zkPassport: {
    policyVersion: 2,
    verificationUrl: '/verify',
    evmRpcUrl: '',
    evmChainId: 11155111,
    attestationEmitterAddress: '',
    attestationEmitterFromBlock: 0,
    trustedForwarderAddress: '',
    forwarderName: 'SolslotForwarder',
    evmPollTimeoutMs: 120_000,
    bridgeParentId: '',
    bridgeAmount: 1,
    validatorPubkeys: [] as string[],
    validatorThreshold: 0,
    devMode: true,
  },

  /** Populated only from the signed Solslot V2 ceremony artifact. */
  solslotProtocol: {
    artifactHash: '',
    adminPortalSourceSha: '',
    artifactVerified: false,
    retiredCoordinates: [] as string[],
    adminAuthorityV2LauncherId: '',
    adminAuthorityV2MipsRootHash: '',
    adminAuthorityV2QuorumMode: 'mofn1of1' as 'bare' | 'mofn1of1',
    adminAuthorityV2AdminAddresses: [] as string[],
    adminAuthorityV2AdminPubkeys: [] as string[],
    protocolConfigLauncherId: '',
    propertyRegistryLauncherId: '',
    propertyRegistryGovPubkey: '',
    collectionNavRegistryLauncherId: '',
    poolLauncherId: '',
    poolInnerPuzzleHash: '',
    bridgePolicyHash: '',
    membersMerkleRoot: '',
    governanceLauncherId: '',
    governanceQuorumBps: 5000,
    governanceVotingWindowSeconds: 300,
    governanceSgtTotalSupply: 1_000_000,
    governanceMinProposalStake: 10_000,
    sgtGenesisCoinId: '',
    sgtTailHash: '',
    protocolConfigModHash: '',
    propertyRegistryModHash: '',
    mintProposalModHash: '',
    vaultInnerModHash: '',
    vaultVersionRegistryLauncherId: '',
    vaultVersionRegistryModHash: '',
    protocolDidSingletonStructHex: '',
    protocolDidPuzhash: '',
    p2PoolModHash: '',
    p2VaultModHash: '',
    propertyRegistryCurrentPuzzleHash: '',
  },
};
