import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting } from '@angular/common/http/testing';

import { ChiaWasmService } from '../chia-wasm.service';
import { PgtDriverService } from './pgt-driver.service';
import { bytesToHex } from '../../utils/chia-hash';
import mintPublishFixture from '../mint-proposal-v2/mint-publish.fixtures.json';

// ─── Python cross-fixtures ──────────────────────────────────────────────
// Values generated by populis_protocol's pgt_driver against fixed
// inputs.  Drift here means either the bundled .puzzle-hex.ts files
// are stale or the curry-and-treehash math is wrong.
//
// Input vectors (must match what generated these constants):
const GENESIS_COIN_ID = '0x' + '00'.repeat(31) + 'aa';
const TRACKER_LAUNCHER_ID = '0x' + '00'.repeat(31) + 'bb';
const DEED_PUZZLE_HASH = '0x' + '00'.repeat(31) + 'cc';
const VOTER_INNER_PUZZLE_HASH = '0x' + '00'.repeat(31) + 'dd';
const PROPOSAL_HASH = '0x' + '00'.repeat(31) + 'ee';
const VV_INNER_MOD_HASH = '0x' + '00'.repeat(31) + '01';
const VV_PARAMS_HASH = '0x' + '00'.repeat(31) + '02';
const VV_VERSION = 2n;
const LOCK_AMOUNT = 100_000n;
const LOCK_DEADLINE = 1_000_000n;

// Expected outputs (from Python).
const EXPECTED = {
  trackerStructHash: '0x7afc743110b633ca1b1d52c25386ddeb0f6cf02d1408de73c4c0a7eb7cf5d01e',
  pgtTailHash:        '0x8fc6334ddfc2b486e366b67b37cc9de986a342c03f2e7b7cb8d4ff094a6a8ded',
  pgtFreeInnerHash:   '0x0184a35afc5abd12c0b331c4fa5000e914bed020eaf0cb15581a35792ce8915d',
  pgtLockedInnerHash: '0xf444f5b8e82f57aaa060c8425e4c16b42bc851f1d3abee23a76e0ffea1f05e23',
  catPgtFreePuzhash:  '0xb6b1fcdc4bcb25f31e29a545239cf4da7ed35da70fdf85ac00b3d16e423a9277',
  billMint:           '0xd7582ffa72b0a5044b9284f9d91947a24c59caff847157943f991fc3e994912d',
  billSettle:         '0x4b6b3bcadad3e62c2c36c7ac8b3ffd28679590ef77e6e387fedd1a8946ec867b',
  billVaultVersion:  '0xde049c8cb6fbee29e8f925ed9d2fee7dbb7823c5edda3e1d51f5374da65971f0',
  lockArgsTreeHash:   '0x49dc1c754139a79d33feae0e7d6a66a47d770323ff9e95b17379749c96911c1d',
  lockAnnouncementId: '0xcb824e9573d825c27c7d315499b7a9e0cf9558b4d2a3f155efbcec03928a0a27',
};

function hex(b: Uint8Array): string {
  return bytesToHex(b);
}

describe('PgtDriverService', () => {
  let service: PgtDriverService;

  beforeAll(async () => {
    if ((window as unknown as { ChiaSDK?: unknown }).ChiaSDK) {
      return;
    }
    // @ts-ignore — deep-import; types come from chia_wallet_sdk_wasm.d.ts.
    const wasmExports = await import('chia-wallet-sdk-wasm/chia_wallet_sdk_wasm_bg.js');
    const response = await fetch('/assets/chia_wasm/chia_wallet_sdk_wasm_bg.wasm');
    if (!response.ok) {
      throw new Error(
        `WASM asset fetch failed: ${response.status} ${response.statusText}.\n` +
          'Karma must serve src/assets/chia_wasm at /assets/chia_wasm — ' +
          'check angular.json:test.assets.',
      );
    }
    const bytes = await response.arrayBuffer();
    const result = await WebAssembly.instantiate(bytes, {
      './chia_wallet_sdk_wasm_bg.js': wasmExports as unknown as WebAssembly.ModuleImports,
    });
    const setWasm = (wasmExports as unknown as { __wbg_set_wasm?: (w: WebAssembly.Exports) => void }).__wbg_set_wasm;
    if (typeof setWasm !== 'function') {
      throw new Error('chia_wallet_sdk_wasm_bg.js missing __wbg_set_wasm');
    }
    setWasm(result.instance.exports);
    (window as unknown as { ChiaSDK: unknown }).ChiaSDK = wasmExports;
  });

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [provideHttpClient(), provideHttpClientTesting()],
    });
    TestBed.inject(ChiaWasmService).probeReady();
    service = TestBed.inject(PgtDriverService);
  });

  // ── Canonical mod-hashes ─────────────────────────────────────────────

  it('pgt_tail bytecode tree-hashes to the canonical mod hash', () => {
    expect(hex(service.pgtTailModHash())).toBe(PgtDriverService.PGT_TAIL_MOD_HASH);
  });

  it('pgt_free_inner bytecode tree-hashes to the canonical mod hash', () => {
    expect(hex(service.pgtFreeInnerModHash())).toBe(PgtDriverService.PGT_FREE_INNER_MOD_HASH);
  });

  it('pgt_locked_inner bytecode tree-hashes to the canonical mod hash', () => {
    expect(hex(service.pgtLockedInnerModHash())).toBe(PgtDriverService.PGT_LOCKED_INNER_MOD_HASH);
  });

  it('governance_singleton_inner bytecode tree-hashes to the canonical mod hash', () => {
    expect(hex(service.governanceTrackerInnerModHash())).toBe(
      PgtDriverService.GOVERNANCE_TRACKER_INNER_MOD_HASH,
    );
  });

  // ── Cross-validation against Python pgt_driver ──────────────────────

  it('trackerStructHash matches Python pd.make_proposal_tracker_struct().get_tree_hash()', () => {
    expect(
      hex(service.trackerStructHash({ trackerLauncherId: TRACKER_LAUNCHER_ID })),
    ).toBe(EXPECTED.trackerStructHash);
  });

  it('pgtTailHash matches Python pd.pgt_tail_hash(genesis)', () => {
    expect(hex(service.pgtTailHash(GENESIS_COIN_ID))).toBe(EXPECTED.pgtTailHash);
  });

  it('pgtFreeInnerHash matches Python pd.pgt_free_inner_hash(...)', () => {
    const trackerStruct = service.trackerStructHash({ trackerLauncherId: TRACKER_LAUNCHER_ID });
    expect(
      hex(
        service.pgtFreeInnerHash({
          trackerStructHash: trackerStruct,
          voterInnerPuzzleHash: VOTER_INNER_PUZZLE_HASH,
        }),
      ),
    ).toBe(EXPECTED.pgtFreeInnerHash);
  });

  it('pgtLockedInnerHash matches Python pd.pgt_locked_inner_hash(...)', () => {
    const trackerStruct = service.trackerStructHash({ trackerLauncherId: TRACKER_LAUNCHER_ID });
    expect(
      hex(
        service.pgtLockedInnerHash({
          trackerStructHash: trackerStruct,
          voterInnerPuzzleHash: VOTER_INNER_PUZZLE_HASH,
          lockProposalHash: PROPOSAL_HASH,
          lockDeadlineSeconds: LOCK_DEADLINE,
        }),
      ),
    ).toBe(EXPECTED.pgtLockedInnerHash);
  });

  it('catPgtFreePuzzleHash matches Python pd.cat_pgt_free_puzzle_hash(...)', () => {
    const trackerStruct = service.trackerStructHash({ trackerLauncherId: TRACKER_LAUNCHER_ID });
    const pgtFreeHash = service.pgtFreeInnerHash({
      trackerStructHash: trackerStruct,
      voterInnerPuzzleHash: VOTER_INNER_PUZZLE_HASH,
    });
    const tail = service.pgtTailHash(GENESIS_COIN_ID);
    expect(
      hex(
        service.catPgtFreePuzzleHash({
          pgtFreeInnerHash: pgtFreeHash,
          pgtTailHash: tail,
        }),
      ),
    ).toBe(EXPECTED.catPgtFreePuzhash);
  });

  // ── Bill proposal hashes ────────────────────────────────────────────

  it('billMint matches Python pd.proposal_hash_from_bill(pd.bill_mint(...))', () => {
    expect(hex(service.billMint(DEED_PUZZLE_HASH))).toBe(EXPECTED.billMint);
  });

  it('billMint binds property registry context when supplied', () => {
    expect(
      hex(
        service.billMint(
          mintPublishFixture.expected.deed_full_puzhash,
          mintPublishFixture.inputs.property_id_canon,
          mintPublishFixture.inputs.property_registry_puzzle_hash,
        ),
      ),
    ).toBe(mintPublishFixture.expected.proposal_hash);
  });

  it('billVaultVersion matches Python pd.proposal_hash_from_bill(pd.bill_vault_version(...))', () => {
    expect(
      hex(
        service.billVaultVersion({
          newVaultInnerModHash: VV_INNER_MOD_HASH,
          newCanonicalParamsHash: VV_PARAMS_HASH,
          newVaultVersion: VV_VERSION,
        }),
      ),
    ).toBe(EXPECTED.billVaultVersion);
  });

  it('billFreeze produces a 32-byte tree hash for status=1', () => {
    const h = service.billFreeze(1);
    expect(h.length).toBe(32);
  });

  it('billSettle produces a 32-byte tree hash with bigint args', () => {
    const h = service.billSettle({
      splitxchRoot: '0x' + '0a'.repeat(32),
      totalAmountMojos: 1_234_567n,
      numDeeds: 42n,
      deedReleasesHash: '0x' + '0d'.repeat(32),
    });
    expect(hex(h)).toBe(EXPECTED.billSettle);
  });

  // ── LOCK announcement chain ─────────────────────────────────────────

  it('lockArgsTreeHash matches Python sha256tree(LOCK_TAG proposal_hash amount deadline)', () => {
    expect(
      hex(service.lockArgsTreeHash(PROPOSAL_HASH, LOCK_AMOUNT, LOCK_DEADLINE)),
    ).toBe(EXPECTED.lockArgsTreeHash);
  });

  it('lockAnnouncementId matches the on-chain sender || prefix || sha256tree(...) digest', async () => {
    const trackerStruct = service.trackerStructHash({ trackerLauncherId: TRACKER_LAUNCHER_ID });
    const pgtFreeHash = service.pgtFreeInnerHash({
      trackerStructHash: trackerStruct,
      voterInnerPuzzleHash: VOTER_INNER_PUZZLE_HASH,
    });
    const tail = service.pgtTailHash(GENESIS_COIN_ID);
    const catFreePh = service.catPgtFreePuzzleHash({
      pgtFreeInnerHash: pgtFreeHash,
      pgtTailHash: tail,
    });
    const ann = await service.lockAnnouncementId({
      catPgtFreePuzhash: catFreePh,
      proposalHash: PROPOSAL_HASH,
      amountMojos: LOCK_AMOUNT,
      lockDeadlineSeconds: LOCK_DEADLINE,
    });
    expect(hex(ann)).toBe(EXPECTED.lockAnnouncementId);
  });
});
