import { Injectable, inject } from '@angular/core';

import { ChiaWasmService } from '../chia-wasm.service';
import { bytesToHex, hexToBytes } from '../../utils/chia-hash';
import { CAT_MOD_PUZZLE_HEX } from './cat-mod.puzzle-hex';
import { PgtDriverService } from './pgt-driver.service';

/**
 * TS port of the canonical PGT VOTE spend builders in
 * ``populis_protocol/populis_puzzles/pgt_driver.py``:
 *
 *   * {@link buildPgtLockCoinSpend}     ↔ ``build_pgt_lock_coin_spend``
 *   * {@link buildTrackerVoteCoinSpend} ↔ ``build_tracker_vote_coin_spend``
 *
 * **Phase 3b of the committee/mint governance UI brick.**  The portal's
 * committee VOTE flow assembles these two CoinSpends, the wallet signs
 * the voter's inner ``AGG_SIG_ME`` conditions via
 * {@link ChiaWalletService.signSpendBundle}, and the bundle is POSTed to
 * the ``/admin/committee/vote`` publish-only forwarder.
 *
 * **Cross-validation.**  Every output of this service is asserted byte-for-byte
 * equal to the Python builder via
 * ``pgt-driver/pgt-vote-spend.fixtures.json`` (generated by
 * ``populis_protocol/scripts/dump_pgt_vote_spend_fixtures.py``).  If you
 * change either side, regenerate the fixture and run both Karma + pytest.
 *
 * **What this builder does NOT do.**
 *
 *  * Sign anything.  All signing is the wallet's job; the produced spends
 *    are unsigned.
 *  * Discover PGT coins.  ``PgtCoinDiscoveryService`` (Phase 3c) takes
 *    care of locating the voter's free PGT coin via coinset.
 *  * Decide what proposal / amount / deadline to vote with.  Those come
 *    from {@link GovernanceTrackerReaderService} state + user input.
 */
@Injectable({ providedIn: 'root' })
export class PgtVoteSpendBuilderService {
  private readonly wasm = inject(ChiaWasmService);
  private readonly pgt = inject(PgtDriverService);

  // ── Spend-case constants (mirrors pgt_driver.py PGT_LOCK / TRK_VOTE) ──
  static readonly PGT_LOCK = 2;
  static readonly TRK_VOTE = 2;

  // ────────────────────────────────────────────────────────────────────
  //  PGT lock CoinSpend (CAT2-wrapped pgt_free_inner LOCK)
  // ────────────────────────────────────────────────────────────────────

  /**
   * Build the unsigned CAT2-wrapped ``pgt_free_inner`` LOCK CoinSpend.
   *
   * Mirrors ``populis_puzzles.pgt_driver.build_pgt_lock_coin_spend`` exactly
   * — the produced ``puzzle_reveal`` and ``solution`` hex strings are
   * byte-identical (validated by Karma spec fixture).
   *
   * @param args.pgtCoin              The free PGT coin to lock.  Its puzzle
   *   hash MUST equal
   *   ``PgtDriverService.catPgtFreePuzzleHash({...voter args})`` for the
   *   same ``trackerStruct`` + ``voterInnerPuzzleHash``.
   * @param args.voterInnerPuzzleHex  Reveal of the PGT owner's inner puzzle
   *   (e.g. p2_delegated_puzzle_or_hidden_puzzle).  Tree hash MUST equal the
   *   ``voterInnerPuzzleHash`` the PGT free coin was minted with.  As 0x-hex.
   * @param args.voterInnerSolutionHex  The owner's signed inner solution.
   *   It must yield exactly one ``CREATE_COIN`` to the canonical
   *   ``pgt_locked_inner`` puzhash with ``amount == pgtCoin.amount``.  Any
   *   other inner conditions (AGG_SIG_ME etc.) pass through.  As 0x-hex.
   * @param args.trackerLauncherId    Tracker singleton launcher id (0x-hex).
   *   Used to build the curried tracker struct that pgt_free_inner needs
   *   in its inner curry.
   * @param args.pgtTailHash          PGT TAIL puzzle hash (0x-hex).  This is
   *   the CAT2 outer's asset_id.
   * @param args.lineageProof         PGT coin's lineage proof (parent
   *   eve/regular).  When the PGT coin is a CAT2 ring-of-1 with a known
   *   parent, the proof has all three fields populated.  When it's an
   *   eve-style coin (first non-issuance spend), pass an empty proof
   *   (all undefined).
   * @param args.proposalHash         32-byte ``sha256tree(bill_op)`` of the
   *   open proposal we're voting on.  0x-hex.
   * @param args.deadlineSeconds      Absolute uint64 seconds of the
   *   proposal's voting deadline.
   *
   * @returns An unsigned spend (coin + puzzle_reveal + solution as 0x-hex)
   *   in the shape ``ChiaWalletService.signSpendBundle`` expects.
   */
  buildPgtLockCoinSpend(args: BuildPgtLockArgs): UnsignedCoinSpendHex {
    const sdk = this.sdk();
    const clvm = this.clvm();
    const Coin = sdk.Coin;

    // ── 1. Re-derive the PGT free inner puzzle (pgt_free_inner curried) ──
    const voterInnerHex = args.voterInnerPuzzleHex.startsWith('0x')
      ? args.voterInnerPuzzleHex
      : '0x' + args.voterInnerPuzzleHex;
    const voterInnerPuzzleBytes = hexToBytes(voterInnerHex);
    const voterInnerPuzzle = clvm.deserialize(voterInnerPuzzleBytes);
    const voterInnerPuzzleHash = voterInnerPuzzle.treeHash();

    const trackerStruct = this.buildTrackerStruct(
      clvm,
      hexToBytes(this.normalizeHex(args.trackerLauncherId)),
    );
    const freeInnerPuzzle = this.curriedPgtFreeInner(clvm, {
      trackerStruct,
      voterInnerPuzzleHash,
    });

    // ── 2. Build the pgt_free_inner LOCK solution ──
    //   (spend_case inner_puzzle inner_solution case_args)
    //   case_args for LOCK: (proposal_hash deadline my_amount)
    const innerSolution = clvm.list([
      clvm.int(BigInt(PgtVoteSpendBuilderService.PGT_LOCK)),
      voterInnerPuzzle,
      clvm.deserialize(hexToBytes(this.normalizeHex(args.voterInnerSolutionHex))),
      clvm.list([
        clvm.atom(hexToBytes(this.normalizeHex(args.proposalHash))),
        clvm.int(BigInt(args.deadlineSeconds)),
        clvm.int(BigInt(args.pgtCoin.amount)),
      ]),
    ]);

    // ── 3. Wrap in CAT2 outer ──
    const catFullPuzzle = this.curriedCatMod(clvm, {
      pgtTailHash: hexToBytes(this.normalizeHex(args.pgtTailHash)),
      innerPuzzle: freeInnerPuzzle,
    });

    // Sanity: the produced puzzle hash MUST equal the coin's claimed puzzle
    // hash, otherwise the spend would land on the wrong coin id.
    const expectedPh = catFullPuzzle.treeHash();
    const claimedPh = hexToBytes(this.normalizeHex(args.pgtCoin.puzzleHash));
    if (!this.bytesEqual(expectedPh, claimedPh)) {
      throw new Error(
        `pgt-vote-spend: built puzzle hash ${bytesToHex(expectedPh)} ` +
          `does not match coin's claimed puzzle hash ${bytesToHex(claimedPh)}. ` +
          'Check trackerStruct / voter inner / pgt tail hash align.',
      );
    }

    // ── 4. Build the CAT2 outer solution ──
    //   [inner_solution, lineage_proof, prev_id, my_info, next_info,
    //    subtotal, extra_delta]
    //
    // For a single-coin spend (ring of 1, LOCK preserves supply):
    //   prev_id   = my own coin id
    //   my_info   = [parent, full_ph, amount]
    //   next_info = [parent, inner_ph, amount]   ← lineage proof shape for child
    //   subtotal  = 0
    //   extra_delta = 0
    const pgtCoin = new Coin(
      hexToBytes(this.normalizeHex(args.pgtCoin.parentCoinInfo)),
      claimedPh,
      BigInt(args.pgtCoin.amount),
    );
    const myCoinId = pgtCoin.coinId();
    const myInfo = clvm.list([
      clvm.atom(pgtCoin.parentCoinInfo),
      clvm.atom(claimedPh),
      clvm.int(BigInt(args.pgtCoin.amount)),
    ]);
    const freeInnerHash = freeInnerPuzzle.treeHash();
    const nextInfo = clvm.list([
      clvm.atom(pgtCoin.parentCoinInfo),
      clvm.atom(freeInnerHash),
      clvm.int(BigInt(args.pgtCoin.amount)),
    ]);

    const lineageProofProgram = this.encodeLineageProof(clvm, args.lineageProof);

    const outerSolution = clvm.list([
      innerSolution,
      lineageProofProgram,
      clvm.atom(myCoinId),
      myInfo,
      nextInfo,
      clvm.int(BigInt(0)),
      clvm.int(BigInt(0)),
    ]);

    return {
      coin: {
        parentCoinInfo: bytesToHex(pgtCoin.parentCoinInfo),
        puzzleHash: bytesToHex(claimedPh),
        amount: args.pgtCoin.amount,
      },
      puzzleReveal: bytesToHex(catFullPuzzle.serialize()),
      solution: bytesToHex(outerSolution.serialize()),
    };
  }

  // ────────────────────────────────────────────────────────────────────
  //  Tracker VOTE CoinSpend (singleton-wrapped TRK_VOTE)
  // ────────────────────────────────────────────────────────────────────

  /**
   * Build the unsigned singleton-wrapped ``TRK_VOTE`` CoinSpend.
   *
   * Mirrors ``populis_puzzles.pgt_driver.build_tracker_vote_coin_spend``.
   * Recreates the tracker singleton in its next OPEN state with increased
   * ``vote_tally``; asserts the canonical LOCK announcement id the
   * co-spent PGT lock spend emits.
   *
   * @param args.trackerCoin              The current tracker singleton coin
   *   in OPEN state.  Its puzzle hash MUST equal
   *   ``singleton_top_layer_v1_1.curry([trackerStruct, trackerInner]).tree_hash()``
   *   for the given ``trackerLauncherId`` + ``trackerInnerPuzzleHex``.
   * @param args.trackerInnerPuzzleHex    The OPEN-state curried tracker
   *   inner puzzle reveal (0x-hex).  Tree hash of this is what
   *   ``my_inner_puzzlehash`` in the inner solution carries.
   * @param args.trackerLauncherId        Tracker singleton launcher id
   *   (0x-hex).
   * @param args.lineageProof             Tracker coin's parent lineage
   *   proof (all 3 fields required for non-eve spends).
   * @param args.voterInnerPuzzleHash     Voter's inner puzzle hash (0x-hex).
   *   MUST match the PGT free coin's owner curry so the LOCK announcement
   *   id the tracker asserts matches what the PGT spend emits.
   * @param args.additionalVoteAmount     PGT mojos locked by the co-spent
   *   PGT lock spend.  Must be > 0 and equal the PGT coin's amount.
   *
   * @returns Unsigned CoinSpend (hex) ready to bundle with the matching
   *   PGT lock spend.
   */
  buildTrackerVoteCoinSpend(args: BuildTrackerVoteArgs): UnsignedCoinSpendHex {
    const sdk = this.sdk();
    const clvm = this.clvm();
    const Coin = sdk.Coin;

    if (args.additionalVoteAmount <= 0) {
      throw new Error(
        'pgt-vote-spend: additionalVoteAmount must be > 0',
      );
    }
    const voterInnerPh = hexToBytes(this.normalizeHex(args.voterInnerPuzzleHash));
    if (voterInnerPh.length !== 32) {
      throw new Error('pgt-vote-spend: voterInnerPuzzleHash must be 32 bytes');
    }

    // ── 1. Re-derive the singleton-wrapped tracker puzzle ──
    const trackerInner = clvm.deserialize(
      hexToBytes(this.normalizeHex(args.trackerInnerPuzzleHex)),
    );
    const trackerInnerHash = trackerInner.treeHash();
    const trackerStruct = this.buildTrackerStruct(
      clvm,
      hexToBytes(this.normalizeHex(args.trackerLauncherId)),
    );
    const trackerFullPuzzle = this.singletonFullPuzzle(
      clvm,
      trackerStruct,
      trackerInner,
    );
    const expectedFullPh = trackerFullPuzzle.treeHash();
    const claimedPh = hexToBytes(this.normalizeHex(args.trackerCoin.puzzleHash));
    if (!this.bytesEqual(expectedFullPh, claimedPh)) {
      throw new Error(
        `pgt-vote-spend: built tracker full puzzle hash ${bytesToHex(expectedFullPh)} ` +
          `does not match coin's claimed puzzle hash ${bytesToHex(claimedPh)}.`,
      );
    }

    // ── 2. Build the inner solution ──
    //   (my_id my_inner_puzzlehash my_amount TRK_VOTE
    //    (voter_inner_puzhash additional_vote_amount))
    const trackerCoin = new Coin(
      hexToBytes(this.normalizeHex(args.trackerCoin.parentCoinInfo)),
      claimedPh,
      BigInt(args.trackerCoin.amount),
    );
    const myId = trackerCoin.coinId();
    const innerSolution = clvm.list([
      clvm.atom(myId),
      clvm.atom(trackerInnerHash),
      clvm.int(BigInt(args.trackerCoin.amount)),
      clvm.int(BigInt(PgtVoteSpendBuilderService.TRK_VOTE)),
      clvm.list([
        clvm.atom(voterInnerPh),
        clvm.int(BigInt(args.additionalVoteAmount)),
      ]),
    ]);

    // ── 3. Build the singleton outer solution ──
    //   (lineage_proof my_amount inner_solution)
    const lineageProofProgram = this.encodeLineageProof(
      clvm,
      args.lineageProof,
    );
    const outerSolution = clvm.list([
      lineageProofProgram,
      clvm.int(BigInt(args.trackerCoin.amount)),
      innerSolution,
    ]);

    return {
      coin: {
        parentCoinInfo: bytesToHex(trackerCoin.parentCoinInfo),
        puzzleHash: bytesToHex(claimedPh),
        amount: args.trackerCoin.amount,
      },
      puzzleReveal: bytesToHex(trackerFullPuzzle.serialize()),
      solution: bytesToHex(outerSolution.serialize()),
    };
  }

  // ────────────────────────────────────────────────────────────────────
  //  Internals
  // ────────────────────────────────────────────────────────────────────

  private buildTrackerStruct(
    clvm: ClvmShape,
    trackerLauncherId: Uint8Array,
  ): ProgramShape {
    return clvm.pair(
      clvm.atom(hexToBytes(PgtDriverService.SINGLETON_MOD_HASH)),
      clvm.pair(
        clvm.atom(trackerLauncherId),
        clvm.atom(hexToBytes(PgtDriverService.SINGLETON_LAUNCHER_HASH)),
      ),
    );
  }

  private curriedPgtFreeInner(
    clvm: ClvmShape,
    args: {
      trackerStruct: ProgramShape;
      voterInnerPuzzleHash: Uint8Array;
    },
  ): ProgramShape {
    // pgt_free_inner curry order (mirrors pgt_driver.pgt_free_inner_puzzle):
    //   (MOD_HASH LOCKED_MOD_HASH PROPOSAL_TRACKER_STRUCT INNER_PUZZLE_HASH)
    const mod = clvm.deserialize(hexToBytes(PGT_FREE_INNER_MOD_BYTECODE_HEX()));
    return mod.curry([
      clvm.atom(hexToBytes(PgtDriverService.PGT_FREE_INNER_MOD_HASH)),
      clvm.atom(hexToBytes(PgtDriverService.PGT_LOCKED_INNER_MOD_HASH)),
      args.trackerStruct,
      clvm.atom(args.voterInnerPuzzleHash),
    ]);
  }

  private curriedCatMod(
    clvm: ClvmShape,
    args: { pgtTailHash: Uint8Array; innerPuzzle: ProgramShape },
  ): ProgramShape {
    // CAT2 curry order: (MOD_HASH TAIL_HASH INNER_PUZZLE).
    const mod = clvm.deserialize(hexToBytes(CAT_MOD_PUZZLE_HEX));
    return mod.curry([
      clvm.atom(hexToBytes(PgtDriverService.CAT_MOD_HASH)),
      clvm.atom(args.pgtTailHash),
      args.innerPuzzle,
    ]);
  }

  private singletonFullPuzzle(
    clvm: ClvmShape,
    singletonStruct: ProgramShape,
    innerPuzzle: ProgramShape,
  ): ProgramShape {
    const sdk = this.sdk();
    const topLayer =
      sdk.Constants?.singletonTopLayerV11?.() ??
      sdk.Constants?.singletonTopLayer?.();
    if (!topLayer) {
      throw new Error(
        'pgt-vote-spend: chia-wallet-sdk-wasm Constants.singletonTopLayerV11 unavailable',
      );
    }
    return clvm.deserialize(topLayer).curry([singletonStruct, innerPuzzle]);
  }

  private encodeLineageProof(
    clvm: ClvmShape,
    proof: LineageProofShape | undefined,
  ): ProgramShape {
    // chia's LineageProof.to_program() emits:
    //   - empty proof (None,None,None)  →  nil
    //   - eve-only (parent_name=X, inner=None, amount=None)  →  (X)
    //   - full proof (parent_name=X, inner=Y, amount=Z)  →  (X Y Z)
    if (!proof || (!proof.parentName && !proof.innerPuzzleHash && proof.amount === undefined)) {
      return clvm.nil();
    }
    if (proof.parentName && !proof.innerPuzzleHash && proof.amount === undefined) {
      return clvm.list([clvm.atom(hexToBytes(this.normalizeHex(proof.parentName)))]);
    }
    if (!proof.parentName || !proof.innerPuzzleHash || proof.amount === undefined) {
      throw new Error(
        'pgt-vote-spend: lineage proof must be empty, eve-only ' +
          '(parentName only), or fully populated (all 3 fields).',
      );
    }
    return clvm.list([
      clvm.atom(hexToBytes(this.normalizeHex(proof.parentName))),
      clvm.atom(hexToBytes(this.normalizeHex(proof.innerPuzzleHash))),
      clvm.int(BigInt(proof.amount)),
    ]);
  }

  private normalizeHex(value: string): string {
    return value.startsWith('0x') || value.startsWith('0X') ? value : '0x' + value;
  }

  private bytesEqual(a: Uint8Array, b: Uint8Array): boolean {
    if (a.length !== b.length) return false;
    for (let i = 0; i < a.length; i++) if (a[i] !== b[i]) return false;
    return true;
  }

  private sdk(): VoteSdkShape {
    const sdk = this.wasm.sdk() as VoteSdkShape;
    if (!sdk?.Clvm || !sdk?.Coin) {
      throw new Error('pgt-vote-spend: chia-wallet-sdk-wasm Clvm/Coin exports unavailable');
    }
    return sdk;
  }

  private clvm(): ClvmShape {
    return new (this.sdk().Clvm)();
  }
}

// pgt_free_inner.clsp bytecode — re-exported via a getter so the import
// works regardless of TS module resolution order in tests.
function PGT_FREE_INNER_MOD_BYTECODE_HEX(): string {
  // Lazy require to avoid a circular import with pgt-driver service helpers.
  // eslint-disable-next-line @typescript-eslint/no-var-requires
  const { PGT_FREE_INNER_PUZZLE_HEX } = require('./pgt-free-inner.puzzle-hex');
  return PGT_FREE_INNER_PUZZLE_HEX;
}

// ──────────────────────────────────────────────────────────────────────
//  Shapes
// ──────────────────────────────────────────────────────────────────────

/**
 * Lineage proof as the chia CAT2 outer / singleton inner expects.
 *
 * Chia's ``LineageProof.to_program()`` accepts three shapes:
 *
 *   * empty:    all fields undefined  →  nil      (eve issuance from XCH)
 *   * eve-only: only ``parentName``   →  (parent) (eve singleton from launcher)
 *   * full:     all three fields      →  (parent, inner_hash, amount)
 *                                        (regular subsequent spend)
 */
export interface LineageProofShape {
  parentName?: string;
  innerPuzzleHash?: string;
  amount?: number | bigint;
}

export interface CoinHexShape {
  parentCoinInfo: string;
  puzzleHash: string;
  amount: number | bigint;
}

export interface UnsignedCoinSpendHex {
  coin: { parentCoinInfo: string; puzzleHash: string; amount: number | bigint };
  puzzleReveal: string;
  solution: string;
}

export interface BuildPgtLockArgs {
  pgtCoin: CoinHexShape;
  voterInnerPuzzleHex: string;
  voterInnerSolutionHex: string;
  trackerLauncherId: string;
  pgtTailHash: string;
  lineageProof: LineageProofShape;
  proposalHash: string;
  deadlineSeconds: number | bigint;
}

export interface BuildTrackerVoteArgs {
  trackerCoin: CoinHexShape;
  trackerInnerPuzzleHex: string;
  trackerLauncherId: string;
  lineageProof: LineageProofShape;
  voterInnerPuzzleHash: string;
  additionalVoteAmount: number | bigint;
}

// ── WASM SDK typing ──────────────────────────────────────────────────
interface ProgramShape {
  treeHash(): Uint8Array;
  serialize(): Uint8Array;
  curry(args: ProgramShape[]): ProgramShape;
}
interface ClvmShape {
  deserialize(bytes: Uint8Array): ProgramShape;
  atom(value: Uint8Array): ProgramShape;
  int(value: bigint): ProgramShape;
  list(value: ProgramShape[]): ProgramShape;
  pair(first: ProgramShape, rest: ProgramShape): ProgramShape;
  nil(): ProgramShape;
}
interface CoinClass {
  new (parentCoinInfo: Uint8Array, puzzleHash: Uint8Array, amount: bigint): {
    parentCoinInfo: Uint8Array;
    puzzleHash: Uint8Array;
    amount: bigint;
    coinId(): Uint8Array;
  };
}
interface VoteSdkShape {
  Clvm: new () => ClvmShape;
  Coin: CoinClass;
  Constants?: {
    singletonTopLayerV11?: () => Uint8Array;
    singletonTopLayer?: () => Uint8Array;
  };
}
