export const A5_ROSTER_UPDATE_AUTHORIZATION_MODEL = {
  spendName: 'ADMIN_ROSTER_UPDATE',
  spendTag: 0x07,
  authorizer: 'current_admin_authority_v2_mips_quorum',
  forbiddenAuthorizers: [
    'candidate_admin_wallet',
    'populis_api_backend',
    'pgt_committee_vote',
    'bootstrap_operator_token',
  ],
  updateRule: 'append_exactly_one_admin_slot',
  thresholdRule: 'supermajority_threshold_over_updated_roster',
  backendRole: 'optional_cross_check_only',
  localReviewGate: 'verify_signer_input_hashes_without_mips_execution',
  verifiedSignerInputs: [
    'current_mips_puzzle_reveal_tree_hash',
    'current_mips_quorum_solution_serialized_clvm_parse_only',
    'current_admin_authority_v2_inner_puzzle_reveal_tree_hash',
    'live_singleton_coin_metadata_and_puzzle_hash',
  ],
  forbiddenReviewActions: [
    'execute_mips',
    'construct_clvm_spends',
    'collect_wallet_signature',
    'sign',
    'broadcast',
    'call_backend',
  ],
  signerBoundary: 'no_signing_no_broadcast_until_local_signer_inputs_are_hash_verified',
} as const;

export const A5_ROSTER_UPDATE_SPEND_BUILDER_INTAKE_CONTRACT = {
  boundary: 'normalize_and_reverify_inputs_without_spend_construction',
  result: 'verified_intake_only_no_signed_bundle',
  requiredInputs: [
    'local_unsigned_spend_blueprint',
    'local_verification_report',
    'raw_current_mips_puzzle_reveal',
    'raw_current_mips_quorum_solution',
    'raw_current_admin_authority_v2_inner_puzzle_reveal',
    'live_singleton_coin_metadata',
  ],
  requiredRechecks: [
    'blueprint_matches_verification_report',
    'raw_reveals_match_verified_commitment_hashes',
    'live_singleton_coin_id_matches_parent_puzzle_hash_amount',
    'current_inner_puzzle_hash_matches_current_state_commitment',
    'singleton_full_puzzle_hash_matches_live_coin_puzzle_hash',
  ],
  allowedOutputs: [
    'normalized_spend_builder_intake',
    'deterministic_commitment_summary',
    'unsigned_construction_plan',
  ],
  forbiddenActions: [
    'execute_mips',
    'construct_clvm_spends',
    'collect_wallet_signature',
    'sign',
    'broadcast',
    'call_backend',
  ],
  forbiddenMaterial: [
    'wallet_signature',
    'signed_spend_bundle',
    'api_credentials',
    'jwt',
    'nonce',
    'secret',
  ],
} as const;

export const A5_ROSTER_UPDATE_UNSIGNED_CLVM_CONSTRUCTION_CONTRACT = {
  boundary: 'derive_unsigned_clvm_construction_plan_without_coin_spend_serialization',
  result: 'unsigned_clvm_construction_plan_only_no_coin_spends',
  requiredInputs: [
    'verified_spend_builder_intake',
    'raw_current_mips_puzzle_reveal',
    'raw_current_mips_quorum_solution',
    'raw_current_admin_authority_v2_inner_puzzle_reveal',
    'live_singleton_coin_metadata',
  ],
  requiredRechecks: [
    'verified_intake_result_is_verified_intake_only_no_signed_bundle',
    'raw_material_hashes_match_verified_intake_commitments',
    'live_singleton_coin_matches_verified_intake',
    'current_state_commitments_match_verified_intake',
    'singleton_full_puzzle_hash_matches_live_coin_puzzle_hash',
  ],
  allowedOutputs: [
    'unsigned_admin_authority_v2_spend_shape',
    'unsigned_mips_spend_shape',
    'expected_conditions_summary',
    'deterministic_unsigned_construction_summary',
  ],
  forbiddenActions: [
    'execute_mips',
    'serialize_coin_spends',
    'collect_wallet_signature',
    'sign',
    'broadcast',
    'call_backend',
  ],
  forbiddenMaterial: [
    'raw_reveal_bytes_in_output',
    'wallet_signature',
    'signed_spend_bundle',
    'api_credentials',
    'jwt',
    'nonce',
    'secret',
  ],
} as const;

export const A5_ROSTER_UPDATE_AUTHORIZATION_TEXT = [
  'A.5 roster updates are admin_authority_v2 singleton spends with SPEND_ADMIN_ROSTER_UPDATE = 0x07 and spend_name ADMIN_ROSTER_UPDATE.',
  'The only protocol authorizer for this A.5 add-admin path is the current admin_authority_v2 MIPS quorum committed in current.mips_root_hash.',
  'The candidate admin wallet does not authorize its own addition.',
  'The Populis API backend is optional cross-check infrastructure only and is not an authority source for roster changes.',
  'PGT committee approval is not part of this A.5 add-admin path unless a future governance design explicitly adds a separate spend path.',
  'The bootstrap operator token cannot authorize post-genesis roster updates.',
  'Each A.5 roster update appends exactly one admin slot, preserves existing admin records as a prefix, preserves pending_ops_hash, and increments authority_version by one.',
  'The post-update MIPS root is recomputed from the updated roster using the admin supermajority threshold.',
  'The review screen locally verifies signer input hashes before any future spend builder: current MIPS puzzle reveal tree hash must match current.mips_root_hash, the current MIPS quorum solution must parse as serialized CLVM without being executed, the current admin_authority_v2 inner puzzle reveal tree hash must match the recomputed current inner puzzle hash, and live singleton coin metadata plus puzzle hash must match the package.',
  'The unsigned package and review screen remain no-signing and no-broadcast boundaries until current MIPS puzzle reveal, current MIPS quorum solution, live singleton coin, and wallet spend-bundle signature inputs are supplied and hash-verified.',
  'Local hash verification does not execute MIPS, construct CLVM spends, collect wallet signatures, sign, broadcast, or call the backend.',
  'The spend-builder intake boundary may normalize and reverify the local unsigned spend blueprint, local verification report, raw current MIPS puzzle reveal, raw current MIPS quorum solution, raw current admin_authority_v2 inner puzzle reveal, and live singleton coin metadata.',
  'Spend-builder intake must recheck that blueprint commitments match the verification report, raw reveals match verified commitment hashes, the live singleton coin id matches parent puzzle hash and amount, the current inner puzzle hash matches the current state commitment, and the singleton full puzzle hash matches the live coin puzzle hash.',
  'Spend-builder intake may only output a normalized intake, deterministic commitment summary, or unsigned construction plan; it must not execute MIPS, construct CLVM spends, collect wallet signatures, sign, broadcast, call the backend, or include wallet signatures, signed spend bundles, API credentials, JWTs, nonces, or secrets.',
  'The unsigned CLVM construction boundary may derive unsigned admin_authority_v2 and MIPS spend shapes, expected conditions, and a deterministic unsigned construction summary from a verified spend-builder intake without serializing coin spends.',
  'Unsigned CLVM construction must recheck that the verified intake result is verified_intake_only_no_signed_bundle, raw material hashes match verified intake commitments, live singleton coin metadata matches the verified intake, current state commitments match the verified intake, and the singleton full puzzle hash matches the live coin puzzle hash.',
  'Unsigned CLVM construction must not execute MIPS, serialize coin spends, collect wallet signatures, sign, broadcast, call the backend, output raw reveal bytes, or include wallet signatures, signed spend bundles, API credentials, JWTs, nonces, or secrets.',
] as const;
