export const A5_ROSTER_UPDATE_AUTHORIZATION_MODEL = {
  spendName: 'ADMIN_ROSTER_UPDATE',
  spendTag: 0x07,
  authorizer: 'current_admin_authority_v2_mips_quorum',
  forbiddenAuthorizers: [
    'candidate_admin_wallet',
    'populis_api_backend',
    'pgt_committee_vote',
    'bootstrap_operator_token',
  ],
  updateRule: 'append_exactly_one_admin_slot',
  thresholdRule: 'supermajority_threshold_over_updated_roster',
  backendRole: 'optional_cross_check_only',
  localReviewGate: 'verify_signer_input_hashes_without_mips_execution',
  verifiedSignerInputs: [
    'current_mips_puzzle_reveal_tree_hash',
    'current_mips_quorum_solution_serialized_clvm_parse_only',
    'current_admin_authority_v2_inner_puzzle_reveal_tree_hash',
    'live_singleton_coin_metadata_and_puzzle_hash',
  ],
  forbiddenReviewActions: [
    'execute_mips',
    'construct_clvm_spends',
    'collect_wallet_signature',
    'sign',
    'broadcast',
    'call_backend',
  ],
  signerBoundary: 'no_signing_no_broadcast_until_local_signer_inputs_are_hash_verified',
} as const;

export const A5_ROSTER_UPDATE_SPEND_BUILDER_INTAKE_CONTRACT = {
  boundary: 'normalize_and_reverify_inputs_without_spend_construction',
  result: 'verified_intake_only_no_signed_bundle',
  requiredInputs: [
    'local_unsigned_spend_blueprint',
    'local_verification_report',
    'raw_current_mips_puzzle_reveal',
    'raw_current_mips_quorum_solution',
    'raw_current_admin_authority_v2_inner_puzzle_reveal',
    'live_singleton_coin_metadata',
  ],
  requiredRechecks: [
    'blueprint_matches_verification_report',
    'raw_reveals_match_verified_commitment_hashes',
    'live_singleton_coin_id_matches_parent_puzzle_hash_amount',
    'current_inner_puzzle_hash_matches_current_state_commitment',
    'singleton_full_puzzle_hash_matches_live_coin_puzzle_hash',
  ],
  allowedOutputs: [
    'normalized_spend_builder_intake',
    'deterministic_commitment_summary',
    'unsigned_construction_plan',
  ],
  forbiddenActions: [
    'execute_mips',
    'construct_clvm_spends',
    'collect_wallet_signature',
    'sign',
    'broadcast',
    'call_backend',
  ],
  forbiddenMaterial: [
    'wallet_signature',
    'signed_spend_bundle',
    'api_credentials',
    'jwt',
    'nonce',
    'secret',
  ],
} as const;

export const A5_ROSTER_UPDATE_UNSIGNED_CLVM_CONSTRUCTION_CONTRACT = {
  boundary: 'derive_unsigned_clvm_construction_plan_without_coin_spend_serialization',
  result: 'unsigned_clvm_construction_plan_only_no_coin_spends',
  requiredInputs: [
    'verified_spend_builder_intake',
    'raw_current_mips_puzzle_reveal',
    'raw_current_mips_quorum_solution',
    'raw_current_admin_authority_v2_inner_puzzle_reveal',
    'live_singleton_coin_metadata',
  ],
  requiredRechecks: [
    'verified_intake_result_is_verified_intake_only_no_signed_bundle',
    'raw_material_hashes_match_verified_intake_commitments',
    'live_singleton_coin_matches_verified_intake',
    'current_state_commitments_match_verified_intake',
    'singleton_full_puzzle_hash_matches_live_coin_puzzle_hash',
  ],
  allowedOutputs: [
    'unsigned_admin_authority_v2_spend_shape',
    'unsigned_mips_spend_shape',
    'expected_conditions_summary',
    'deterministic_unsigned_construction_summary',
  ],
  forbiddenActions: [
    'execute_mips',
    'serialize_coin_spends',
    'collect_wallet_signature',
    'sign',
    'broadcast',
    'call_backend',
  ],
  forbiddenMaterial: [
    'raw_reveal_bytes_in_output',
    'wallet_signature',
    'signed_spend_bundle',
    'api_credentials',
    'jwt',
    'nonce',
    'secret',
  ],
} as const;

export const A5_ROSTER_UPDATE_MIPS_EXECUTION_COIN_SPEND_CONTRACT = {
  boundary: 'execute_mips_and_serialize_unsigned_coin_spends_without_signing_or_broadcast',
  result: 'unsigned_coin_spend_candidate_only_no_signatures',
  requiredInputs: [
    'unsigned_clvm_construction_plan',
    'verified_spend_builder_intake',
    'raw_current_mips_puzzle_reveal',
    'raw_current_mips_quorum_solution',
    'raw_current_admin_authority_v2_inner_puzzle_reveal',
    'live_singleton_coin_metadata',
    'current_admin_records',
    'current_pending_ops',
    'new_admin_record',
    'singleton_lineage_proof',
  ],
  requiredRechecks: [
    'unsigned_clvm_plan_result_is_unsigned_clvm_construction_plan_only_no_coin_spends',
    'verified_intake_result_is_verified_intake_only_no_signed_bundle',
    'raw_material_hashes_match_plan_and_intake_commitments',
    'admin_and_pending_records_hash_to_committed_state',
    'singleton_lineage_proof_is_supplied_for_unsigned_coin_spend_solution',
    'mips_execution_cost_within_limit',
    'mips_execution_conditions_match_expected_roster_update',
    'serialized_unsigned_coin_spends_match_plan_shapes',
    'serialized_unsigned_coin_spends_contain_no_signatures',
  ],
  allowedMaterial: [
    'raw_reveal_bytes_inside_unsigned_coin_spend_puzzle_reveal_only',
    'raw_solution_bytes_inside_unsigned_coin_spend_solution_only',
  ],
  allowedOutputs: [
    'bounded_mips_execution_report',
    'unsigned_admin_authority_v2_coin_spend',
    'embedded_mips_authorization_payload',
    'unsigned_spend_bundle_candidate',
    'deterministic_pre_signing_review',
  ],
  forbiddenActions: [
    'collect_wallet_signature',
    'sign',
    'broadcast',
    'call_backend_as_roster_authority',
  ],
  forbiddenMaterial: [
    'wallet_signature',
    'aggregated_signature',
    'signed_spend_bundle',
    'api_credentials',
    'jwt',
    'nonce',
    'secret',
    'private_key',
  ],
} as const;

export const A5_ROSTER_UPDATE_WALLET_SIGNATURE_COLLECTION_CONTRACT = {
  boundary: 'collect_wallet_signature_for_unsigned_spend_bundle_without_broadcast',
  result: 'signed_spend_bundle_candidate_not_broadcast',
  requiredInputs: [
    'unsigned_coin_spend_candidate',
    'unsigned_spend_bundle_candidate',
    'deterministic_pre_signing_review',
    'wallet_signature_provider',
  ],
  requiredRechecks: [
    'unsigned_candidate_result_is_unsigned_coin_spend_candidate_only_no_signatures',
    'unsigned_spend_bundle_candidate_contains_expected_coin_spends',
    'coin_spend_bytes_match_pre_signing_candidate',
    'deterministic_pre_signing_review_matches_unsigned_candidate',
    'no_existing_signatures_or_signed_bundle_are_supplied',
    'wallet_signature_is_collected_over_final_spend_bundle_only',
  ],
  allowedMaterial: [
    'wallet_signature',
    'aggregated_signature',
  ],
  allowedOutputs: [
    'signed_spend_bundle_candidate',
    'wallet_signature_summary',
    'deterministic_post_signing_review',
  ],
  forbiddenActions: [
    'broadcast',
    'call_backend_as_roster_authority',
    'mutate_coin_spends',
    'recompute_roster_transition',
  ],
  forbiddenMaterial: [
    'private_key',
    'mnemonic',
    'api_credentials',
    'jwt',
    'nonce',
    'secret',
    'backend_authority_attestation',
  ],
} as const;

export const A5_ROSTER_UPDATE_SIGNED_BUNDLE_BROADCAST_CONTRACT = {
  boundary: 'push_signed_spend_bundle_after_operator_confirmation',
  result: 'submitted_spend_bundle_push_result_not_confirmation',
  requiredInputs: [
    'signed_spend_bundle_candidate',
    'deterministic_post_signing_review',
    'operator_broadcast_confirmation',
    'coinset_push_transaction_client',
  ],
  requiredRechecks: [
    'signed_candidate_result_is_signed_spend_bundle_candidate_not_broadcast',
    'signed_spend_bundle_contains_expected_coin_spends',
    'aggregated_signature_is_present_and_96_bytes',
    'deterministic_post_signing_review_matches_signed_candidate',
    'operator_confirms_broadcast_intent_and_network',
    'no_private_keys_wallet_provider_or_backend_authority_material_are_supplied',
    'push_response_is_recorded_without_claiming_chain_confirmation',
  ],
  allowedMaterial: [
    'signed_spend_bundle_candidate',
    'aggregated_signature',
    'push_transaction_response',
  ],
  allowedOutputs: [
    'broadcast_submission_record',
    'push_transaction_response',
    'post_broadcast_monitoring_hints',
  ],
  forbiddenActions: [
    'collect_wallet_signature',
    'sign',
    'mutate_coin_spends',
    'recompute_roster_transition',
    'call_backend_as_roster_authority',
    'claim_chain_confirmation',
  ],
  forbiddenMaterial: [
    'private_key',
    'mnemonic',
    'wallet_signature_provider',
    'api_credentials',
    'jwt',
    'nonce',
    'secret',
    'backend_authority_attestation',
  ],
} as const;

export const A5_ROSTER_UPDATE_AUTHORIZATION_TEXT = [
  'A.5 roster updates are admin_authority_v2 singleton spends with SPEND_ADMIN_ROSTER_UPDATE = 0x07 and spend_name ADMIN_ROSTER_UPDATE.',
  'The only protocol authorizer for this A.5 add-admin path is the current admin_authority_v2 MIPS quorum committed in current.mips_root_hash.',
  'The candidate admin wallet does not authorize its own addition.',
  'The Populis API backend is optional cross-check infrastructure only and is not an authority source for roster changes.',
  'PGT committee approval is not part of this A.5 add-admin path unless a future governance design explicitly adds a separate spend path.',
  'The bootstrap operator token cannot authorize post-genesis roster updates.',
  'Each A.5 roster update appends exactly one admin slot, preserves existing admin records as a prefix, preserves pending_ops_hash, and increments authority_version by one.',
  'The post-update MIPS root is recomputed from the updated roster using the admin supermajority threshold.',
  'The review screen locally verifies signer input hashes before any future spend builder: current MIPS puzzle reveal tree hash must match current.mips_root_hash, the current MIPS quorum solution must parse as serialized CLVM without being executed, the current admin_authority_v2 inner puzzle reveal tree hash must match the recomputed current inner puzzle hash, and live singleton coin metadata plus puzzle hash must match the package.',
  'The unsigned package and review screen remain no-signing and no-broadcast boundaries until current MIPS puzzle reveal, current MIPS quorum solution, live singleton coin, and wallet spend-bundle signature inputs are supplied and hash-verified.',
  'Local hash verification does not execute MIPS, construct CLVM spends, collect wallet signatures, sign, broadcast, or call the backend.',
  'The spend-builder intake boundary may normalize and reverify the local unsigned spend blueprint, local verification report, raw current MIPS puzzle reveal, raw current MIPS quorum solution, raw current admin_authority_v2 inner puzzle reveal, and live singleton coin metadata.',
  'Spend-builder intake must recheck that blueprint commitments match the verification report, raw reveals match verified commitment hashes, the live singleton coin id matches parent puzzle hash and amount, the current inner puzzle hash matches the current state commitment, and the singleton full puzzle hash matches the live coin puzzle hash.',
  'Spend-builder intake may only output a normalized intake, deterministic commitment summary, or unsigned construction plan; it must not execute MIPS, construct CLVM spends, collect wallet signatures, sign, broadcast, call the backend, or include wallet signatures, signed spend bundles, API credentials, JWTs, nonces, or secrets.',
  'The unsigned CLVM construction boundary may derive unsigned admin_authority_v2 and MIPS spend shapes, expected conditions, and a deterministic unsigned construction summary from a verified spend-builder intake without serializing coin spends.',
  'Unsigned CLVM construction must recheck that the verified intake result is verified_intake_only_no_signed_bundle, raw material hashes match verified intake commitments, live singleton coin metadata matches the verified intake, current state commitments match the verified intake, and the singleton full puzzle hash matches the live coin puzzle hash.',
  'Unsigned CLVM construction must not execute MIPS, serialize coin spends, collect wallet signatures, sign, broadcast, call the backend, output raw reveal bytes, or include wallet signatures, signed spend bundles, API credentials, JWTs, nonces, or secrets.',
  'The MIPS execution and unsigned CoinSpend serialization boundary may execute the current MIPS authorization path under explicit cost limits and serialize an unsigned admin_authority_v2 CoinSpend candidate from the unsigned CLVM construction plan.',
  'MIPS execution and unsigned CoinSpend serialization must recheck that the unsigned CLVM plan result is unsigned_clvm_construction_plan_only_no_coin_spends, the verified intake result is verified_intake_only_no_signed_bundle, raw material hashes match plan and intake commitments, full admin records plus pending ops hash to the committed state, singleton lineage proof is supplied, MIPS execution cost is within limit, execution conditions match the expected roster update, and serialized unsigned CoinSpends match the planned shapes without signatures.',
  'Raw reveal and solution bytes may appear only inside unsigned CoinSpend puzzle_reveal and solution fields at this boundary.',
  'MIPS execution and unsigned CoinSpend serialization must not collect wallet signatures, sign, broadcast, treat the backend as roster authority, or include wallet signatures, aggregated signatures, signed spend bundles, API credentials, JWTs, nonces, secrets, or private keys.',
  'The wallet signature collection boundary may collect a wallet signature for an already-reviewed unsigned_spend_bundle_candidate and output a signed_spend_bundle_candidate_not_broadcast.',
  'Wallet signature collection must recheck that the unsigned candidate result is unsigned_coin_spend_candidate_only_no_signatures, the unsigned spend bundle candidate contains the expected CoinSpends, CoinSpend bytes match the pre-signing candidate, deterministic pre-signing review data still matches, no existing signatures or signed bundle were supplied, and the wallet signs only the final spend bundle.',
  'Wallet signature collection must not broadcast, call the backend as roster authority, mutate CoinSpends, recompute the roster transition, or include private keys, mnemonics, API credentials, JWTs, nonces, secrets, or backend authority attestations.',
  'The signed-bundle broadcast boundary may push an already-signed signed_spend_bundle_candidate only after explicit operator broadcast confirmation and must output a submitted_spend_bundle_push_result_not_confirmation.',
  'Signed-bundle broadcast must recheck that the signed candidate result is signed_spend_bundle_candidate_not_broadcast, the signed spend bundle contains the expected CoinSpends, the aggregated signature is present and 96 bytes, deterministic post-signing review data still matches, the operator confirms broadcast intent and network, no private keys, wallet provider, or backend authority material are supplied, and the push response is recorded without claiming chain confirmation.',
  'Signed-bundle broadcast may call a transaction relay such as coinset push_transaction, but relay acceptance is not roster authority and is not chain confirmation.',
  'Signed-bundle broadcast must not collect wallet signatures, sign, mutate CoinSpends, recompute the roster transition, call the backend as roster authority, claim chain confirmation, or include private keys, mnemonics, wallet signature providers, API credentials, JWTs, nonces, secrets, or backend authority attestations.',
] as const;
