/**
 * Cross-repo binding test for the TS new-vault launch builder (Brick 6a).
 *
 * The fixture ``vault-launch.fixtures.json`` is generated by
 * ``populis_protocol/scripts/dump_vault_launch_fixtures.py`` and pinned by
 * ``tests/test_vault_launch_fixtures.py``.  Each section asserts the TS
 * port produces byte-identical hex to ``vault_driver.py``.
 *
 * **If a test here fails:**
 *   1. The TS implementation in ``vault-launch-spend.service.ts`` drifted
 *      from the Python source of truth — diff the offending case.
 *   2. OR the Python source changed and the fixture wasn't regenerated.
 *      Re-run ``python scripts/dump_vault_launch_fixtures.py`` and re-test.
 */
import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting } from '@angular/common/http/testing';

import { ChiaWasmService } from './chia-wasm.service';
import {
  CanonicalVaultParams,
  SINGLETON_LAUNCHER_HASH,
  VaultIdentity,
  VaultLaunchSpendService,
} from './vault-launch-spend.service';
import { hexToBytes } from '../utils/chia-hash';
import fixturesJson from './vault-launch.fixtures.json';

interface ParseExpected {
  identity: VaultIdentity;
  params: CanonicalVaultParams;
  vaultInnerModHash: string;
  canonicalParamsHash: string;
}

interface LaunchExpected {
  launcherId: string;
  launcherCoin: { parentCoinInfo: string; puzzleHash: string; amount: number };
  vaultInnerPuzzleHash: string;
  vaultFullPuzzleHash: string;
  eveCoin: { parentCoinInfo: string; puzzleHash: string; amount: number };
  launcherAnnouncementMessage: string;
  launcherAnnouncementId: string;
}

interface FixtureFile {
  constants: {
    vault_inner_mod_hash: string;
    singleton_mod_hash: string;
    singleton_launcher_hash: string;
    canonical_params_hash: string;
  };
  identity: VaultIdentity;
  params: CanonicalVaultParams;
  parse_vault: { label: string; input: { full_puzzle_reveal: string }; expected: ParseExpected }[];
  vault_inner_puzzle_hash: { label: string; input: { launcher_id: string }; expected: string }[];
  vault_full_puzzle_hash: { label: string; input: { launcher_id: string }; expected: string }[];
  launch_outputs: { label: string; input: { parent_coin_id: string }; expected: LaunchExpected }[];
}

const fixtures = fixturesJson as FixtureFile;

describe('VaultLaunchSpendService', () => {
  let service: VaultLaunchSpendService;
  let wasmService: ChiaWasmService;

  beforeAll(async () => {
    // Mirror the admin-authority-v2 spec's WASM bootstrap: deep-import the
    // glue, fetch the .wasm asset Karma serves, hand-instantiate once per
    // session, and stash on window.ChiaSDK for ChiaWasmService.probeReady().
    if ((window as unknown as { ChiaSDK?: unknown }).ChiaSDK) {
      return;
    }
    // @ts-ignore — deep-import path; types from chia_wallet_sdk_wasm.d.ts.
    const wasmExports = await import('chia-wallet-sdk-wasm/chia_wallet_sdk_wasm_bg.js');
    const response = await fetch('/assets/chia_wasm/chia_wallet_sdk_wasm_bg.wasm');
    if (!response.ok) {
      throw new Error(
        `WASM asset fetch failed: ${response.status} ${response.statusText}. ` +
          'Karma must serve src/assets/chia_wasm at /assets/chia_wasm.',
      );
    }
    const bytes = await response.arrayBuffer();
    const result = await WebAssembly.instantiate(bytes, {
      './chia_wallet_sdk_wasm_bg.js': wasmExports as unknown as WebAssembly.ModuleImports,
    });
    const setWasm = (wasmExports as unknown as { __wbg_set_wasm?: (w: WebAssembly.Exports) => void })
      .__wbg_set_wasm;
    if (typeof setWasm !== 'function') {
      throw new Error('chia_wallet_sdk_wasm_bg.js missing __wbg_set_wasm');
    }
    setWasm(result.instance.exports);
    (window as unknown as { ChiaSDK: unknown }).ChiaSDK = wasmExports;
  });

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [provideHttpClient(), provideHttpClientTesting()],
    });
    wasmService = TestBed.inject(ChiaWasmService);
    wasmService.probeReady();
    service = TestBed.inject(VaultLaunchSpendService);
  });

  // ── constants ────────────────────────────────────────────────────────
  it('embeds the canonical singleton constants', () => {
    expect(SINGLETON_LAUNCHER_HASH).toBe(fixtures.constants.singleton_launcher_hash);
  });

  // ── parseVault ───────────────────────────────────────────────────────
  describe('parseVault', () => {
    fixtures.parse_vault.forEach((c) => {
      it(`recovers identity + params for "${c.label}"`, () => {
        const sdk = wasmService.sdk() as { Clvm: new () => never };
        const clvm = new sdk.Clvm() as never;
        const parsed = service.parseVault(clvm, hexToBytes(c.input.full_puzzle_reveal));
        expect(parsed.identity).toEqual(c.expected.identity);
        expect(parsed.params).toEqual(c.expected.params);
        expect(parsed.vaultInnerModHash).toBe(c.expected.vaultInnerModHash);
        expect(parsed.canonicalParamsHash).toBe(c.expected.canonicalParamsHash);
      });
    });
  });

  // ── vaultInnerPuzzleHash ─────────────────────────────────────────────
  describe('vaultInnerPuzzleHash', () => {
    fixtures.vault_inner_puzzle_hash.forEach((c) => {
      it(`matches puzzle_for_vault_inner for "${c.label}"`, () => {
        const got = service.vaultInnerPuzzleHash(
          c.input.launcher_id,
          fixtures.identity,
          fixtures.params,
        );
        expect(got).withContext(c.label).toBe(c.expected);
      });
    });
  });

  // ── vaultFullPuzzleHash ──────────────────────────────────────────────
  describe('vaultFullPuzzleHash', () => {
    fixtures.vault_full_puzzle_hash.forEach((c) => {
      it(`matches puzzle_for_vault_full for "${c.label}"`, () => {
        const got = service.vaultFullPuzzleHash(
          c.input.launcher_id,
          fixtures.identity,
          fixtures.params,
        );
        expect(got).withContext(c.label).toBe(c.expected);
      });
    });
  });

  // ── computeLaunchOutputs ─────────────────────────────────────────────
  describe('computeLaunchOutputs', () => {
    fixtures.launch_outputs.forEach((c) => {
      it(`matches the Python launch outputs for "${c.label}"`, () => {
        const out = service.computeLaunchOutputs({
          parentCoinId: c.input.parent_coin_id,
          identity: fixtures.identity,
          params: fixtures.params,
        });
        expect(out.launcherId).withContext('launcherId').toBe(c.expected.launcherId);
        expect(out.launcherCoin.parentCoinInfo).toBe(c.expected.launcherCoin.parentCoinInfo);
        expect(out.launcherCoin.puzzleHash).toBe(c.expected.launcherCoin.puzzleHash);
        expect(Number(out.launcherCoin.amount)).toBe(c.expected.launcherCoin.amount);
        expect(out.vaultInnerPuzzleHash).toBe(c.expected.vaultInnerPuzzleHash);
        expect(out.vaultFullPuzzleHash).toBe(c.expected.vaultFullPuzzleHash);
        expect(out.eveCoin.parentCoinInfo).toBe(c.expected.eveCoin.parentCoinInfo);
        expect(out.eveCoin.puzzleHash).toBe(c.expected.eveCoin.puzzleHash);
        expect(Number(out.eveCoin.amount)).toBe(c.expected.eveCoin.amount);
        expect(out.launcherAnnouncementMessage).toBe(c.expected.launcherAnnouncementMessage);
        expect(out.launcherAnnouncementId).toBe(c.expected.launcherAnnouncementId);
      });
    });
  });

  // ── buildLauncherCoinSpend ───────────────────────────────────────────
  describe('buildLauncherCoinSpend', () => {
    it('shapes the launcher CoinSpend with the launcher hash + 1 mojo', () => {
      const parent = fixtures.launch_outputs[0].input.parent_coin_id;
      const eveFullPh = fixtures.launch_outputs[0].expected.vaultFullPuzzleHash;
      const spend = service.buildLauncherCoinSpend({
        parentCoinId: parent,
        eveFullPuzzleHash: eveFullPh,
      });
      expect(spend.coin.parentCoinInfo).toBe(parent);
      expect(spend.coin.puzzleHash).toBe(SINGLETON_LAUNCHER_HASH);
      expect(spend.coin.amount).toBe(1n);
      expect(spend.puzzleReveal.startsWith('0x')).toBe(true);
      expect(spend.puzzleReveal.length).toBeGreaterThan(10);
      expect(spend.solution.startsWith('0x')).toBe(true);
    });
  });

  // ── assertMatchesRegistry ────────────────────────────────────────────
  describe('assertMatchesRegistry', () => {
    it('passes when local code + params match the registry', () => {
      expect(() =>
        service.assertMatchesRegistry({
          params: fixtures.params,
          registryVaultInnerModHash: fixtures.constants.vault_inner_mod_hash,
          registryCanonicalParamsHash: fixtures.constants.canonical_params_hash,
        }),
      ).not.toThrow();
    });

    it('throws when the registry advertises a different vault code', () => {
      expect(() =>
        service.assertMatchesRegistry({
          params: fixtures.params,
          registryVaultInnerModHash: '0x' + '99'.repeat(32),
          registryCanonicalParamsHash: fixtures.constants.canonical_params_hash,
        }),
      ).toThrowError(/vault code mod hash does not match/);
    });

    it('throws when the registry advertises different canonical params', () => {
      expect(() =>
        service.assertMatchesRegistry({
          params: fixtures.params,
          registryVaultInnerModHash: fixtures.constants.vault_inner_mod_hash,
          registryCanonicalParamsHash: '0x' + '88'.repeat(32),
        }),
      ).toThrowError(/canonical params hash does not match/);
    });
  });
});
