/**
 * Cross-repo binding test for the TS deed-migrate co-spend builder (Brick 6b).
 *
 * The fixture ``vault-migrate.fixtures.json`` is generated by
 * ``populis_protocol/scripts/dump_vault_migrate_fixtures.py`` and pinned by
 * ``tests/test_vault_migrate_fixtures.py``.  Each section asserts the TS port
 * produces byte-identical hex to ``vault_driver.py`` +
 * ``tests/test_vault.py::TestVaultBLSMigrate``.
 */
import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting } from '@angular/common/http/testing';

import { ChiaWasmService } from './chia-wasm.service';
import { CanonicalVaultParams, VaultIdentity } from './vault-launch-spend.service';
import {
  SPEND_MIGRATE,
  SingletonLineageProof,
  VaultMigrateSpendService,
} from './vault-migrate-spend.service';
import fixturesJson from './vault-migrate.fixtures.json';

interface CoinFixture {
  parentCoinInfo: string;
  puzzleHash: string;
  amount: number;
}

interface LineageFixture {
  parentParentCoinInfo: string;
  parentInnerPuzzleHash: string;
  parentAmount: number;
}

interface FixtureFile {
  constants: {
    p2_vault_mod_hash: string;
    spend_migrate: number;
    singleton_mod_hash: string;
    singleton_launcher_hash: string;
  };
  identity: VaultIdentity;
  params: CanonicalVaultParams;
  migrate_signing_tree: {
    label: string;
    input: { deed_launcher_id: string; new_p2_vault_puzzlehash: string; vault_coin_id: string };
    expected: string;
  }[];
  new_p2_vault_puzzle_hash: {
    label: string;
    input: { vault_launcher_id: string };
    expected: string;
  }[];
  vault_migrate_spend: {
    label: string;
    input: {
      old_vault_launcher_id: string;
      vault_coin: CoinFixture;
      deed_launcher_id: string;
      new_vault_launcher_id: string;
      current_timestamp: number;
      lineage_proof: LineageFixture;
    };
    expected: {
      vaultCoinId: string;
      newP2VaultPuzzleHash: string;
      coin: CoinFixture;
      puzzleReveal: string;
      solution: string;
    };
  }[];
  deed_migrate_spend: {
    label: string;
    input: {
      old_vault_launcher_id: string;
      old_vault_inner_puzzle_hash: string;
      vault_coin_id: string;
      deed_launcher_id: string;
      deed_coin: CoinFixture;
      new_vault_launcher_id: string;
      deed_lineage_proof: LineageFixture;
    };
    expected: {
      deedCoinId: string;
      p2VaultInnerPuzzleHash: string;
      newP2VaultPuzzleHash: string;
      coin: CoinFixture;
      puzzleReveal: string;
      solution: string;
    };
  }[];
}

const fixtures = fixturesJson as FixtureFile;

function toLineage(l: LineageFixture): SingletonLineageProof {
  return {
    parentParentCoinInfo: l.parentParentCoinInfo,
    parentInnerPuzzleHash: l.parentInnerPuzzleHash,
    parentAmount: l.parentAmount,
  };
}

describe('VaultMigrateSpendService', () => {
  let service: VaultMigrateSpendService;
  let wasmService: ChiaWasmService;

  beforeAll(async () => {
    if ((window as unknown as { ChiaSDK?: unknown }).ChiaSDK) {
      return;
    }
    // @ts-ignore — deep-import path; types from chia_wallet_sdk_wasm.d.ts.
    const wasmExports = await import('chia-wallet-sdk-wasm/chia_wallet_sdk_wasm_bg.js');
    const response = await fetch('/assets/chia_wasm/chia_wallet_sdk_wasm_bg.wasm');
    if (!response.ok) {
      throw new Error(`WASM asset fetch failed: ${response.status} ${response.statusText}.`);
    }
    const bytes = await response.arrayBuffer();
    const result = await WebAssembly.instantiate(bytes, {
      './chia_wallet_sdk_wasm_bg.js': wasmExports as unknown as WebAssembly.ModuleImports,
    });
    const setWasm = (wasmExports as unknown as { __wbg_set_wasm?: (w: WebAssembly.Exports) => void })
      .__wbg_set_wasm;
    if (typeof setWasm !== 'function') {
      throw new Error('chia_wallet_sdk_wasm_bg.js missing __wbg_set_wasm');
    }
    setWasm(result.instance.exports);
    (window as unknown as { ChiaSDK: unknown }).ChiaSDK = wasmExports;
  });

  beforeEach(() => {
    TestBed.configureTestingModule({
      providers: [provideHttpClient(), provideHttpClientTesting()],
    });
    wasmService = TestBed.inject(ChiaWasmService);
    wasmService.probeReady();
    service = TestBed.inject(VaultMigrateSpendService);
  });

  it('SPEND_MIGRATE opcode matches the Python value', () => {
    expect(SPEND_MIGRATE).toBe(fixtures.constants.spend_migrate);
  });

  describe('migrateBlsSigningTree', () => {
    fixtures.migrate_signing_tree.forEach((c) => {
      it(`matches migrate_bls_signing_tree for "${c.label}"`, () => {
        const got = service.migrateBlsSigningTree(
          c.input.deed_launcher_id,
          c.input.new_p2_vault_puzzlehash,
          c.input.vault_coin_id,
        );
        expect(got).withContext(c.label).toBe(c.expected);
      });
    });
  });

  describe('newP2VaultPuzzleHash', () => {
    fixtures.new_p2_vault_puzzle_hash.forEach((c) => {
      it(`matches puzzle_for_p2_vault for "${c.label}"`, () => {
        expect(service.newP2VaultPuzzleHash(c.input.vault_launcher_id))
          .withContext(c.label)
          .toBe(c.expected);
      });
    });
  });

  describe('buildVaultMigrateCoinSpend', () => {
    fixtures.vault_migrate_spend.forEach((c) => {
      it(`matches build_vault_migrate_spend for "${c.label}"`, () => {
        const out = service.buildVaultMigrateCoinSpend({
          oldVaultLauncherId: c.input.old_vault_launcher_id,
          vaultCoin: c.input.vault_coin,
          identity: fixtures.identity,
          params: fixtures.params,
          deedLauncherId: c.input.deed_launcher_id,
          newVaultLauncherId: c.input.new_vault_launcher_id,
          currentTimestamp: c.input.current_timestamp,
          lineageProof: toLineage(c.input.lineage_proof),
        });
        expect(out.vaultCoinId).withContext('vaultCoinId').toBe(c.expected.vaultCoinId);
        expect(out.newP2VaultPuzzleHash).toBe(c.expected.newP2VaultPuzzleHash);
        expect(out.coinSpend.coin.parentCoinInfo).toBe(c.expected.coin.parentCoinInfo);
        expect(out.coinSpend.coin.puzzleHash).toBe(c.expected.coin.puzzleHash);
        expect(Number(out.coinSpend.coin.amount)).toBe(c.expected.coin.amount);
        expect(out.coinSpend.puzzleReveal).withContext('puzzleReveal').toBe(c.expected.puzzleReveal);
        expect(out.coinSpend.solution).withContext('solution').toBe(c.expected.solution);
      });
    });
  });

  describe('buildDeedMigrateCoinSpend', () => {
    fixtures.deed_migrate_spend.forEach((c) => {
      it(`matches the Python deed p2_vault spend for "${c.label}"`, () => {
        const out = service.buildDeedMigrateCoinSpend({
          oldVaultLauncherId: c.input.old_vault_launcher_id,
          oldVaultInnerPuzzleHash: c.input.old_vault_inner_puzzle_hash,
          vaultCoinId: c.input.vault_coin_id,
          deedLauncherId: c.input.deed_launcher_id,
          deedCoin: c.input.deed_coin,
          newVaultLauncherId: c.input.new_vault_launcher_id,
          deedLineageProof: toLineage(c.input.deed_lineage_proof),
        });
        expect(out.deedCoinId).withContext('deedCoinId').toBe(c.expected.deedCoinId);
        expect(out.p2VaultInnerPuzzleHash).toBe(c.expected.p2VaultInnerPuzzleHash);
        expect(out.newP2VaultPuzzleHash).toBe(c.expected.newP2VaultPuzzleHash);
        expect(out.coinSpend.coin.parentCoinInfo).toBe(c.expected.coin.parentCoinInfo);
        expect(out.coinSpend.coin.puzzleHash).toBe(c.expected.coin.puzzleHash);
        expect(Number(out.coinSpend.coin.amount)).toBe(c.expected.coin.amount);
        expect(out.coinSpend.puzzleReveal).withContext('puzzleReveal').toBe(c.expected.puzzleReveal);
        expect(out.coinSpend.solution).withContext('solution').toBe(c.expected.solution);
      });
    });
  });
});
