import { Injectable, inject } from '@angular/core';

import { ChiaWasmService } from '../chia-wasm.service';
import {
  ChiaWalletService,
  SignedSpendBundle,
  UnsignedCoinSpend,
} from '../chia-wallet.service';
import { CoinsetService, PushTxResponse } from '../coinset.service';
import { WalletCoinPickerService } from '../wallet-coin-picker.service';
import { ADMIN_AUTHORITY_V2_INNER_PUZZLE_HEX } from './admin-authority-v2.puzzle-hex';
import { environment } from '../../../environments/environment';

/**
 * TS port of selected helpers from
 * ``populis_protocol/populis_puzzles/admin_authority_v2_driver.py``.
 *
 * **Why this exists.** The portal's WASM-first path needs to construct
 * v2 admin-authority spends + verify singleton state without contacting
 * the Populis API.  This service is the canonical client-side
 * implementation of the off-chain helpers the puzzle's state-hash
 * defun mirrors.
 *
 * **Cross-repo binding.** The Python helpers in
 * ``admin_authority_v2_driver.py`` are the source of truth.  This TS
 * port is validated against the JSON fixture
 * ``admin-authority-v2.fixtures.json`` (regenerated by
 * ``populis_protocol/scripts/dump_v2_fixtures.py`` and pinned by the
 * cross-repo regression test ``tests/test_v2_fixtures.py``).
 *
 * **Engineering notes:**
 * * All hash computation goes through ``chia-wallet-sdk-wasm``'s
 *   ``Clvm`` so we share the exact tree-hash algorithm with the
 *   on-chain puzzle.  No re-implementation of sha256tree in TS.
 * * Currying uses ``Program.curry()`` rather than the lower-level
 *   ``curryTreeHash`` helper — slightly more allocations but the
 *   resulting Programs can be reused for spend construction in
 *   later D-N phases.
 */
@Injectable({ providedIn: 'root' })
export class AdminAuthorityV2Service {
  private readonly wasm = inject(ChiaWasmService);
  private readonly chiaWallet = inject(ChiaWalletService);
  private readonly coinset = inject(CoinsetService);
  private readonly coinPicker = inject(WalletCoinPickerService);

  /**
   * Empty-list tree-hash sentinel.  Equals ``sha256tree(())`` and is
   * used as the curried ``PENDING_KEY_OPS_HASH`` of a freshly-launched
   * singleton (no pending ops).  Matches Python's
   * ``admin_authority_v2_driver.EMPTY_LIST_HASH``.
   */
  static readonly EMPTY_LIST_HASH =
    '0x4bf5122f344554c53bde2ebb8cd2b7e3d1600ad631c385a5d7cce23c7785459a';

  /**
   * Tree hash of ``singleton_top_layer_v1_1.clsp`` from chia-blockchain.
   * The v2 admin-authority singleton wraps its inner puzzle in this
   * standard top layer.  Pinned in the cross-repo fixture at
   * ``constants.singleton_mod_hash`` so any drift in the chia ecosystem
   * surfaces immediately as a Karma test failure.
   */
  static readonly SINGLETON_MOD_HASH =
    '0x7faa3253bfddd1e0decb0906b2dc6247bbc4cf608f58345d173adb63e8b47c9f';

  /**
   * Tree hash of ``singleton_launcher.clsp``.  This is the puzzle hash
   * the launcher coin lives at — its solution-of-3 emits a CREATE_COIN
   * for the eve coin + a CREATE_PUZZLE_ANNOUNCEMENT.  Pinned in the
   * cross-repo fixture at ``constants.singleton_launcher_hash``.
   */
  static readonly SINGLETON_LAUNCHER_HASH =
    '0xeff07522495060c066f66f32acc2a77e3a3e737aca8baea4d1a64ea4cdc13da9';

  /**
   * Default eve-coin amount for a fresh singleton launch.  Singletons
   * by convention hold 1 mojo (must be odd) — the value is irrelevant
   * to the singleton's identity, only the launcher coin's id matters.
   */
  static readonly DEFAULT_EVE_AMOUNT = 1n;

  /**
   * Default protocol-policy values mirroring the Python driver.
   * Operators can override at deployment time; these match the
   * design doc's recommended defaults.
   */
  static readonly DEFAULTS = {
    maxAdmins: 25n,
    maxKeysPerAdmin: 10n,
    cooldownBlocks: 1024n,
    recoveryTimeoutBlocks: 5040n,
    pgtGovernancePuzzleHash: '0x' + '00'.repeat(32),
  } as const;

  /**
   * Tree hash of the uncurried inner puzzle.  Curried into every v2
   * inner puzzle as ``SELF_MOD_HASH`` (the puzzle uses it for
   * self-recurry).  The cross-repo regression test pins this value;
   * any drift means the puzzle source changed.
   */
  modHash(): Uint8Array {
    const clvm = this.clvm();
    const puzzleBytes = hexToBytes(ADMIN_AUTHORITY_V2_INNER_PUZZLE_HEX);
    return clvm.deserialize(puzzleBytes).treeHash();
  }

  computeSerializedProgramTreeHash(programHex: string): string {
    const clvm = this.clvm();
    return bytesToHexPrefixed(clvm.deserialize(hexToBytes(programHex.trim())).treeHash());
  }

  /**
   * sha256tree of the 4-tuple ``(mips_root_hash, admins_hash,
   * pending_ops_hash, authority_version)``.  This is the hash the
   * singleton emits as ``CREATE_PUZZLE_ANNOUNCEMENT(0x50 || state_hash)``
   * on every spend, and the value the API publishes via
   * ``GET /admin/auth/authority_v2``.
   *
   * @param mipsRootHash 0x-prefixed 32-byte hex (sha256tree of the MIPS m_of_n).
   * @param adminsHash 0x-prefixed 32-byte hex (sha256tree of the admins list).
   * @param pendingOpsHash 0x-prefixed 32-byte hex (sha256tree of the pending ops list, or EMPTY_LIST_HASH).
   * @param authorityVersion non-negative integer; monotonic per spend.
   */
  computeStateHash(args: {
    mipsRootHash: string;
    adminsHash: string;
    pendingOpsHash: string;
    authorityVersion: number | bigint;
  }): Uint8Array {
    const clvm = this.clvm();
    const list = clvm.list([
      clvm.atom(hexToBytes(args.mipsRootHash)),
      clvm.atom(hexToBytes(args.adminsHash)),
      clvm.atom(hexToBytes(args.pendingOpsHash)),
      clvm.int(BigInt(args.authorityVersion)),
    ]);
    return list.treeHash();
  }

  computeRosterUpdateBindingHash(args: {
    currentMipsRootHash: string;
    currentAdminsHash: string;
    currentPendingOpsHash: string;
    currentAuthorityVersion: number | bigint;
    newAdminsHash: string;
    newMipsRootHash: string;
    newAuthorityVersion: number | bigint;
  }): Uint8Array {
    const clvm = this.clvm();
    const list = clvm.list([
      clvm.int(BigInt(0x07)),
      clvm.atom(hexToBytes(args.currentMipsRootHash)),
      clvm.atom(hexToBytes(args.currentAdminsHash)),
      clvm.atom(hexToBytes(args.currentPendingOpsHash)),
      clvm.int(BigInt(args.currentAuthorityVersion)),
      clvm.atom(hexToBytes(args.newAdminsHash)),
      clvm.atom(hexToBytes(args.newMipsRootHash)),
      clvm.int(BigInt(args.newAuthorityVersion)),
    ]);
    return list.treeHash();
  }

  validateUnsignedRosterSpendPackage(pkg: unknown): AdminRosterSpendPackagePreflight {
    const failures: string[] = [];
    const root = asRecord(pkg);
    if (!root) {
      return preflightResult(['package must be an object']);
    }

    collectForbiddenCredentialFields(root, 'package', failures);

    expectString(root, 'kind', 'admin_authority_v2_roster_update_unsigned_package', failures);
    expectString(root, 'package_status', 'unsigned_package_only', failures);
    expectString(root, 'signing_status', 'not_signed', failures);
    expectString(root, 'broadcast_status', 'not_built_not_submitted', failures);
    expectString(root, 'backend_dependency', 'optional_admin_cross_check_only', failures);
    expectString(root, 'activation_status', 'candidate_not_active_until_admin_roster_update_confirms', failures);

    const launcherId = readString(root, 'launcher_id', failures);
    const current = readRecord(root, 'current', failures);
    const update = readRecord(root, 'update', failures);
    const spendIntent = readRecord(root, 'spend_intent', failures);
    const liveSingleton = readRecord(root, 'live_singleton', failures);
    readArray(root, 'required_local_signer_inputs', failures);
    readRecord(root, 'optional_attachments', failures);

    if (spendIntent) {
      expectString(spendIntent, 'kind', 'admin_authority_v2_roster_update', failures, 'spend_intent.kind');
      expectNumber(spendIntent, 'spend_tag', 0x07, failures, 'spend_intent.spend_tag');
      expectString(spendIntent, 'spend_name', 'ADMIN_ROSTER_UPDATE', failures, 'spend_intent.spend_name');
      expectString(spendIntent, 'binding_hash_source', 'local_admin_authority_v2_service', failures, 'spend_intent.binding_hash_source');
      expectString(spendIntent, 'validation_scope', 'local_unsigned_package_no_broadcast', failures, 'spend_intent.validation_scope');
      if (launcherId && readString(spendIntent, 'launcher_id', failures, 'spend_intent.launcher_id') !== launcherId) {
        failures.push('spend_intent.launcher_id must match launcher_id');
      }
    }

    if (liveSingleton) {
      const source = readString(liveSingleton, 'source', failures, 'live_singleton.source');
      if (source && source !== 'operator_wallet_or_coinset_client' && source !== 'optional_api_lookup') {
        failures.push('live_singleton.source must be operator_wallet_or_coinset_client or optional_api_lookup');
      }
      expectNumber(liveSingleton, 'required_amount', 1, failures, 'live_singleton.required_amount');
    }

    if (!current || !update || !spendIntent) {
      return preflightResult(failures);
    }

    const currentAuthorityVersion = readNumber(current, 'authority_version', failures, 'current.authority_version');
    const newAuthorityVersion = readNumber(update, 'new_authority_version', failures, 'update.new_authority_version');
    if (currentAuthorityVersion !== null && newAuthorityVersion !== null && newAuthorityVersion !== currentAuthorityVersion + 1) {
      failures.push('update.new_authority_version must equal current.authority_version + 1');
    }

    const currentPendingOpsHash = readString(current, 'pending_ops_hash', failures, 'current.pending_ops_hash');
    const newPendingOpsHash = readString(update, 'new_pending_ops_hash', failures, 'update.new_pending_ops_hash');
    if (currentPendingOpsHash && newPendingOpsHash && !sameHexValue(currentPendingOpsHash, newPendingOpsHash)) {
      failures.push('current.pending_ops_hash must equal update.new_pending_ops_hash');
    }

    const currentRecords = readArray(current, 'admin_records', failures, 'current.admin_records');
    const updatedRecords = readArray(update, 'updated_admin_records', failures, 'update.updated_admin_records');
    const newAdminRecord = readRecord(update, 'new_admin_record', failures, 'update.new_admin_record');
    const currentAdminRecords = currentRecords ? adminRecordsFromPackage(currentRecords, 'current.admin_records', failures) : [];
    const updatedAdminRecords = updatedRecords ? adminRecordsFromPackage(updatedRecords, 'update.updated_admin_records', failures) : [];

    if (currentRecords && updatedRecords && newAdminRecord) {
      if (updatedRecords.length !== currentRecords.length + 1) {
        failures.push('update.updated_admin_records must append exactly one admin slot');
      }
      const prefix = updatedRecords.slice(0, currentRecords.length);
      if (JSON.stringify(prefix) !== JSON.stringify(currentRecords)) {
        failures.push('update.updated_admin_records must preserve existing admin records as a prefix');
      }
      const appended = updatedRecords[updatedRecords.length - 1];
      if (JSON.stringify(appended) !== JSON.stringify(newAdminRecord)) {
        failures.push('update.new_admin_record must equal the appended admin record');
      }
      const appendedRecord = asRecord(appended);
      const expectedNewIdx = currentRecords.length;
      if (appendedRecord && appendedRecord['admin_idx'] !== expectedNewIdx) {
        failures.push('update.new_admin_record.admin_idx must equal the next appended slot index');
      }
    }

    const currentMipsRootHash = readString(current, 'mips_root_hash', failures, 'current.mips_root_hash');
    const currentAdminsHash = readString(current, 'admins_hash', failures, 'current.admins_hash');
    const currentStateHash = readString(current, 'state_hash', failures, 'current.state_hash');
    const newMipsRootHash = readString(update, 'new_mips_root_hash', failures, 'update.new_mips_root_hash');
    const newAdminsHash = readString(update, 'new_admins_hash', failures, 'update.new_admins_hash');
    const newStateHash = readString(update, 'new_state_hash', failures, 'update.new_state_hash');
    const updateBindingHash = readString(update, 'roster_update_binding_hash', failures, 'update.roster_update_binding_hash');
    const intentCurrentStateHash = readString(spendIntent, 'current_state_hash', failures, 'spend_intent.current_state_hash');
    const intentNewStateHash = readString(spendIntent, 'new_state_hash', failures, 'spend_intent.new_state_hash');
    const intentBindingHash = readString(spendIntent, 'roster_update_binding_hash', failures, 'spend_intent.roster_update_binding_hash');

    this.compareComputedHashes({
      failures,
      currentAdminRecords,
      updatedAdminRecords,
      currentMipsRootHash,
      currentAdminsHash,
      currentPendingOpsHash,
      currentAuthorityVersion,
      currentStateHash,
      newMipsRootHash,
      newAdminsHash,
      newPendingOpsHash,
      newAuthorityVersion,
      newStateHash,
      updateBindingHash,
      intentCurrentStateHash,
      intentNewStateHash,
      intentBindingHash,
    });

    return preflightResult(failures);
  }

  /**
   * sha256tree of the flat admins list ``((admin_idx leaves m_within) ...)``.
   * Empty list returns the EMPTY_LIST_HASH sentinel.
   */
  computeAdminsHash(admins: ReadonlyArray<AdminRecord>): Uint8Array {
    if (admins.length === 0) {
      return hexToBytes(AdminAuthorityV2Service.EMPTY_LIST_HASH);
    }
    const clvm = this.clvm();
    const records = admins.map((a) =>
      clvm.list([
        clvm.int(BigInt(a.adminIdx)),
        clvm.list(a.leaves.map((leaf) => clvm.atom(hexToBytes(leaf)))),
        clvm.int(BigInt(a.mWithin)),
      ]),
    );
    return clvm.list(records).treeHash();
  }

  /**
   * sha256tree of the flat pending-ops list
   * ``((admin_idx op_kind target_hash activates_at) ...)``.
   * Empty list returns the EMPTY_LIST_HASH sentinel (matches the
   * Python ``compute_pending_ops_hash`` short-circuit).
   */
  computePendingOpsHash(ops: ReadonlyArray<PendingOp>): Uint8Array {
    if (ops.length === 0) {
      return hexToBytes(AdminAuthorityV2Service.EMPTY_LIST_HASH);
    }
    const clvm = this.clvm();
    const records = ops.map((op) =>
      clvm.list([
        clvm.int(BigInt(op.adminIdx)),
        clvm.int(BigInt(op.opKind)),
        clvm.atom(hexToBytes(op.targetHash)),
        clvm.int(BigInt(op.activatesAt)),
      ]),
    );
    return clvm.list(records).treeHash();
  }

  /**
   * Tree hash of the fully-curried inner puzzle for a given protocol
   * policy + state.  Currying order MUST match the on-chain mod's
   * curry sequence (see ``admin_authority_v2_inner.clsp``):
   *
   *     SELF_MOD_HASH, MAX_ADMINS, MAX_KEYS_PER_ADMIN, COOLDOWN_BLOCKS,
   *     RECOVERY_TIMEOUT_BLOCKS, PGT_GOVERNANCE_PUZZLE_HASH,
   *     MIPS_ROOT_HASH, ADMINS_HASH, PENDING_KEY_OPS_HASH,
   *     AUTHORITY_VERSION
   *
   * Drift in this curry sequence relative to Python or Chialisp
   * surfaces as a fixture mismatch in ``admin-authority-v2.service.spec.ts``.
   */
  makeInnerPuzzleHash(args: {
    mipsRootHash: string;
    adminsHash: string;
    pendingOpsHash?: string;
    authorityVersion?: number | bigint;
    maxAdmins?: number | bigint;
    maxKeysPerAdmin?: number | bigint;
    cooldownBlocks?: number | bigint;
    recoveryTimeoutBlocks?: number | bigint;
    pgtGovernancePuzzleHash?: string;
  }): Uint8Array {
    const D = AdminAuthorityV2Service.DEFAULTS;
    const clvm = this.clvm();
    const puzzle = clvm.deserialize(hexToBytes(ADMIN_AUTHORITY_V2_INNER_PUZZLE_HEX));
    const curried = puzzle.curry([
      clvm.atom(this.modHash()),
      clvm.int(BigInt(args.maxAdmins ?? D.maxAdmins)),
      clvm.int(BigInt(args.maxKeysPerAdmin ?? D.maxKeysPerAdmin)),
      clvm.int(BigInt(args.cooldownBlocks ?? D.cooldownBlocks)),
      clvm.int(BigInt(args.recoveryTimeoutBlocks ?? D.recoveryTimeoutBlocks)),
      clvm.atom(
        hexToBytes(args.pgtGovernancePuzzleHash ?? D.pgtGovernancePuzzleHash),
      ),
      clvm.atom(hexToBytes(args.mipsRootHash)),
      clvm.atom(hexToBytes(args.adminsHash)),
      clvm.atom(hexToBytes(args.pendingOpsHash ?? AdminAuthorityV2Service.EMPTY_LIST_HASH)),
      clvm.int(BigInt(args.authorityVersion ?? 1)),
    ]);
    return curried.treeHash();
  }

  /**
   * Tree hash of the singleton wrapper around an inner puzzle.
   * Equivalent to ``puzzle_for_singleton(launcherId, inner).tree_hash()``
   * where ``inner.tree_hash() === innerPuzzleHash``.
   *
   * Implemented via the standard chia ``curry_and_treehash`` formula
   * applied to ``SINGLETON_MOD_HASH`` with two args:
   *
   *   1. ``SINGLETON_STRUCT(launcher_id) = (MOD_HASH . (LAUNCHER_ID . LAUNCHER_HASH))``
   *   2. The inner puzzle hash itself
   *
   * Cross-checked against ``puzzle_for_singleton`` in
   * ``populis_protocol/tests/test_admin_authority_v2_launch.py``.
   *
   * @param launcherId 0x-prefixed 32-byte hex (the singleton's permanent identifier).
   * @param innerPuzzleHash 0x-prefixed 32-byte hex (sha256tree of the v2 inner puzzle).
   */
  singletonFullPuzzleHash(launcherId: string, innerPuzzleHash: string): Uint8Array {
    const launcherIdBytes = hexToBytes(launcherId);
    const innerHashBytes = hexToBytes(innerPuzzleHash);

    const structHash = this.singletonStructHash(launcherIdBytes);
    const modHashBytes = hexToBytes(AdminAuthorityV2Service.SINGLETON_MOD_HASH);
    const quotedMod = this.treeHashPair(this.qKwTreeHash(), modHashBytes);

    return this.curryAndTreeHash(quotedMod, [structHash, innerHashBytes]);
  }

  /**
   * Compute every deterministic output of a v2 admin-authority launch.
   *
   * Mirrors ``populis_protocol.populis_puzzles.admin_authority_v2_driver.compute_launch_outputs``
   * byte-for-byte (validated by the cross-repo fixture).  Returns the
   * launcher coin, eve coin, and announcement values the portal needs
   * to construct a full launch spend bundle.
   *
   * No signatures or chain reads are performed — every output is a
   * pure function of the inputs.
   */
  computeLaunchOutputs(args: {
    parentCoinId: string;
    eveInnerPuzzleHash: string;
    eveAmount?: number | bigint;
  }): LaunchOutputs {
    const eveAmount = BigInt(args.eveAmount ?? AdminAuthorityV2Service.DEFAULT_EVE_AMOUNT);
    const sdk = this.sdk();
    if (!sdk.Coin) {
      throw new Error(
        'AdminAuthorityV2Service.computeLaunchOutputs: chia-wallet-sdk-wasm Coin class missing.',
      );
    }

    const parentCoinIdBytes = hexToBytes(args.parentCoinId);
    const launcherCoin = new sdk.Coin(
      parentCoinIdBytes,
      hexToBytes(AdminAuthorityV2Service.SINGLETON_LAUNCHER_HASH),
      1n, // launcher coin is always 1 mojo (odd) per chia singleton convention
    );
    const launcherIdBytes = launcherCoin.coinId();
    const launcherIdHex = bytesToHexPrefixed(launcherIdBytes);

    const eveFullPuzzleHashBytes = this.singletonFullPuzzleHash(
      launcherIdHex,
      args.eveInnerPuzzleHash,
    );

    const eveCoin = new sdk.Coin(
      launcherIdBytes,
      eveFullPuzzleHashBytes,
      eveAmount,
    );

    // Build the launcher solution program: (eve_full_ph eve_amount key_value_list).
    // Using Clvm.list to ensure the same CLVM list encoding the launcher
    // puzzle expects (right-nested cons cells terminated by nil).
    const clvm = this.clvm();
    const launcherSolution = clvm.list([
      clvm.atom(eveFullPuzzleHashBytes),
      clvm.int(eveAmount),
      clvm.nil(),
    ]);
    const launcherAnnouncementMessage = launcherSolution.treeHash();

    // Standard chia announcement-id formula: sha256(coin_id || message).
    // We compute this client-side via the WebCrypto-equivalent SubtleCrypto
    // is not available synchronously in WASM contexts, so we use a tiny
    // helper that imports a small sha256 implementation via the WASM
    // tree-hash primitives.  treeHashAtom(arg) = sha256(0x01 || arg) so
    // we can't reuse it directly for raw concatenation hashing; instead
    // we use the WASM SDK's ``Coin.coinId`` formula equivalent: a fresh
    // sha256 over the concatenation.  We build it via Clvm by creating
    // an atom of the concatenated bytes and noting that tree_hash of an
    // atom = sha256(0x01 || bytes).  That's NOT what we want (we want
    // raw sha256), so we go through SubtleCrypto for the announcement id.
    // Browsers + Karma both expose ``crypto.subtle``.
    const announcementInput = new Uint8Array(
      launcherIdBytes.length + launcherAnnouncementMessage.length,
    );
    announcementInput.set(launcherIdBytes, 0);
    announcementInput.set(launcherAnnouncementMessage, launcherIdBytes.length);
    const launcherAnnouncementId = sha256Sync(announcementInput);

    return {
      launcherId: launcherIdHex,
      launcherCoin: {
        parentCoinInfo: bytesToHexPrefixed(launcherCoin.parentCoinInfo),
        puzzleHash: bytesToHexPrefixed(launcherCoin.puzzleHash),
        amount: launcherCoin.amount,
      },
      eveInnerPuzzleHash: args.eveInnerPuzzleHash,
      eveFullPuzzleHash: bytesToHexPrefixed(eveFullPuzzleHashBytes),
      eveCoin: {
        parentCoinInfo: bytesToHexPrefixed(eveCoin.parentCoinInfo),
        puzzleHash: bytesToHexPrefixed(eveCoin.puzzleHash),
        amount: eveCoin.amount,
      },
      launcherAnnouncementMessage: bytesToHexPrefixed(launcherAnnouncementMessage),
      launcherAnnouncementId: bytesToHexPrefixed(launcherAnnouncementId),
    };
  }

  /**
   * Construct the unsigned CoinSpend that spends the launcher coin
   * to create the eve coin.  The launcher uses the standard chia
   * ``singleton_launcher.clsp`` puzzle which is permissionless —
   * no signature is needed, anyone can spend it once it exists.
   *
   * The launcher coin must already exist on chain (created by the
   * funding-coin spend the wallet signed via ``chiaWallet.transfer``).
   * This helper produces the second half of the spend bundle.
   *
   * @param args.parentCoinId The funding coin's id (= launcher coin's
   *   parent_coin_info).  Comes from ``findLauncherParentCoinId``
   *   after parsing the wallet's transfer response.
   * @param args.eveFullPuzzleHash The eve coin's full puzzle hash
   *   (as returned by ``computeLaunchOutputs``).
   * @param args.eveAmount Eve coin amount (typically 1 mojo).
   * @returns Unsigned CoinSpend ready to combine with the wallet's
   *   signed funding spend in a complete spend bundle.
   */
  buildLauncherCoinSpend(args: {
    parentCoinId: string;
    eveFullPuzzleHash: string;
    eveAmount?: number | bigint;
  }): UnsignedCoinSpend {
    const eveAmount = BigInt(args.eveAmount ?? AdminAuthorityV2Service.DEFAULT_EVE_AMOUNT);
    const sdk = this.sdk();
    if (!sdk.Constants?.singletonLauncher) {
      throw new Error(
        'buildLauncherCoinSpend: chia-wallet-sdk-wasm Constants.singletonLauncher missing',
      );
    }

    // Launcher coin's puzzle reveal is just the standard chia
    // singleton_launcher bytecode — no curry needed.  We grab the
    // serialized form directly from the WASM SDK.
    const launcherPuzzleBytes = sdk.Constants.singletonLauncher();

    // Launcher solution: (eve_full_ph eve_amount key_value_list).
    // Same shape as in computeLaunchOutputs; rebuild it here so the
    // CoinSpend's solution is freshly serialised in this Clvm instance.
    const clvm = this.clvm();
    const launcherSolution = clvm.list([
      clvm.atom(hexToBytes(args.eveFullPuzzleHash)),
      clvm.int(eveAmount),
      clvm.nil(),
    ]);
    const launcherSolutionBytes = launcherSolution.serialize();

    return {
      coin: {
        parentCoinInfo: args.parentCoinId,
        puzzleHash: AdminAuthorityV2Service.SINGLETON_LAUNCHER_HASH,
        amount: 1n, // launcher coin is always 1 mojo
      },
      puzzleReveal: bytesToHexPrefixed(launcherPuzzleBytes),
      solution: bytesToHexPrefixed(launcherSolutionBytes),
    };
  }

  /**
   * Find which coin spend in a wallet-returned bundle creates the
   * launcher coin (puzzle_hash = SINGLETON_LAUNCHER_HASH, amount = 1).
   *
   * The wallet's ``transfer`` result may include change spends and
   * other side outputs.  We need to identify which specific coin's
   * spend produced the launcher so we can compute the launcher's
   * parent (= that coin's id).
   *
   * Algorithm: deserialise + run each coinSpend's puzzle with its
   * solution, scan emitted CREATE_COIN conditions for one that
   * creates ``(SINGLETON_LAUNCHER_HASH, 1)``.  The producing coin's
   * id is what we want.
   *
   * @returns The coin id (hex) of the funding coin whose spend
   *   created the launcher.  Throws if no coinSpend in the bundle
   *   creates a launcher coin (i.e. the wallet didn't honour the
   *   transfer to SINGLETON_LAUNCHER_HASH).
   */
  findLauncherParentCoinId(
    coinSpends: ReadonlyArray<UnsignedCoinSpend>,
  ): string {
    const sdk = this.sdk();
    if (!sdk.Coin || !sdk.Clvm) {
      throw new Error(
        'findLauncherParentCoinId: chia-wallet-sdk-wasm Clvm/Coin missing',
      );
    }
    const targetHashHex = AdminAuthorityV2Service.SINGLETON_LAUNCHER_HASH.toLowerCase();
    const targetHashBytes = hexToBytes(targetHashHex);

    for (const cs of coinSpends) {
      const clvm = new sdk.Clvm();
      let conditions;
      try {
        const puzzle = clvm.deserialize(hexToBytes(cs.puzzleReveal));
        const solution = clvm.deserialize(hexToBytes(cs.solution));
        // High cost cap; we just need the conditions, not a tight
        // mempool-mode replay.  ``puzzle.run`` returns a ProgramOutput.
        const output = (puzzle as unknown as { run: (s: ProgramShape, c: number, m: boolean) => { value: ProgramShape } })
          .run(solution, 11_000_000, false);
        conditions = output.value;
      } catch {
        // If a coin spend's puzzle/solution can't be replayed (rare
        // for standard wallet spends), skip it; another spend in the
        // bundle may still produce the launcher.
        continue;
      }

      const condArray = (conditions as unknown as { toList: () => ProgramShape[] }).toList();
      for (const cond of condArray) {
        const condList = (cond as unknown as { toList: () => ProgramShape[] }).toList();
        if (condList.length < 3) continue;
        // CREATE_COIN opcode = 51 (0x33).
        const opcode = (condList[0] as unknown as { toAtom: () => Uint8Array }).toAtom();
        if (opcode.length !== 1 || opcode[0] !== 51) continue;
        const ph = (condList[1] as unknown as { toAtom: () => Uint8Array }).toAtom();
        const amountBytes = (condList[2] as unknown as { toAtom: () => Uint8Array }).toAtom();
        // Match (SINGLETON_LAUNCHER_HASH, 1).  CLVM amount=1 is encoded as a single 0x01 byte.
        if (
          ph.length === targetHashBytes.length &&
          ph.every((b, i) => b === targetHashBytes[i]) &&
          amountBytes.length === 1 &&
          amountBytes[0] === 1
        ) {
          // This coin spend created the launcher; return its coin id.
          const coin = new sdk.Coin(
            hexToBytes(cs.coin.parentCoinInfo),
            hexToBytes(cs.coin.puzzleHash),
            BigInt(typeof cs.coin.amount === 'bigint' ? cs.coin.amount : cs.coin.amount),
          );
          return bytesToHexPrefixed(coin.coinId());
        }
      }
    }

    throw new Error(
      'findLauncherParentCoinId: no coin spend in the bundle creates a ' +
        '(SINGLETON_LAUNCHER_HASH, 1) coin.  Did the wallet honour the ' +
        'transfer target?',
    );
  }

  /**
   * Full genesis launch orchestration: ask the wallet to fund the
   * launcher, find the funding coin id from its response, build the
   * launcher's CoinSpend, combine, push to coinset.
   *
   * Returns the launcher_id (= singleton's permanent identifier) plus
   * the full LaunchOutputs and the coinset response.  The wizard
   * displays the launcher_id and starts polling
   * ``coinset.getCoinRecordByName(launcherId)`` for confirmation.
   *
   * **Failure modes (all surface as thrown errors):**
   * * Wallet not connected → "wallet not connected".
   * * Wallet auto-broadcasts → actionable message about needing
   *   sign-and-return mode.
   * * Wallet rejects the transfer → user-rejection error verbatim.
   * * Wallet doesn't actually fund the launcher → clear message
   *   from ``findLauncherParentCoinId``.
   * * coinset rejects the bundle → ``pushTransaction`` throws with
   *   the node's error message.
   */
  /**
   * Build a funding-coin spend client-side via WASM and ask the
   * connected wallet to sign it via the CHIP-0002 ``signCoinSpends``
   * RPC.  Returns the resulting signed bundle (single coin spend +
   * aggregated signature).
   *
   * This replaces the older ``ChiaWalletService.transfer`` flow,
   * which Goby's documented ``transfer`` schema can't satisfy:
   * Goby always auto-broadcasts, returns just a transaction id, and
   * doesn't expose a ``waitForConfirmation: false`` knob.
   * ``signCoinSpends`` is the canonical wallet-agnostic path
   * (Goby + Sage both implement it).
   *
   * **Pipeline:**
   *
   *   1. Pick the largest unspent coin under the wallet's first
   *      receive address via {@link WalletCoinPickerService}.
   *   2. Fetch the full coin record from coinset (we need
   *      ``parent_coin_info`` + the actual on-chain ``puzzle_hash``
   *      + the full ``amount`` to compute change).
   *   3. Build a delegated spend with ``CREATE_COIN(target, amount)``
   *      and (if needed) ``CREATE_COIN(change_address, change)``.
   *   4. Wrap in ``standardSpend`` curried with the wallet's
   *      synthetic public key (Goby/Sage's ``getPublicKeys`` returns
   *      synthetic keys per CHIP-0002).
   *   5. Use the WASM ``Clvm`` to materialise the spend's puzzle
   *      reveal + solution as serialised bytes.
   *   6. Convert to wire format (hex) and call
   *      ``ChiaWalletService.signSpendBundle`` which routes through
   *      the wallet's CHIP-0002 ``signCoinSpends``.
   *
   * The returned ``aggregatedSignature`` is a 96-byte BLS signature
   * over all the ``AGG_SIG_ME`` conditions in the spend (the
   * standard puzzle's signature requirement).
   *
   * @returns Signed bundle: one coin spend + aggregated signature.
   */
  private async buildAndSignFundingSpend(args: {
    targetPuzzleHash: string;
    amount: bigint;
  }): Promise<SignedSpendBundle> {
    const sdk = this.sdk();
    if (!sdk.Clvm || !sdk.Coin || !sdk.PublicKey || !sdk.standardPuzzleHash) {
      throw new Error(
        'buildAndSignFundingSpend: chia-wallet-sdk-wasm is missing ' +
          'Clvm/Coin/PublicKey/standardPuzzleHash exports — cannot construct funding spend.',
      );
    }

    const pubkeyHex = this.chiaWallet.pubkey();
    if (!pubkeyHex) {
      throw new Error('buildAndSignFundingSpend: wallet not connected');
    }
    const syntheticKey = sdk.PublicKey.fromBytes(hexToBytes(pubkeyHex));
    const fundingPuzzleHashBytes = sdk.standardPuzzleHash(syntheticKey);
    const fundingPuzzleHash = bytesToHexPrefixed(fundingPuzzleHashBytes);
    const fundingAddress = this.encodeAddress(fundingPuzzleHashBytes);

    // 1. Pick a coin via the wallet bridge + coinset.
    const pick = await this.coinPicker.pickLargestUnspentCoinForPuzzleHash({
      puzzleHash: fundingPuzzleHash,
      displayAddress: fundingAddress,
    });

    // 2. Fetch the full coin record (need parent_coin_info + amount).
    const record = await this.coinset.getCoinRecordByName(pick.coinId);
    if (!record) {
      throw new Error(
        `buildAndSignFundingSpend: coin ${pick.coinId} not found on chain. ` +
          'It may have been spent between the pick and the submit. Retry.',
      );
    }
    const coinAmount = BigInt(record.coin.amount);
    const sendAmount = args.amount;
    if (!sameHexValue(record.coin.puzzle_hash, fundingPuzzleHash)) {
      throw new Error(
        'buildAndSignFundingSpend: selected coin puzzle hash no longer matches ' +
          'the connected wallet public key. Retry with an unlocked coin at ' +
          `${fundingPuzzleHash}.`,
      );
    }
    if (coinAmount < sendAmount) {
      throw new Error(
        `buildAndSignFundingSpend: picked coin holds only ${coinAmount} ` +
          `mojos, but funding requires ${sendAmount}. Top up the wallet.`,
      );
    }
    const changeAmount = coinAmount - sendAmount;

    // 3-5. Build the spend via WASM.
    const clvm = new sdk.Clvm();
    const launcherPhBytes = hexToBytes(args.targetPuzzleHash);
    const changePhBytes = fundingPuzzleHashBytes;

    const conditions = [clvm.createCoin(launcherPhBytes, sendAmount, undefined)];
    if (changeAmount > 0n) {
      conditions.push(clvm.createCoin(changePhBytes, changeAmount, undefined));
    }
    const innerSpend = clvm.delegatedSpend(conditions);

    // Build the source coin object + spend it as a standard coin.
    const sourceCoin = new sdk.Coin(
      hexToBytes(record.coin.parent_coin_info),
      hexToBytes(record.coin.puzzle_hash),
      coinAmount,
    );
    clvm.spendStandardCoin(sourceCoin, syntheticKey, innerSpend);

    // 6. Extract the resulting CoinSpend and convert to our wire
    // format.  ``coinSpends()`` returns everything spent through this
    // Clvm instance — for our case that's exactly one entry.
    const coinSpends = clvm.coinSpends();
    if (coinSpends.length !== 1) {
      throw new Error(
        `buildAndSignFundingSpend: expected 1 coin spend, got ` +
          `${coinSpends.length}`,
      );
    }
    const cs = coinSpends[0];
    const puzzleRevealHash = bytesToHexPrefixed(clvm.deserialize(cs.puzzleReveal).treeHash());
    const coinPuzzleHash = bytesToHexPrefixed(cs.coin.puzzleHash);
    if (!sameHexValue(puzzleRevealHash, coinPuzzleHash)) {
      throw new Error(
        `buildAndSignFundingSpend: local funding spend would fail WRONG_PUZZLE_HASH ` +
          `(coin puzzle hash ${coinPuzzleHash}, puzzle reveal hash ${puzzleRevealHash}). ` +
          `Fund an unlocked standard wallet coin at ${fundingPuzzleHash} and retry.`,
      );
    }
    const unsigned: UnsignedCoinSpend[] = [
      {
        coin: {
          parentCoinInfo: bytesToHexPrefixed(cs.coin.parentCoinInfo),
          puzzleHash: bytesToHexPrefixed(cs.coin.puzzleHash),
          amount: cs.coin.amount,
        },
        puzzleReveal: bytesToHexPrefixed(cs.puzzleReveal),
        solution: bytesToHexPrefixed(cs.solution),
      },
    ];

    // Hand off to wallet for signing.  The wallet signs all
    // AGG_SIG_ME conditions in the inner solution and returns the
    // aggregated 96-byte BLS signature.  We get back the same coin
    // spends (echoed) + the signature.
    return await this.chiaWallet.signSpendBundle(unsigned);
  }

  async submitLaunch(args: {
    eveInnerPuzzleHash: string;
    eveAmount?: number | bigint;
  }): Promise<{
    launcherId: string;
    launchOutputs: LaunchOutputs;
    pushResponse: PushTxResponse;
    fullSpendBundle: SignedSpendBundle;
  }> {
    // 1. Build the funding-coin spend client-side via WASM, then ask
    // the wallet to sign it via the CHIP-0002 ``signCoinSpends`` RPC.
    //
    // We DO NOT use Goby's deprecated ``transfer`` RPC here because:
    //   * It always auto-broadcasts (no ``waitForConfirmation`` field
    //     in the documented schema).
    //   * It only returns ``{ id: string }`` — a transaction id, not
    //     the signed spend bundle we'd need to combine with our
    //     launcher spend before broadcasting.
    //   * Goby v1.0+ rejects calls without an ``assetId`` field with
    //     "Invalid assetId" (code 4000) and the bundle is internally
    //     rebroadcast through a different path that 400s on
    //     non-standard puzzle hashes (the singleton launcher).
    //
    // ``signCoinSpends`` is the canonical CHIP-0002 path: we provide
    // the unsigned coin spend, the wallet returns just the
    // aggregated signature (no broadcast).
    const fundingResult = await this.buildAndSignFundingSpend({
      targetPuzzleHash: AdminAuthorityV2Service.SINGLETON_LAUNCHER_HASH,
      amount: 1n,
    });

    // 2. Find which spend in the result created the launcher coin.
    // Its source coin's id is the launcher's parent_coin_info.
    const fundingCoinId = this.findLauncherParentCoinId(fundingResult.coinSpends);

    // 3. Now we know the parent → derive every launch output.
    const launchOutputs = this.computeLaunchOutputs({
      parentCoinId: fundingCoinId,
      eveInnerPuzzleHash: args.eveInnerPuzzleHash,
      eveAmount: args.eveAmount,
    });

    // 4. Build the launcher's permissionless coin spend.
    const launcherSpend = this.buildLauncherCoinSpend({
      parentCoinId: fundingCoinId,
      eveFullPuzzleHash: launchOutputs.eveFullPuzzleHash,
      eveAmount: args.eveAmount,
    });

    // 5. Combine wallet's signed funding spend + our launcher spend
    // into one bundle.  The aggregated_signature only covers the
    // funding spend's AGG_SIGs; the launcher spend has none.
    const fullSpendBundle: SignedSpendBundle = {
      coinSpends: [...fundingResult.coinSpends, launcherSpend],
      aggregatedSignature: fundingResult.aggregatedSignature,
    };

    // 6. Push the combined bundle to coinset.org.
    const pushResponse = await this.coinset.pushTransaction(fullSpendBundle);

    return {
      launcherId: launchOutputs.launcherId,
      launchOutputs,
      pushResponse,
      fullSpendBundle,
    };
  }

  // ───────────────────────────────────────────────────────────────────
  // Internal helpers — curry-and-treehash math.
  //
  // These reproduce ``chia.wallet.util.curry_and_treehash`` in TS.  The
  // formula (from Chia source) is:
  //
  //   curry_and_treehash(quoted_mod, *args) =
  //     pair(A_KW, pair(quoted_mod, pair(curried_values_tree_hash(args), NIL)))
  //
  //   curried_values_tree_hash([])       = ONE_TREEHASH
  //   curried_values_tree_hash([a, ...]) =
  //     pair(C_KW, pair(pair(Q_KW, a), pair(curried_values_tree_hash([...]), NIL)))
  //
  // We use ``treeHashPair`` from chia-wallet-sdk-wasm rather than
  // computing sha256 manually so the implementation shares the exact
  // hashing primitive used by every other Chia tooling.
  // ───────────────────────────────────────────────────────────────────

  private compareComputedHashes(args: {
    failures: string[];
    currentAdminRecords: AdminRecord[];
    updatedAdminRecords: AdminRecord[];
    currentMipsRootHash: string | null;
    currentAdminsHash: string | null;
    currentPendingOpsHash: string | null;
    currentAuthorityVersion: number | null;
    currentStateHash: string | null;
    newMipsRootHash: string | null;
    newAdminsHash: string | null;
    newPendingOpsHash: string | null;
    newAuthorityVersion: number | null;
    newStateHash: string | null;
    updateBindingHash: string | null;
    intentCurrentStateHash: string | null;
    intentNewStateHash: string | null;
    intentBindingHash: string | null;
  }): void {
    try {
      if (args.currentAdminsHash) {
        const computedCurrentAdminsHash = bytesToHexPrefixed(this.computeAdminsHash(args.currentAdminRecords));
        if (!sameHexValue(args.currentAdminsHash, computedCurrentAdminsHash)) {
          args.failures.push('current.admins_hash must match computed admin records hash');
        }
      }
      if (args.newAdminsHash) {
        const computedUpdatedAdminsHash = bytesToHexPrefixed(this.computeAdminsHash(args.updatedAdminRecords));
        if (!sameHexValue(args.newAdminsHash, computedUpdatedAdminsHash)) {
          args.failures.push('update.new_admins_hash must match computed admin records hash');
        }
      }
      if (
        args.currentMipsRootHash &&
        args.currentAdminsHash &&
        args.currentPendingOpsHash &&
        args.currentAuthorityVersion !== null
      ) {
        const computedCurrentStateHash = bytesToHexPrefixed(
          this.computeStateHash({
            mipsRootHash: args.currentMipsRootHash,
            adminsHash: args.currentAdminsHash,
            pendingOpsHash: args.currentPendingOpsHash,
            authorityVersion: args.currentAuthorityVersion,
          }),
        );
        compareHex(args.currentStateHash, computedCurrentStateHash, 'current.state_hash must match computed current state hash', args.failures);
        compareHex(args.intentCurrentStateHash, computedCurrentStateHash, 'spend_intent.current_state_hash must match computed current state hash', args.failures);
      }
      if (
        args.newMipsRootHash &&
        args.newAdminsHash &&
        args.newPendingOpsHash &&
        args.newAuthorityVersion !== null
      ) {
        const computedNewStateHash = bytesToHexPrefixed(
          this.computeStateHash({
            mipsRootHash: args.newMipsRootHash,
            adminsHash: args.newAdminsHash,
            pendingOpsHash: args.newPendingOpsHash,
            authorityVersion: args.newAuthorityVersion,
          }),
        );
        compareHex(args.newStateHash, computedNewStateHash, 'update.new_state_hash must match computed update state hash', args.failures);
        compareHex(args.intentNewStateHash, computedNewStateHash, 'spend_intent.new_state_hash must match computed update state hash', args.failures);
      }
      if (
        args.currentMipsRootHash &&
        args.currentAdminsHash &&
        args.currentPendingOpsHash &&
        args.currentAuthorityVersion !== null &&
        args.newAdminsHash &&
        args.newMipsRootHash &&
        args.newAuthorityVersion !== null
      ) {
        const computedBindingHash = bytesToHexPrefixed(
          this.computeRosterUpdateBindingHash({
            currentMipsRootHash: args.currentMipsRootHash,
            currentAdminsHash: args.currentAdminsHash,
            currentPendingOpsHash: args.currentPendingOpsHash,
            currentAuthorityVersion: args.currentAuthorityVersion,
            newAdminsHash: args.newAdminsHash,
            newMipsRootHash: args.newMipsRootHash,
            newAuthorityVersion: args.newAuthorityVersion,
          }),
        );
        compareHex(args.updateBindingHash, computedBindingHash, 'update.roster_update_binding_hash must match computed roster update binding hash', args.failures);
        compareHex(args.intentBindingHash, computedBindingHash, 'spend_intent.roster_update_binding_hash must match computed roster update binding hash', args.failures);
      }
    } catch (e) {
      args.failures.push(`local preflight hash recomputation failed: ${errorMessage(e)}`);
    }
  }

  private singletonStructHash(launcherIdBytes: Uint8Array): Uint8Array {
    // SINGLETON_STRUCT = (MOD_HASH . (LAUNCHER_ID . LAUNCHER_HASH))
    // sha256tree of a cons cell = treeHashPair(treeHash(left), treeHash(right))
    const launcherHashBytes = hexToBytes(AdminAuthorityV2Service.SINGLETON_LAUNCHER_HASH);
    const modHashBytes = hexToBytes(AdminAuthorityV2Service.SINGLETON_MOD_HASH);
    const innerPair = this.treeHashPair(
      this.treeHashAtom(launcherIdBytes),
      this.treeHashAtom(launcherHashBytes),
    );
    return this.treeHashPair(this.treeHashAtom(modHashBytes), innerPair);
  }

  private curryAndTreeHash(quotedMod: Uint8Array, args: Uint8Array[]): Uint8Array {
    return this.treeHashPair(
      this.aKwTreeHash(),
      this.treeHashPair(
        quotedMod,
        this.treeHashPair(this.curriedValuesTreeHash(args), this.nilTreeHash()),
      ),
    );
  }

  private curriedValuesTreeHash(args: Uint8Array[]): Uint8Array {
    if (args.length === 0) {
      return this.qKwTreeHash(); // ONE_TREEHASH = treeHashAtom([1])
    }
    const [first, ...rest] = args;
    return this.treeHashPair(
      this.cKwTreeHash(),
      this.treeHashPair(
        this.treeHashPair(this.qKwTreeHash(), first),
        this.treeHashPair(this.curriedValuesTreeHash(rest), this.nilTreeHash()),
      ),
    );
  }

  // Memoised single-byte tree hashes (computed once per service lifetime).
  private _qKw?: Uint8Array; // treeHashAtom([1]) — 'q' opcode tree hash
  private _aKw?: Uint8Array; // treeHashAtom([2]) — 'a' opcode tree hash
  private _cKw?: Uint8Array; // treeHashAtom([4]) — 'c' opcode tree hash
  private _nil?: Uint8Array; // treeHashAtom([])  — nil tree hash

  private qKwTreeHash(): Uint8Array {
    return (this._qKw ??= this.treeHashAtom(new Uint8Array([0x01])));
  }
  private aKwTreeHash(): Uint8Array {
    return (this._aKw ??= this.treeHashAtom(new Uint8Array([0x02])));
  }
  private cKwTreeHash(): Uint8Array {
    return (this._cKw ??= this.treeHashAtom(new Uint8Array([0x04])));
  }
  private nilTreeHash(): Uint8Array {
    return (this._nil ??= this.treeHashAtom(new Uint8Array(0)));
  }

  private treeHashAtom(bytes: Uint8Array): Uint8Array {
    const sdk = this.sdk();
    if (!sdk.treeHashAtom) {
      throw new Error('chia-wallet-sdk-wasm missing treeHashAtom export');
    }
    return sdk.treeHashAtom(bytes);
  }

  private treeHashPair(first: Uint8Array, rest: Uint8Array): Uint8Array {
    const sdk = this.sdk();
    if (!sdk.treeHashPair) {
      throw new Error('chia-wallet-sdk-wasm missing treeHashPair export');
    }
    return sdk.treeHashPair(first, rest);
  }

  /**
   * Lazy WASM Clvm accessor.  Throws a clear error if the SDK isn't
   * loaded yet — callers should wait for ``ChiaWasmService.ready()``
   * before invoking the hash helpers.
   */
  private clvm(): ClvmShape {
    const sdk = this.sdk();
    if (!sdk.Clvm) {
      throw new Error(
        'AdminAuthorityV2Service: chia-wallet-sdk-wasm not loaded yet. ' +
          'Await ChiaWasmService.ready() before calling hash helpers.',
      );
    }
    return new sdk.Clvm();
  }

  /** Returns the raw WASM SDK namespace (the contents of `window.ChiaSDK`). */
  private sdk(): SdkShape {
    return this.wasm.sdk() as SdkShape;
  }

  private encodeAddress(puzzleHash: Uint8Array): string {
    const sdk = this.sdk();
    const prefix = environment.chiaNetwork === 'mainnet' ? 'xch' : 'txch';
    if (typeof sdk.Address !== 'function') return bytesToHexPrefixed(puzzleHash);
    return new sdk.Address(puzzleHash, prefix).encode();
  }
}

// ─────────────────────────────────────────────────────────────────────────
// Synchronous SHA-256 used for the launcher-announcement id.  The Web
// Crypto API only exposes async ``crypto.subtle.digest``, but we need
// sync semantics so ``computeLaunchOutputs`` doesn't poison its callers
// with promises.  Implements FIPS 180-4 SHA-256 in pure JS — small
// (~80 LOC equivalent) and fully synchronous.  Used only for
// ``sha256(launcher_id || message)``; everything else flows through
// the WASM tree-hash primitives.
// ─────────────────────────────────────────────────────────────────────────

const SHA256_K = new Uint32Array([
  0x428a2f98, 0x71374491, 0xb5c0fbcf, 0xe9b5dba5, 0x3956c25b, 0x59f111f1,
  0x923f82a4, 0xab1c5ed5, 0xd807aa98, 0x12835b01, 0x243185be, 0x550c7dc3,
  0x72be5d74, 0x80deb1fe, 0x9bdc06a7, 0xc19bf174, 0xe49b69c1, 0xefbe4786,
  0x0fc19dc6, 0x240ca1cc, 0x2de92c6f, 0x4a7484aa, 0x5cb0a9dc, 0x76f988da,
  0x983e5152, 0xa831c66d, 0xb00327c8, 0xbf597fc7, 0xc6e00bf3, 0xd5a79147,
  0x06ca6351, 0x14292967, 0x27b70a85, 0x2e1b2138, 0x4d2c6dfc, 0x53380d13,
  0x650a7354, 0x766a0abb, 0x81c2c92e, 0x92722c85, 0xa2bfe8a1, 0xa81a664b,
  0xc24b8b70, 0xc76c51a3, 0xd192e819, 0xd6990624, 0xf40e3585, 0x106aa070,
  0x19a4c116, 0x1e376c08, 0x2748774c, 0x34b0bcb5, 0x391c0cb3, 0x4ed8aa4a,
  0x5b9cca4f, 0x682e6ff3, 0x748f82ee, 0x78a5636f, 0x84c87814, 0x8cc70208,
  0x90befffa, 0xa4506ceb, 0xbef9a3f7, 0xc67178f2,
]);

function sha256Sync(message: Uint8Array): Uint8Array {
  const ml = message.length;
  const padded = new Uint8Array(Math.ceil((ml + 9) / 64) * 64);
  padded.set(message);
  padded[ml] = 0x80;
  const bits = BigInt(ml) * 8n;
  for (let i = 0; i < 8; i++) {
    padded[padded.length - 1 - i] = Number((bits >> BigInt(i * 8)) & 0xffn);
  }

  const H = new Uint32Array([
    0x6a09e667, 0xbb67ae85, 0x3c6ef372, 0xa54ff53a, 0x510e527f, 0x9b05688c,
    0x1f83d9ab, 0x5be0cd19,
  ]);

  const W = new Uint32Array(64);
  for (let chunk = 0; chunk < padded.length; chunk += 64) {
    for (let i = 0; i < 16; i++) {
      W[i] =
        (padded[chunk + i * 4] << 24) |
        (padded[chunk + i * 4 + 1] << 16) |
        (padded[chunk + i * 4 + 2] << 8) |
        padded[chunk + i * 4 + 3];
    }
    for (let i = 16; i < 64; i++) {
      const s0 = rotr(W[i - 15], 7) ^ rotr(W[i - 15], 18) ^ (W[i - 15] >>> 3);
      const s1 = rotr(W[i - 2], 17) ^ rotr(W[i - 2], 19) ^ (W[i - 2] >>> 10);
      W[i] = (W[i - 16] + s0 + W[i - 7] + s1) | 0;
    }
    let [a, b, c, d, e, f, g, h] = H;
    for (let i = 0; i < 64; i++) {
      const S1 = rotr(e, 6) ^ rotr(e, 11) ^ rotr(e, 25);
      const ch = (e & f) ^ (~e & g);
      const t1 = (h + S1 + ch + SHA256_K[i] + W[i]) | 0;
      const S0 = rotr(a, 2) ^ rotr(a, 13) ^ rotr(a, 22);
      const maj = (a & b) ^ (a & c) ^ (b & c);
      const t2 = (S0 + maj) | 0;
      h = g; g = f; f = e; e = (d + t1) | 0;
      d = c; c = b; b = a; a = (t1 + t2) | 0;
    }
    H[0] = (H[0] + a) | 0; H[1] = (H[1] + b) | 0;
    H[2] = (H[2] + c) | 0; H[3] = (H[3] + d) | 0;
    H[4] = (H[4] + e) | 0; H[5] = (H[5] + f) | 0;
    H[6] = (H[6] + g) | 0; H[7] = (H[7] + h) | 0;
  }

  const out = new Uint8Array(32);
  for (let i = 0; i < 8; i++) {
    out[i * 4] = (H[i] >>> 24) & 0xff;
    out[i * 4 + 1] = (H[i] >>> 16) & 0xff;
    out[i * 4 + 2] = (H[i] >>> 8) & 0xff;
    out[i * 4 + 3] = H[i] & 0xff;
  }
  return out;
}

function rotr(x: number, n: number): number {
  return ((x >>> n) | (x << (32 - n))) | 0;
}

// ─────────────────────────────────────────────────────────────────────────
// Public types mirroring the Python dataclasses.
// ─────────────────────────────────────────────────────────────────────────

/**
 * One admin slot's state.  Maps directly to the Chialisp record
 * ``(admin_idx leaves m_within)`` where ``leaves`` is the flat list
 * of member tree hashes representing the OneOfN of authentication
 * methods this admin can sign with, and ``m_within`` is the threshold
 * for KEY_REMOVE_QUORUM (typically 1 for single-method admins).
 */
export interface AdminRecord {
  /** 0-indexed admin slot identifier; immutable for the admin's lifetime. */
  adminIdx: number | bigint;
  /** 0x-prefixed 32-byte hex hashes of each MIPS member puzzle in this admin's OneOfN. */
  leaves: ReadonlyArray<string>;
  /** KEY_REMOVE_QUORUM threshold within this admin's leaves (1 ≤ m_within ≤ leaves.length). */
  mWithin: number | bigint;
}

/**
 * Coin tuple — mirrors WASM ``Coin`` but as plain JSON-friendly fields
 * so the launch-outputs result can be passed through Angular signals
 * + JSON pipes without holding a reference to the WASM heap.
 */
export interface CoinTuple {
  /** 0x-prefixed 32-byte hex of the coin's parent's coin id. */
  parentCoinInfo: string;
  /** 0x-prefixed 32-byte hex of the coin's puzzle hash. */
  puzzleHash: string;
  /** Mojos held by the coin (always 1 for v2 launcher / eve). */
  amount: bigint;
}

/**
 * Deterministic outputs of a v2 admin-authority launch.  Mirror of the
 * Python ``LaunchOutputs`` dataclass (sans the raw ``launcher_solution``
 * Program — the portal rebuilds that lazily when it actually needs to
 * construct the launcher CoinSpend).
 *
 * Every field is hex-encoded for JSON/signal serialisability.  The
 * launcher coin's ``coinId`` (= ``launcherId``) is the singleton's
 * permanent identifier.
 */
export interface LaunchOutputs {
  launcherId: string;
  launcherCoin: CoinTuple;
  eveInnerPuzzleHash: string;
  eveFullPuzzleHash: string;
  eveCoin: CoinTuple;
  /** sha256tree of the launcher solution — body of the launcher's
   * CREATE_PUZZLE_ANNOUNCEMENT. */
  launcherAnnouncementMessage: string;
  /** sha256(launcherId || announcementMessage) — the value that
   * ASSERT_PUZZLE_ANNOUNCEMENT consumers index by. */
  launcherAnnouncementId: string;
}

/**
 * A pending key-rotation op awaiting activation or veto.  Maps to the
 * Chialisp record ``(admin_idx op_kind target_hash activates_at)``.
 */
export interface PendingOp {
  /** Which admin slot the op affects. */
  adminIdx: number | bigint;
  /** 1 = OP_KIND_ADD, 2 = OP_KIND_REMOVE.  Must match the puzzle constants. */
  opKind: number | bigint;
  /** 0x-prefixed 32-byte hex of the leaf being added or removed. */
  targetHash: string;
  /** Block height at which KEY_ADD_ACTIVATE / KEY_REMOVE_QUORUM becomes spendable. */
  activatesAt: number | bigint;
}

export interface AdminRosterSpendPackagePreflight {
  ok: boolean;
  status: string;
  failures: string[];
}

// ─────────────────────────────────────────────────────────────────────────
// Internal types + helpers.
// ─────────────────────────────────────────────────────────────────────────

/**
 * Loose typing for the WASM Clvm class.  The full type lives in
 * ``chia_wallet_sdk_wasm.d.ts`` (~100 KB) and changes between minor
 * versions; we only need the few methods used here.
 */
interface ClvmShape {
  deserialize(bytes: Uint8Array): ProgramShape;
  atom(value: Uint8Array): ProgramShape;
  int(value: bigint): ProgramShape;
  list(values: ProgramShape[]): ProgramShape;
  pair(first: ProgramShape, rest: ProgramShape): ProgramShape;
  nil(): ProgramShape;
  // ── Standard-spend construction (CHIP-0002 signCoinSpends path) ──
  /** Build a standard-puzzle CREATE_COIN condition. */
  createCoin(
    puzzleHash: Uint8Array,
    amount: bigint,
    memos?: ProgramShape | undefined,
  ): ProgramShape;
  /** Wrap conditions into a delegated-spend (puzzle + solution). */
  delegatedSpend(conditions: ProgramShape[]): SpendShape;
  /** Add a CHIP-0002 standard-puzzle spend for ``coin`` to this Clvm. */
  spendStandardCoin(
    coin: CoinShape,
    syntheticKey: PublicKeyShape,
    spend: SpendShape,
  ): void;
  /** Retrieve all coin spends accumulated in this Clvm instance. */
  coinSpends(): CoinSpendShape[];
}

interface ProgramShape {
  treeHash(): Uint8Array;
  curry(args: ProgramShape[]): ProgramShape;
  /** Serialize the program back to CLVM bytecode (for spend reveals/solutions). */
  serialize(): Uint8Array;
}

interface CoinShape {
  parentCoinInfo: Uint8Array;
  puzzleHash: Uint8Array;
  amount: bigint;
  coinId(): Uint8Array;
}

/** Loose shape for a WASM ``Spend`` (puzzle + solution program pair). */
interface SpendShape {
  puzzle: ProgramShape;
  solution: ProgramShape;
}

/** Loose shape for the WASM ``CoinSpend`` returned by ``Clvm.coinSpends()``. */
interface CoinSpendShape {
  coin: CoinShape;
  puzzleReveal: Uint8Array;
  solution: Uint8Array;
}

/** Loose shape for the WASM ``PublicKey`` (G1 BLS public key). */
interface PublicKeyShape {
  toBytes(): Uint8Array;
}

interface PublicKeyCtor {
  fromBytes(bytes: Uint8Array): PublicKeyShape;
}

interface SdkShape {
  Clvm?: new () => ClvmShape;
  Coin?: new (parent: Uint8Array, puzzleHash: Uint8Array, amount: bigint) => CoinShape;
  /** Static ``PublicKey.fromBytes`` constructor (CHIP-0002 synthetic keys are 48-byte G1 elements). */
  PublicKey?: PublicKeyCtor;
  standardPuzzleHash?: (syntheticKey: PublicKeyShape) => Uint8Array;
  Address?: new (puzzleHash: Uint8Array, prefix: string) => { encode: () => string };
  /**
   * Static-only namespace exposing canonical chia constants.  In WASM 0.33
   * this lives at ``ChiaSDK.Constants`` (NOT ``ChiaSDK.Program``).
   */
  Constants?: {
    /** Serialized chia singleton_launcher.clsp bytecode. */
    singletonLauncher?: () => Uint8Array;
    /** Tree hash of singleton_launcher.clsp. */
    singletonLauncherHash?: () => Uint8Array;
  };
  treeHashAtom?: (atom: Uint8Array) => Uint8Array;
  treeHashPair?: (first: Uint8Array, rest: Uint8Array) => Uint8Array;
}

function preflightResult(failures: string[]): AdminRosterSpendPackagePreflight {
  return {
    ok: failures.length === 0,
    status: failures.length === 0 ? 'passes local checks' : 'fails local checks',
    failures,
  };
}

function asRecord(value: unknown): Record<string, unknown> | null {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

function readRecord(root: Record<string, unknown>, key: string, failures: string[], path = key): Record<string, unknown> | null {
  const value = root[key];
  const record = asRecord(value);
  if (!record) failures.push(`${path} must be an object`);
  return record;
}

function readArray(root: Record<string, unknown>, key: string, failures: string[], path = key): unknown[] | null {
  const value = root[key];
  if (!Array.isArray(value)) {
    failures.push(`${path} must be an array`);
    return null;
  }
  return value;
}

function readString(root: Record<string, unknown>, key: string, failures: string[], path = key): string | null {
  const value = root[key];
  if (typeof value !== 'string' || !value) {
    failures.push(`${path} must be a non-empty string`);
    return null;
  }
  return value;
}

function readNumber(root: Record<string, unknown>, key: string, failures: string[], path = key): number | null {
  const value = root[key];
  if (typeof value !== 'number' || !Number.isInteger(value)) {
    failures.push(`${path} must be an integer`);
    return null;
  }
  return value;
}

function expectString(root: Record<string, unknown>, key: string, expected: string, failures: string[], path = key): void {
  const value = root[key];
  if (value !== expected) failures.push(`${path} must equal ${expected}`);
}

function expectNumber(root: Record<string, unknown>, key: string, expected: number, failures: string[], path = key): void {
  const value = root[key];
  if (value !== expected) failures.push(`${path} must equal ${expected}`);
}

function collectForbiddenCredentialFields(value: unknown, path: string, failures: string[]): void {
  const record = asRecord(value);
  if (!record) {
    if (Array.isArray(value)) {
      value.forEach((item, index) => collectForbiddenCredentialFields(item, `${path}[${index}]`, failures));
    }
    return;
  }
  for (const [key, child] of Object.entries(record)) {
    const lower = key.toLowerCase();
    if (
      lower.includes('bearer') ||
      lower.includes('jwt') ||
      lower.includes('nonce') ||
      lower.includes('signature') ||
      lower.includes('private') ||
      lower.includes('secret') ||
      lower.includes('faucet') ||
      lower.includes('bootstrap')
    ) {
      failures.push(`${path}.${key} must not contain credentials or signatures`);
    }
    collectForbiddenCredentialFields(child, `${path}.${key}`, failures);
  }
}

function adminRecordsFromPackage(records: unknown[], path: string, failures: string[]): AdminRecord[] {
  return records.flatMap((record, index) => {
    const itemPath = `${path}[${index}]`;
    const obj = asRecord(record);
    if (!obj) {
      failures.push(`${itemPath} must be an object`);
      return [];
    }
    const adminIdx = readNumber(obj, 'admin_idx', failures, `${itemPath}.admin_idx`);
    const mWithin = readNumber(obj, 'm_within', failures, `${itemPath}.m_within`);
    const leaves = readArray(obj, 'leaves', failures, `${itemPath}.leaves`);
    const leafHashes = leaves?.flatMap((leaf, leafIndex) => {
      const leafObj = asRecord(leaf);
      if (!leafObj) {
        failures.push(`${itemPath}.leaves[${leafIndex}] must be an object`);
        return [];
      }
      const leafHash = readString(leafObj, 'leaf_hash', failures, `${itemPath}.leaves[${leafIndex}].leaf_hash`);
      return leafHash ? [leafHash] : [];
    }) ?? [];
    if (adminIdx === null || mWithin === null) return [];
    return [{ adminIdx, leaves: leafHashes, mWithin }];
  });
}

function sameHexValue(a: string, b: string): boolean {
  return a.toLowerCase() === b.toLowerCase();
}

function compareHex(actual: string | null, expected: string, message: string, failures: string[]): void {
  if (!actual || !sameHexValue(actual, expected)) failures.push(message);
}

function errorMessage(value: unknown): string {
  return value instanceof Error ? value.message : String(value);
}

/**
 * Decode a 0x-prefixed (or bare) hex string to bytes.  Throws on
 * non-hex characters or odd length.
 */
function hexToBytes(hex: string): Uint8Array {
  let s = hex.startsWith('0x') || hex.startsWith('0X') ? hex.slice(2) : hex;
  if (s.length % 2 !== 0) {
    throw new Error(`hex string has odd length: ${hex}`);
  }
  const out = new Uint8Array(s.length / 2);
  for (let i = 0; i < out.length; i++) {
    const byte = parseInt(s.substring(i * 2, i * 2 + 2), 16);
    if (Number.isNaN(byte)) {
      throw new Error(`invalid hex at byte ${i}: ${hex}`);
    }
    out[i] = byte;
  }
  return out;
}

/**
 * Encode bytes as a 0x-prefixed lowercase hex string.  Stable output
 * for fixture comparisons.
 */
export function bytesToHexPrefixed(bytes: Uint8Array): string {
  let s = '0x';
  for (const b of bytes) {
    s += b.toString(16).padStart(2, '0');
  }
  return s;
}
