import { Injectable, inject } from '@angular/core';

import { ChiaWasmService } from '../chia-wasm.service';
import { ADMIN_AUTHORITY_V2_INNER_PUZZLE_HEX } from './admin-authority-v2.puzzle-hex';

/**
 * TS port of selected helpers from
 * ``populis_protocol/populis_puzzles/admin_authority_v2_driver.py``.
 *
 * **Why this exists.** The portal's WASM-first path needs to construct
 * v2 admin-authority spends + verify singleton state without contacting
 * the Populis API.  This service is the canonical client-side
 * implementation of the off-chain helpers the puzzle's state-hash
 * defun mirrors.
 *
 * **Cross-repo binding.** The Python helpers in
 * ``admin_authority_v2_driver.py`` are the source of truth.  This TS
 * port is validated against the JSON fixture
 * ``admin-authority-v2.fixtures.json`` (regenerated by
 * ``populis_protocol/scripts/dump_v2_fixtures.py`` and pinned by the
 * cross-repo regression test ``tests/test_v2_fixtures.py``).
 *
 * **Engineering notes:**
 * * All hash computation goes through ``chia-wallet-sdk-wasm``'s
 *   ``Clvm`` so we share the exact tree-hash algorithm with the
 *   on-chain puzzle.  No re-implementation of sha256tree in TS.
 * * Currying uses ``Program.curry()`` rather than the lower-level
 *   ``curryTreeHash`` helper — slightly more allocations but the
 *   resulting Programs can be reused for spend construction in
 *   later D-N phases.
 */
@Injectable({ providedIn: 'root' })
export class AdminAuthorityV2Service {
  private readonly wasm = inject(ChiaWasmService);

  /**
   * Empty-list tree-hash sentinel.  Equals ``sha256tree(())`` and is
   * used as the curried ``PENDING_KEY_OPS_HASH`` of a freshly-launched
   * singleton (no pending ops).  Matches Python's
   * ``admin_authority_v2_driver.EMPTY_LIST_HASH``.
   */
  static readonly EMPTY_LIST_HASH =
    '0x4bf5122f344554c53bde2ebb8cd2b7e3d1600ad631c385a5d7cce23c7785459a';

  /**
   * Default protocol-policy values mirroring the Python driver.
   * Operators can override at deployment time; these match the
   * design doc's recommended defaults.
   */
  static readonly DEFAULTS = {
    maxAdmins: 25n,
    maxKeysPerAdmin: 10n,
    cooldownBlocks: 1024n,
    recoveryTimeoutBlocks: 5040n,
    pgtGovernancePuzzleHash: '0x' + '00'.repeat(32),
  } as const;

  /**
   * Tree hash of the uncurried inner puzzle.  Curried into every v2
   * inner puzzle as ``SELF_MOD_HASH`` (the puzzle uses it for
   * self-recurry).  The cross-repo regression test pins this value;
   * any drift means the puzzle source changed.
   */
  modHash(): Uint8Array {
    const clvm = this.clvm();
    const puzzleBytes = hexToBytes(ADMIN_AUTHORITY_V2_INNER_PUZZLE_HEX);
    return clvm.deserialize(puzzleBytes).treeHash();
  }

  /**
   * sha256tree of the 4-tuple ``(mips_root_hash, admins_hash,
   * pending_ops_hash, authority_version)``.  This is the hash the
   * singleton emits as ``CREATE_PUZZLE_ANNOUNCEMENT(0x50 || state_hash)``
   * on every spend, and the value the API publishes via
   * ``GET /admin/auth/authority_v2``.
   *
   * @param mipsRootHash 0x-prefixed 32-byte hex (sha256tree of the MIPS m_of_n).
   * @param adminsHash 0x-prefixed 32-byte hex (sha256tree of the admins list).
   * @param pendingOpsHash 0x-prefixed 32-byte hex (sha256tree of the pending ops list, or EMPTY_LIST_HASH).
   * @param authorityVersion non-negative integer; monotonic per spend.
   */
  computeStateHash(args: {
    mipsRootHash: string;
    adminsHash: string;
    pendingOpsHash: string;
    authorityVersion: number | bigint;
  }): Uint8Array {
    const clvm = this.clvm();
    const list = clvm.list([
      clvm.atom(hexToBytes(args.mipsRootHash)),
      clvm.atom(hexToBytes(args.adminsHash)),
      clvm.atom(hexToBytes(args.pendingOpsHash)),
      clvm.int(BigInt(args.authorityVersion)),
    ]);
    return list.treeHash();
  }

  /**
   * sha256tree of the flat admins list ``((admin_idx leaves m_within) ...)``.
   * Empty list returns the EMPTY_LIST_HASH sentinel.
   */
  computeAdminsHash(admins: ReadonlyArray<AdminRecord>): Uint8Array {
    if (admins.length === 0) {
      return hexToBytes(AdminAuthorityV2Service.EMPTY_LIST_HASH);
    }
    const clvm = this.clvm();
    const records = admins.map((a) =>
      clvm.list([
        clvm.int(BigInt(a.adminIdx)),
        clvm.list(a.leaves.map((leaf) => clvm.atom(hexToBytes(leaf)))),
        clvm.int(BigInt(a.mWithin)),
      ]),
    );
    return clvm.list(records).treeHash();
  }

  /**
   * sha256tree of the flat pending-ops list
   * ``((admin_idx op_kind target_hash activates_at) ...)``.
   * Empty list returns the EMPTY_LIST_HASH sentinel (matches the
   * Python ``compute_pending_ops_hash`` short-circuit).
   */
  computePendingOpsHash(ops: ReadonlyArray<PendingOp>): Uint8Array {
    if (ops.length === 0) {
      return hexToBytes(AdminAuthorityV2Service.EMPTY_LIST_HASH);
    }
    const clvm = this.clvm();
    const records = ops.map((op) =>
      clvm.list([
        clvm.int(BigInt(op.adminIdx)),
        clvm.int(BigInt(op.opKind)),
        clvm.atom(hexToBytes(op.targetHash)),
        clvm.int(BigInt(op.activatesAt)),
      ]),
    );
    return clvm.list(records).treeHash();
  }

  /**
   * Tree hash of the fully-curried inner puzzle for a given protocol
   * policy + state.  Currying order MUST match the on-chain mod's
   * curry sequence (see ``admin_authority_v2_inner.clsp``):
   *
   *     SELF_MOD_HASH, MAX_ADMINS, MAX_KEYS_PER_ADMIN, COOLDOWN_BLOCKS,
   *     RECOVERY_TIMEOUT_BLOCKS, PGT_GOVERNANCE_PUZZLE_HASH,
   *     MIPS_ROOT_HASH, ADMINS_HASH, PENDING_KEY_OPS_HASH,
   *     AUTHORITY_VERSION
   *
   * Drift in this curry sequence relative to Python or Chialisp
   * surfaces as a fixture mismatch in ``admin-authority-v2.service.spec.ts``.
   */
  makeInnerPuzzleHash(args: {
    mipsRootHash: string;
    adminsHash: string;
    pendingOpsHash?: string;
    authorityVersion?: number | bigint;
    maxAdmins?: number | bigint;
    maxKeysPerAdmin?: number | bigint;
    cooldownBlocks?: number | bigint;
    recoveryTimeoutBlocks?: number | bigint;
    pgtGovernancePuzzleHash?: string;
  }): Uint8Array {
    const D = AdminAuthorityV2Service.DEFAULTS;
    const clvm = this.clvm();
    const puzzle = clvm.deserialize(hexToBytes(ADMIN_AUTHORITY_V2_INNER_PUZZLE_HEX));
    const curried = puzzle.curry([
      clvm.atom(this.modHash()),
      clvm.int(BigInt(args.maxAdmins ?? D.maxAdmins)),
      clvm.int(BigInt(args.maxKeysPerAdmin ?? D.maxKeysPerAdmin)),
      clvm.int(BigInt(args.cooldownBlocks ?? D.cooldownBlocks)),
      clvm.int(BigInt(args.recoveryTimeoutBlocks ?? D.recoveryTimeoutBlocks)),
      clvm.atom(
        hexToBytes(args.pgtGovernancePuzzleHash ?? D.pgtGovernancePuzzleHash),
      ),
      clvm.atom(hexToBytes(args.mipsRootHash)),
      clvm.atom(hexToBytes(args.adminsHash)),
      clvm.atom(hexToBytes(args.pendingOpsHash ?? AdminAuthorityV2Service.EMPTY_LIST_HASH)),
      clvm.int(BigInt(args.authorityVersion ?? 1)),
    ]);
    return curried.treeHash();
  }

  /**
   * Lazy WASM Clvm accessor.  Throws a clear error if the SDK isn't
   * loaded yet — callers should wait for ``ChiaWasmService.ready()``
   * before invoking the hash helpers.
   */
  private clvm(): ClvmShape {
    const sdk = this.wasm.sdk() as { Clvm?: new () => ClvmShape };
    if (!sdk?.Clvm) {
      throw new Error(
        'AdminAuthorityV2Service: chia-wallet-sdk-wasm not loaded yet. ' +
          'Await ChiaWasmService.ready() before calling hash helpers.',
      );
    }
    return new sdk.Clvm();
  }
}

// ─────────────────────────────────────────────────────────────────────────
// Public types mirroring the Python dataclasses.
// ─────────────────────────────────────────────────────────────────────────

/**
 * One admin slot's state.  Maps directly to the Chialisp record
 * ``(admin_idx leaves m_within)`` where ``leaves`` is the flat list
 * of member tree hashes representing the OneOfN of authentication
 * methods this admin can sign with, and ``m_within`` is the threshold
 * for KEY_REMOVE_QUORUM (typically 1 for single-method admins).
 */
export interface AdminRecord {
  /** 0-indexed admin slot identifier; immutable for the admin's lifetime. */
  adminIdx: number | bigint;
  /** 0x-prefixed 32-byte hex hashes of each MIPS member puzzle in this admin's OneOfN. */
  leaves: ReadonlyArray<string>;
  /** KEY_REMOVE_QUORUM threshold within this admin's leaves (1 ≤ m_within ≤ leaves.length). */
  mWithin: number | bigint;
}

/**
 * A pending key-rotation op awaiting activation or veto.  Maps to the
 * Chialisp record ``(admin_idx op_kind target_hash activates_at)``.
 */
export interface PendingOp {
  /** Which admin slot the op affects. */
  adminIdx: number | bigint;
  /** 1 = OP_KIND_ADD, 2 = OP_KIND_REMOVE.  Must match the puzzle constants. */
  opKind: number | bigint;
  /** 0x-prefixed 32-byte hex of the leaf being added or removed. */
  targetHash: string;
  /** Block height at which KEY_ADD_ACTIVATE / KEY_REMOVE_QUORUM becomes spendable. */
  activatesAt: number | bigint;
}

// ─────────────────────────────────────────────────────────────────────────
// Internal types + helpers.
// ─────────────────────────────────────────────────────────────────────────

/**
 * Loose typing for the WASM Clvm class.  The full type lives in
 * ``chia_wallet_sdk_wasm.d.ts`` (~100 KB) and changes between minor
 * versions; we only need the few methods used here.
 */
interface ClvmShape {
  deserialize(bytes: Uint8Array): ProgramShape;
  atom(value: Uint8Array): ProgramShape;
  int(value: bigint): ProgramShape;
  list(values: ProgramShape[]): ProgramShape;
}

interface ProgramShape {
  treeHash(): Uint8Array;
  curry(args: ProgramShape[]): ProgramShape;
}

/**
 * Decode a 0x-prefixed (or bare) hex string to bytes.  Throws on
 * non-hex characters or odd length.
 */
function hexToBytes(hex: string): Uint8Array {
  let s = hex.startsWith('0x') || hex.startsWith('0X') ? hex.slice(2) : hex;
  if (s.length % 2 !== 0) {
    throw new Error(`hex string has odd length: ${hex}`);
  }
  const out = new Uint8Array(s.length / 2);
  for (let i = 0; i < out.length; i++) {
    const byte = parseInt(s.substring(i * 2, i * 2 + 2), 16);
    if (Number.isNaN(byte)) {
      throw new Error(`invalid hex at byte ${i}: ${hex}`);
    }
    out[i] = byte;
  }
  return out;
}

/**
 * Encode bytes as a 0x-prefixed lowercase hex string.  Stable output
 * for fixture comparisons.
 */
export function bytesToHexPrefixed(bytes: Uint8Array): string {
  let s = '0x';
  for (const b of bytes) {
    s += b.toString(16).padStart(2, '0');
  }
  return s;
}
